#!/bin/bash

DISABLE_MULTILIB=1

VERSION="7.1-0"

DIR="aspell6-en-${VERSION}"
TARBALL="aspell6-en-${VERSION}.tar.bz2"

SRC1=(
http://ftp.gnu.org/gnu/aspell/dict/en/${TARBALL}
)

MD5SUMS=(
beba5e8f3afd3ed1644653bb685b2dfb
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  ./configure || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://ftp.gnu.org/gnu/aspell/dict/en/'
  VERSION_STRING='aspell6-en-%version%.tar.bz2'
  MIRRORS=(
    'http://ftp.gnu.org/gnu/aspell/dict/en/aspell6-en-%version%.tar.bz2'
  )
}
