#!/bin/bash

DONT_REMOVE=1
DISABLE_MULTILIB=1

VERSION="1.11.2"

DIR="automake-${VERSION}"
TARBALL="automake-${VERSION}.tar.bz2"

SRC1=(
http://ftp.gnu.org/gnu/automake/${TARBALL}
)

MD5SUMS=(
18194e804d415767bae8f703c963d456
)

build(){
  unpack_tarball $TARBALL
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --build=$BUILDHOST \
    --host=$BUILDTARGET --prefix=/usr || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://ftp.gnu.org/gnu/automake/'
  VERSION_STRING='automake-%version%.tar.bz2'
  MIRRORS=(
    'http://ftp.gnu.org/gnu/automake/automake-%version%.tar.bz2'
  )
}
