#!/bin/bash

DONT_REMOVE=1
DISABLE_MULTILIB=1

VERSION="0.8.8"

DIR="docbook2X-${VERSION}"
TARBALL="docbook2X-${VERSION}.tar.gz"

SRC1=(
http://prdownloads.sourceforge.net/docbook2x/${TARBALL}
)

MD5SUMS=(
b9b76a6af198c4f44574cfd17a322f01
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --build=$BUILDHOST \
    --host=$BUILDTARGET --prefix=/usr --sysconfdir=/etc || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://sourceforge.net/projects/docbook2x/files/docbook2x/%version%/'
  VERSION_STRING='docbook2X-%version%.tar.gz'
}
