#!/bin/bash

DISABLE_MULTILIB=1

VERSION="1.0.2"

DIR="font-adobe-utopia-100dpi-${VERSION}"
TARBALL="font-adobe-utopia-100dpi-${VERSION}.tar.bz2"

SRC1=(
http://xorg.freedesktop.org/releases/individual/font/${TARBALL}
)

MD5SUMS=(
1c3a2c26bd3f6e406fbadc7380efa369
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR --sysconfdir=/etc --localstatedir=/var || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

post_install(){
  cd /usr/share/fonts/X11/100dpi || return 1
  mkfontdir || return 1
  mkfontscale || return 1
  fc-cache || return 1
}

post_upgrade(){
  post_install || return 1
}

post_remove(){
  [ -d "/usr/lib/X11/fonts/100dpi" ] && {
    cd /usr/lib/X11/fonts/100dpi || return 1
    mkfontdir || return 1
    mkfontscale || return 1
  }
  fc-cache || return 1
  return 0
}

version_check_info(){
  ADDRESS='http://xorg.freedesktop.org/releases/individual/font/'
  VERSION_STRING='font-adobe-utopia-100dpi-%version%.tar.bz2'
}
