#!/bin/bash

DISABLE_MULTILIB=1

VERSION="2.30.0"

DIR="gconf-editor-${VERSION}"
TARBALL="gconf-editor-${VERSION}.tar.bz2"

SRC1=(
  $(gnome_mirrors gconf-editor)
)

MD5SUMS=(
2a941e3c64843be69190f38891470580
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR --libexecdir=/usr/sbin --sysconfdir=/etc/gnome \
    --localstatedir=/var/lib || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  rm -rf $TMPROOT/var/lib/scrollkeeper
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://ftp.gnome.org/pub/GNOME/sources/gconf-editor/%minor_version%/'
  VERSION_STRING='gconf-editor-%version%.tar.bz2'
  ONLY_EVEN_MINORS=1
}
