#!/bin/bash

DISABLE_MULTILIB=1

VERSION="2.30.2"

DIR="gedit-${VERSION}"
TARBALL="gedit-${VERSION}.tar.bz2"

SRC1=(
  $(gnome_mirrors gedit)
)

MD5SUMS=(
00ccd2fdba5c5e1d3bc54da5377f0277
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR --libexecdir=/usr/sbin --sysconfdir=/etc/gnome \
    --localstatedir=/var/lib || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  rm -rf $TMPROOT/var/lib/scrollkeeper
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://ftp.gnome.org/pub/GNOME/sources/gedit/%minor_version%/'
  VERSION_STRING='gedit-%version%.tar.bz2'
  ONLY_EVEN_MINORS=1
}
