#!/bin/bash

DONT_REMOVE=1
DISABLE_MULTILIB=1

VERSION="2.30"

DIR="iana-etc-${VERSION}"
TARBALL="iana-etc-${VERSION}.tar.bz2"

SRC1=(
http://www.sethwklein.net/${TARBALL}
)

MD5SUMS=(
3ba3afb1d1b261383d247f46cb135ee8
)

build(){
  unpack_tarball $TARBALL
  cd $SRCDIR/$DIR || return 1
  make || return 1
  mkdir -p $TMPROOT/etc
  make install PREFIX=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://sethwklein.net/iana-etc'
  VERSION_STRING='iana-etc-%version%.tar.bz2'
}
