#!/bin/bash

DISABLE_MULTILIB=1

VERSION="0.8.17"

DIR="irssi-${VERSION}"
TARBALL="irssi-${VERSION}.tar.bz2"

SRC1=(
http://www.irssi.org/files/${TARBALL}
)

MD5SUMS=(
ecf64be47978d89a742b435a81cb47db
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR --sysconfdir=/etc || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://www.irssi.org/files/'
  VERSION_STRING='irssi-%version%.tar.bz2'
  VERSION_FILTERS='rc'
}
