#!/bin/bash

DISABLE_MULTILIB=1

VERSION="3.11.1"

DIR="iso-codes-${VERSION}"
TARBALL="iso-codes-${VERSION}.tar.gz"

SRC1=(
ftp://pkg-isocodes.alioth.debian.org/pub/pkg-isocodes/${TARBALL}
)

MD5SUMS=(
9c967ccbae61e03a31d2d038f2081c1b
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='ftp://pkg-isocodes.alioth.debian.org/pub/pkg-isocodes/'
  VERSION_STRING='iso-codes-%version%.tar.gz'
}
