#!/bin/bash

DISABLE_MULTILIB=1

VERSION="0.6.3"

DIR="libcroco-${VERSION}"
TARBALL="libcroco-${VERSION}.tar.bz2"

SRC1=(
  $(gnome_mirrors libcroco)
)

MD5SUMS=(
e1e93eeff4367c896f3959af34ba20eb
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR --sysconfdir=/etc || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://ftp.gnome.org/pub/GNOME/sources/libcroco/%minor_version%/'
  VERSION_STRING='libcroco-%version%.tar.bz2'
  ONLY_EVEN_MINORS=1
}
