#!/bin/bash

DISABLE_MULTILIB=1

VERSION="0.6.20"

DIR="libexif-${VERSION}"
TARBALL="libexif-${VERSION}.tar.bz2"

SRC1=(
http://prdownloads.sourceforge.net/libexif/${TARBALL}
)

MD5SUMS=(
19844ce6b5d075af16f0d45de1e8a6a3
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  sed -i 's% install-data-local % %g' doc/Makefile.in || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://sourceforge.net/projects/libexif/files/libexif/'
  VERSION_STRING='libexif/%version%/'
  VERSION_FILTERS='[a-z][a-z] [A-Z][A-Z]'
}
