#!/bin/bash

DISABLE_MULTILIB=1

VERSION="0.1.11"

DIR="libfm-${VERSION}"
TARBALL="libfm-${VERSION}.tar.gz"

SRC1=(
http://prdownloads.sourceforge.net/pcmanfm/${TARBALL}
)

MD5SUMS=(
65cf42729c0f3fc3c8c1ed03f78ce9fb
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR --sysconfdir=/etc || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS="http://sourceforge.net/projects/pcmanfm/files/"
  VERSION_STRING="libfm-%version%.tar.gz"
}
