#!/bin/bash

DISABLE_MULTILIB=1

VERSION="1.0.10"

DIR="libmng-${VERSION}"
TARBALL="libmng-${VERSION}.tar.gz"

SRC1=(
http://prdownloads.sourceforge.net/libmng/${TARBALL}
)

MD5SUMS=(
a464ae7d679781beebdf7440d144b7bd
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  ln -sf makefiles/configure.in . || return 1
  ln -sf makefiles/Makefile.am . || return 1
  autoreconf -f -i || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://sourceforge.net/project/showfiles.php?group_id=5635&package_id=5691'
  VERSION_STRING='libmng-%version%.tar.gz'
  VERSION_FILTERS='devel'
  MIRRORS=(
    'http://prdownloads.sourceforge.net/libmng/libmng-%version%.tar.gz'
  )
}
