#!/bin/bash

DISABLE_MULTILIB=1

VERSION="0.1.4"

DIR="lxtask-${VERSION}"
TARBALL="lxtask-${VERSION}.tar.gz"

SRC1=(
http://prdownloads.sourceforge.net/lxde/${TARBALL}
)

MD5SUMS=(
c4ab47d03d41a88696d64d3f1e78cf7f
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR --sysconfdir=/etc || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS="http://sourceforge.net/projects/lxde/files/LXTask (task manager)/LXTask %version%/"
  VERSION_STRING="lxtask-%version%.tar.gz"
  VERSION_FILTERS='('
}
