#!/bin/bash

DISABLE_MULTILIB=1

VERSION="1.60"

DIR="net-tools-${VERSION}"
TARBALL="net-tools-${VERSION}.tar.bz2"

SRC1=(
http://www.tazenda.demon.co.uk/phil/net-tools/${TARBALL}
)

MD5SUMS=(
888774accab40217dde927e21979c165
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1

cat << "EOF" | patch -Np1 || return 1
diff -Naur net-tools-1.60/config.in net-tools-1.60.patched/config.in
--- net-tools-1.60/config.in	2000-05-21 10:32:12.000000000 -0400
+++ net-tools-1.60.patched/config.in	2007-08-28 12:13:36.000000000 -0400
@@ -49,7 +49,7 @@
 * 
 bool 'UNIX protocol family' HAVE_AFUNIX y
 bool 'INET (TCP/IP) protocol family' HAVE_AFINET y
-bool 'INET6 (IPv6) protocol family' HAVE_AFINET6 n
+bool 'INET6 (IPv6) protocol family' HAVE_AFINET6 y
 bool 'Novell IPX/SPX protocol family' HAVE_AFIPX y
 bool 'Appletalk DDP protocol family' HAVE_AFATALK y
 bool 'AX25 (packet radio) protocol family' HAVE_AFAX25 y
@@ -86,6 +86,6 @@
 *
 *           Other Features.
 *
-bool 'IP Masquerading support' HAVE_FW_MASQUERADE n
-bool 'Build iptunnel and ipmaddr' HAVE_IP_TOOLS n
-bool 'Build mii-tool' HAVE_MII n
+bool 'IP Masquerading support' HAVE_FW_MASQUERADE y
+bool 'Build iptunnel and ipmaddr' HAVE_IP_TOOLS y
+bool 'Build mii-tool' HAVE_MII y
diff -Naur net-tools-1.60/hostname.c net-tools-1.60.patched/hostname.c
--- net-tools-1.60/hostname.c	2001-04-08 13:04:23.000000000 -0400
+++ net-tools-1.60.patched/hostname.c	2007-08-28 12:13:36.000000000 -0400
@@ -78,6 +78,7 @@
             fprintf(stderr, _("%s: name too long\n"), program_name);
             break;
         default:
+	    ;
         }
 	exit(1);
     }
@@ -98,6 +99,7 @@
 	    fprintf(stderr, _("%s: name too long\n"), program_name);
 	    break;
 	default:
+	    ;
 	}
 	exit(1);
     };
@@ -117,6 +119,7 @@
 	    fprintf(stderr, _("%s: name too long\n"), program_name);
 	    break;
 	default:
+	    ;
 	}
 	exit(1);
     };
@@ -174,6 +177,7 @@
 	printf("%s\n", hp->h_name);
 	break;
     default:
+	;
     }
 }
 
diff -Naur net-tools-1.60/include/mii.h net-tools-1.60.patched/include/mii.h
--- net-tools-1.60/include/mii.h	2000-05-21 10:21:27.000000000 -0400
+++ net-tools-1.60.patched/include/mii.h	2007-08-28 12:13:36.000000000 -0400
@@ -11,11 +11,9 @@
 
 /* network interface ioctl's for MII commands */
 #ifndef SIOCGMIIPHY
-#define SIOCGMIIPHY (SIOCDEVPRIVATE)	/* Read from current PHY */
-#define SIOCGMIIREG (SIOCDEVPRIVATE+1) 	/* Read any PHY register */
-#define SIOCSMIIREG (SIOCDEVPRIVATE+2) 	/* Write any PHY register */
-#define SIOCGPARAMS (SIOCDEVPRIVATE+3) 	/* Read operational parameters */
-#define SIOCSPARAMS (SIOCDEVPRIVATE+4) 	/* Set operational parameters */
+#define SIOCGMIIPHY 0x8947 	/* Read from current PHY */
+#define SIOCGMIIREG 0x8948 	/* Read any PHY register */
+#define SIOCSMIIREG 0x8949 	/* Write any PHY register */
 #endif
 
 #include <linux/types.h>
diff -Naur net-tools-1.60/iptunnel.c net-tools-1.60.patched/iptunnel.c
--- net-tools-1.60/iptunnel.c	2001-04-08 13:04:23.000000000 -0400
+++ net-tools-1.60.patched/iptunnel.c	2007-08-28 12:14:03.000000000 -0400
@@ -25,16 +25,10 @@
 #include <fcntl.h>
 #include <sys/socket.h>
 #include <sys/ioctl.h>
-#include <netinet/in.h>
-#include <netinet/ip.h>
 #include <arpa/inet.h>
-#if defined(__GLIBC__) && (__GLIBC__ > 2 || (__GLIBC__ == 2 && __GLIBC_MINOR__ >= 1))
-#include <net/if.h>
-#include <net/if_arp.h>
-#else
 #include <linux/if.h>
 #include <linux/if_arp.h>
-#endif
+#include <linux/ip.h>
 #include <linux/types.h>
 #include <linux/if_tunnel.h>
 
diff -Naur net-tools-1.60/lib/inet_sr.c net-tools-1.60.patched/lib/inet_sr.c
--- net-tools-1.60/lib/inet_sr.c	2000-02-20 16:46:45.000000000 -0500
+++ net-tools-1.60.patched/lib/inet_sr.c	2007-08-28 12:13:36.000000000 -0400
@@ -105,6 +105,7 @@
     case 2:
        isnet = 0; break;
     default:
+       ;
     }
 
     /* Fill in the other fields. */
diff -Naur net-tools-1.60/lib/x25_sr.c net-tools-1.60.patched/lib/x25_sr.c
--- net-tools-1.60/lib/x25_sr.c	2000-05-20 09:38:10.000000000 -0400
+++ net-tools-1.60.patched/lib/x25_sr.c	2007-08-28 12:13:36.000000000 -0400
@@ -22,6 +22,7 @@
 #include <sys/socket.h>
 #include <sys/ioctl.h>
 #include <linux/x25.h>
+#include <linux/version.h>
 #include <ctype.h>
 #include <errno.h>
 #include <netdb.h>
@@ -77,7 +78,11 @@
   rt.sigdigits=sigdigits;
 
   /* x25_route_struct.address isn't type struct sockaddr_x25, Why? */
+#if LINUX_VERSION_CODE < KERNEL_VERSION(2, 6, 0)
   memcpy(&rt.address, &sx25.sx25_addr, sizeof(x25_address));
+#else
+  memcpy(&rt.address, &sx25.sx25_addr, sizeof(struct x25_address));
+#endif
 
   while (*args) {
 	if (!strcmp(*args,"device") || !strcmp(*args,"dev")) {
diff -Naur net-tools-1.60/mii-tool.c net-tools-1.60.patched/mii-tool.c
--- net-tools-1.60/mii-tool.c	2000-05-21 10:31:17.000000000 -0400
+++ net-tools-1.60.patched/mii-tool.c	2007-08-28 12:13:36.000000000 -0400
@@ -379,16 +379,16 @@
 /*--------------------------------------------------------------------*/
 
 const char *usage =
-"usage: %s [-VvRrwl] [-A media,... | -F media] [interface ...]
-       -V, --version               display version information
-       -v, --verbose               more verbose output
-       -R, --reset                 reset MII to poweron state
-       -r, --restart               restart autonegotiation
-       -w, --watch                 monitor for link status changes
-       -l, --log                   with -w, write events to syslog
-       -A, --advertise=media,...   advertise only specified media
-       -F, --force=media           force specified media technology
-media: 100baseT4, 100baseTx-FD, 100baseTx-HD, 10baseT-FD, 10baseT-HD,
+"usage: %s [-VvRrwl] [-A media,... | -F media] [interface ...]\n\
+       -V, --version               display version information\n\
+       -v, --verbose               more verbose output\n\
+       -R, --reset                 reset MII to poweron state\n\
+       -r, --restart               restart autonegotiation\n\
+       -w, --watch                 monitor for link status changes\n\
+       -l, --log                   with -w, write events to syslog\n\
+       -A, --advertise=media,...   advertise only specified media\n\
+       -F, --force=media           force specified media technology\n\
+media: 100baseT4, 100baseTx-FD, 100baseTx-HD, 10baseT-FD, 10baseT-HD,\n\
        (to advertise both HD and FD) 100baseTx, 10baseT\n";
 
 int main(int argc, char **argv)
EOF

  yes "" | make CC="$CC $BUILD" CXX="$CXX $BUILD" || return 1
  make BASEDIR=$TMPROOT update || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://www.tazenda.demon.co.uk/phil/net-tools/'
  VERSION_STRING='net-tools-%version%.tar.bz2'
  MIRRORS=(
    'http://www.tazenda.demon.co.uk/phil/net-tools/net-tools-%version%.tar.bz2'
  )
}
