#!/bin/bash

DISABLE_MULTILIB=1

VERSION="5.7.1"

DIR="net-snmp-${VERSION}"
TARBALL="net-snmp-${VERSION}.tar.gz"

SRC1=(
http://prdownloads.sourceforge.net/net-snmp/${TARBALL}
)

MD5SUMS=(
c95d08fd5d93df0c11a2e1bdf0e01e0b
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  yes "" | CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR --sysconfdir=/etc || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd $SRCDIR || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://sourceforge.net/projects/net-snmp/files/net-snmp/%version%/'
  VERSION_STRING='net-snmp-%version%.tar.gz'
  VERSION_FILTERS='or he ^\. load to pre our'
}
