#!/bin/bash

DISABLE_MULTILIB=1

VERSION="0.26.1"

DIR="vala-${VERSION}"
TARBALL="vala-${VERSION}.tar.xz"

SRC1=(
  $(gnome_mirrors vala)
)

MD5SUMS=(
723a03b822d4cc47abc4019685970a3e
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR --sysconfdir=/etc || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://ftp.gnome.org/pub/GNOME/sources/vala/%minor_version%/'
  VERSION_STRING='vala-%version%.tar.xz'
  ONLY_EVEN_MINORS=1
}
