#!/bin/bash

DISABLE_MULTILIB=1

VERSION="1.7"

DIR="xcb-proto-${VERSION}"
TARBALL="xcb-proto-${VERSION}.tar.bz2"

SRC1=(
http://xcb.freedesktop.org/dist/${TARBALL}
)

MD5SUMS=(
f5d73ec841ed055f5e80535819f18400
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR --sysconfdir=/etc --localstatedir=/var || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  mkdir -p $TMPROOT/usr/share/ || return 1
  mv $TMPROOT/usr/$LIBSDIR/pkgconfig $TMPROOT/usr/share/ || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://xcb.freedesktop.org/dist/'
  VERSION_STRING='xcb-proto-%version%.tar.bz2'
  MIRRORS=(
    'http://xcb.freedesktop.org/dist/xcb-proto-%version%.tar.bz2'
  )
}
