#!/bin/bash

DISABLE_MULTILIB=1

VERSION="0.0.26"

DIR="xmlto-${VERSION}"
TARBALL="xmlto-${VERSION}.tar.bz2"

SRC1=(
https://fedorahosted.org/releases/x/m/xmlto/${TARBALL}
)

MD5SUMS=(
c90a47c774e0963581c1ba57235f64f4
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
  --libdir=/usr/$LIBSDIR --sysconfdir=/etc || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS="https://fedorahosted.org/releases/x/m/xmlto/"
  VERSION_STRING="xmlto-%version%.tar.bz2"
}
