#!/bin/bash

DISABLE_MULTILIB=1

VERSION="1.5"

TARBALL="acpi-${VERSION}.tar.gz"
DIR=acpi-$VERSION

SRC1=(
http://prdownloads.sourceforge.net/acpiclient/${TARBALL}
)

MD5SUMS=(
ccfee3d53eba9c9947adafbcc1387611
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
  --libdir=/usr/$LIBSDIR --sysconfdir=/etc || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://sourceforge.net/projects/acpiclient/files/'
  VERSION_STRING='acpi-%version%.tar.gz'
}
