#!/bin/bash

DISABLE_MULTILIB=1

VERSION="9.10.1"

DIR="bind-${VERSION}"
TARBALL="bind-${VERSION}.tar.gz"

SRC1=(
http://ftp.isc.org/isc/bind9/$VERSION/${TARBALL}
)

MD5SUMS=(
82a69faf01b569568d9233f2666e744d
)

build(){
  unpack_tarball $TARBALL || return 1
  
  cd $SRCDIR/$DIR || return 1
  
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr --sysconfdir=/etc \
    --localstatedir=/var --libdir=/usr/$LIBSDIR --enable-threads \
    --with-libtool || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  
  groupadd -g 52 named
  useradd -c 'BIND User' -d /srv/named -g named -s /bin/false -u 52 named
  
  mkdir -vp $TMPROOT/srv/named/{dev,etc/namedb/{pz,slave},usr/lib/engines,var/run} || return 1
  mknod -m666 $TMPROOT/srv/named/dev/null c 1 3 || return 1
  mknod -m666 $TMPROOT/srv/named/dev/random c 1 8 || return 1
  cp /etc/localtime $TMPROOT/srv/named/etc/localtime || return 1
  touch $TMPROOT/srv/named//managed-keys.bind || return 1
  
  rm -f $TMPROOT/etc/rndc.conf
  
  mkdir -vp $TMPROOT/etc/rc.d || return 1
cat << "EOF" >$TMPROOT/etc/rc.d/rc.bind || return 1
#!/bin/bash

. /etc/rc.d/rc.conf
. /etc/rc.d/rc.functions

case "$1" in
  start)
    print_msg "Starting BIND..."
    if [ ! -e "/etc/rndc.conf" ]; then
      rndc-confgen -r /dev/urandom -b 512 > /etc/rndc.conf
      sed '/conf/d;/^#/!d;s:^# ::' /etc/rndc.conf > /srv/named/etc/named.conf
      cp /srv/named/etc/named.conf /etc
    fi
    loadproc named
  ;;
  stop)
    print_msg "Stopping BIND..."
    killproc named
  ;;
  restart)
    $0 stop
    sleep 1
    $0 start
  ;;
  reload)
    echo "Reloading BIND."
    rndc -c /etc/rndc.conf reload
  ;;
  *)
    echo "Usage: $0 {start|stop|restart|reload}"
    return 1
  ;;
esac
EOF
  chmod 744 $TMPROOT/etc/rc.d/rc.bind || return 1
  
cat > $TMPROOT/srv/named/etc/named.conf.new << EOF || return 1
options {
    directory "/etc/namedb";
    pid-file "/var/run/named.pid";
    statistics-file "/var/run/named.stats";

};
zone "." {
    type hint;
    file "root.hints";
};
zone "0.0.127.in-addr.arpa" {
    type master;
    file "pz/127.0.0";
};

// Bind 9 now logs by default through syslog (except debug).
// These are the default logging rules.

logging {
    category default { default_syslog; default_debug; };
    category unmatched { null; };

  channel default_syslog {
      syslog daemon;                      // send to syslog's daemon
                                          // facility
      severity info;                      // only send priority info
                                          // and higher
  };

  channel default_debug {
      file "named.run";                   // write to named.run in
                                          // the working directory
                                          // Note: stderr is used instead
                                          // of "named.run"
                                          // if the server is started
                                          // with the '-f' option.
      severity dynamic;                   // log at the server's
                                          // current debug level
  };

  channel default_stderr {
      stderr;                             // writes to stderr
      severity info;                      // only send priority info
                                          // and higher
  };

  channel null {
      null;                               // toss anything sent to
                                          // this channel
  };
};
EOF

cat > $TMPROOT/srv/named/etc/namedb/root.hints << "EOF" || return 1
.                       6D  IN      NS      A.ROOT-SERVERS.NET.
.                       6D  IN      NS      B.ROOT-SERVERS.NET.
.                       6D  IN      NS      C.ROOT-SERVERS.NET.
.                       6D  IN      NS      D.ROOT-SERVERS.NET.
.                       6D  IN      NS      E.ROOT-SERVERS.NET.
.                       6D  IN      NS      F.ROOT-SERVERS.NET.
.                       6D  IN      NS      G.ROOT-SERVERS.NET.
.                       6D  IN      NS      H.ROOT-SERVERS.NET.
.                       6D  IN      NS      I.ROOT-SERVERS.NET.
.                       6D  IN      NS      J.ROOT-SERVERS.NET.
.                       6D  IN      NS      K.ROOT-SERVERS.NET.
.                       6D  IN      NS      L.ROOT-SERVERS.NET.
.                       6D  IN      NS      M.ROOT-SERVERS.NET.
A.ROOT-SERVERS.NET.     6D  IN      A       198.41.0.4
B.ROOT-SERVERS.NET.     6D  IN      A       192.228.79.201
C.ROOT-SERVERS.NET.     6D  IN      A       192.33.4.12
D.ROOT-SERVERS.NET.     6D  IN      A       128.8.10.90
E.ROOT-SERVERS.NET.     6D  IN      A       192.203.230.10
F.ROOT-SERVERS.NET.     6D  IN      A       192.5.5.241
G.ROOT-SERVERS.NET.     6D  IN      A       192.112.36.4
H.ROOT-SERVERS.NET.     6D  IN      A       128.63.2.53
I.ROOT-SERVERS.NET.     6D  IN      A       192.36.148.17
J.ROOT-SERVERS.NET.     6D  IN      A       192.58.128.30
K.ROOT-SERVERS.NET.     6D  IN      A       193.0.14.129
L.ROOT-SERVERS.NET.     6D  IN      A       199.7.83.42
M.ROOT-SERVERS.NET.     6D  IN      A       202.12.27.33
EOF
  
#cat > $TMPROOT/srv/named/etc/namedb/pz/localhost << "EOF" || return 1
#$TTL    3D
#@       IN SOA  @ root (
#                            42          ; serial (d. adams)
#                            3H          ; refresh
#                            15M         ; retry
#                            1W          ; expiry
#                            1D)         ; minimum
#        IN NS           @
#        IN A            127.0.0.1
#EOF
#  
#cat > $TMPROOT/srv/named/etc/namedb/pz/127.0.0 << "EOF" || return 1
#$TTL    1D
#@       IN      SOA     localhost. root.localhost.  (
#                            1          ; Serial
#                            8H         ; Refresh
#                            2H         ; Retry
#                            4W         ; Expire
#                            1D)        ; Minimum
#        IN      NS      localhost.
#1       IN      PTR     localhost.
#EOF
  
  chmod -Rv ug+rw $TMPROOT/srv/named || return 1
  chown -Rv named:named $TMPROOT/srv/named || return 1
  
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://ftp.isc.org/isc/bind9/%version%'
  VERSION_STRING='bind-%version%.tar.gz'
  VERSION_FILTERS='[a-z] [A-Z]'
}
