#!/bin/bash

DISABLE_MULTILIB=1

VERSION="7.07.1"

DIR="espgs-${VERSION}"
TARBALL="espgs-${VERSION}-source.tar.bz2"

F1_DIR="ghostscript-fonts-std-8.11"
F1_TARBALL="ghostscript-fonts-std-8.11.tar.gz"

F2_DIR="ghostscript-fonts-other-5.10"
F2_TARBALL="ghostscript-fonts-other-5.10.tar.gz"

SRC1=(
http://prdownloads.sourceforge.net/espgs/${TARBALL}
)

SRC2=(
ftp://ftp.imagemagick.org/pub/ImageMagick/delegates/${F1_TARBALL}
)

SRC3=(
http://ftp.gnu.org/pub/gnu/ghostscript/${F2_TARBALL}
)

MD5SUMS=(
d30bf5c09f2c7caa8291f6305cf03044
6865682b095f8c4500c54b285ff05ef6
fcf3abf81a1b46da9a92942d288020f9
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
  --libdir=/usr/$LIBSDIR || return 1
  make || return 1
  make prefix=$TMPROOT/usr libdir=$TMPROOT/usr/$LIBSDIR \
    install_prefix=$TMPROOT bindir=$TMPROOT/usr/bin \
    datadir=$TMPROOT/usr/share mandir=$TMPROOT/usr/share/man install || return 1
  tar xvfz $DOWNLOADDIR/$F1_TARBALL -C \
    $TMPROOT/usr/share/ghostscript/ || return 1
  tar xvfz $DOWNLOADDIR/$F2_TARBALL -C \
    $TMPROOT/usr/share/ghostscript/fonts/ || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://sourceforge.net/project/showfiles.php?group_id=18073&package_id=19793'
  VERSION_STRING='espgs-%version%-source.tar.bz2'
  VERSION_FILTERS='[a-z] [A-Z]'
}
