#!/bin/bash

DONT_REMOVE=1
DISABLE_MULTILIB=1

VERSION="5.11"

DIR="file-${VERSION}"
TARBALL="file-${VERSION}.tar.gz"

SRC1=(
ftp://ftp.astron.com/pub/file/${TARBALL}
)

MD5SUMS=(
16a407bd66d6c7a832f3a5c0d609c27b
)

Cross_Tools_Build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  ./configure --prefix=$CTCDIR || return 1
  make || return 1
  make install || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

Tools_Build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --build=$BUILDHOST \
    --host=$BUILDTARGET --prefix=$TCDIR \
    --libdir=$TCDIR/$LIBSDIR || return 1
  make || return 1
  make install || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='ftp://ftp.astron.com/pub/file/'
  VERSION_STRING='file-%version%.tar.gz'
  MIRRORS=(
    'ftp://ftp.astron.com/pub/file/file-%version%.tar.gz'
  )
}
