#!/bin/bash

DISABLE_MULTILIB=1

VERSION="1.0.1"

DIR="font-adobe-75dpi-${VERSION}"
TARBALL="font-adobe-75dpi-${VERSION}.tar.bz2"

SRC1=(
http://xorg.freedesktop.org/releases/individual/font/${TARBALL}
)

MD5SUMS=(
a47681c97bd012196691c95e34d400f1
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR --sysconfdir=/etc --localstatedir=/var || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

post_install(){
  cd /usr/share/fonts/X11/75dpi || return 1
  mkfontdir || return 1
  mkfontscale || return 1
  fc-cache || return 1
}

post_upgrade(){
  post_install || return 1
}

post_remove(){
  [ -d "/usr/lib/X11/fonts/75dpi" ] && {
    cd /usr/lib/X11/fonts/75dpi || return 1
    mkfontdir || return 1
    mkfontscale || return 1
  }
  fc-cache || return 1
  return 0
}

version_check_info(){
  ADDRESS='http://xorg.freedesktop.org/releases/individual/font/'
  VERSION_STRING='font-adobe-75dpi-%version%.tar.bz2'
  MIRRORS=(
    'http://xorg.freedesktop.org/releases/individual/font/font-adobe-75dpi-%version%.tar.bz2'
  )
}
