#!/bin/bash

DISABLE_MULTILIB=1

VERSION="0.1.6"

DIR="gegl-${VERSION}"
TARBALL="gegl-${VERSION}.tar.bz2"

SRC1=(
ftp://ftp.gimp.org/pub/gegl/$(cut -f-2 -d'.' <<< $VERSION)/${TARBALL}
)

MD5SUMS=(
af5e5a7d3c7ddfaa2b3414de2a7e9113
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='ftp://ftp.gimp.org/pub/gegl/%minor_version%/'
  VERSION_STRING='gegl-%version%.tar.bz2'
}
