#!/bin/bash

DISABLE_MULTILIB=1

VERSION="0.18"

DIR="gettext-${VERSION}"
TARBALL="gettext-${VERSION}.tar.gz"

SRC1=(
http://ftp.gnu.org/gnu/gettext/${TARBALL}
)

MD5SUMS=(
d52a3e061032a1ed13856d42fc86f0fd
)

Tools_Build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  echo "gl_cv_func_wcwidth_works=yes" > config.cache || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --build=$BUILDHOST \
    --host=$BUILDTARGET --prefix=$TCDIR \
    --libdir=$TCDIR/$LIBSDIR --cache-file=config.cache || return 1
  make || return 1
  make install || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --build=$BUILDHOST \
    --host=$BUILDTARGET --prefix=/usr --libdir=/usr/$LIBSDIR || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://ftp.gnu.org/gnu/gettext/'
  VERSION_STRING='gettext-%version%.tar.gz'
}
