#!/bin/bash

DISABLE_MULTILIB=1

VERSION="2.30.1"

DIR="gnome-terminal-${VERSION}"
TARBALL="gnome-terminal-${VERSION}.tar.bz2"

SRC1=(
  $(gnome_mirrors gnome-terminal)
)

MD5SUMS=(
fed3235a053ce34a16218bfe1c2202ca
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR --libexecdir=/usr/sbin --sysconfdir=/etc/gnome \
    --localstatedir=/var/lib || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  rm -rf $TMPROOT/var/lib/scrollkeeper
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://ftp.gnome.org/pub/GNOME/sources/gnome-terminal/%minor_version%/'
  VERSION_STRING='gnome-terminal-%version%.tar.bz2'
  ONLY_EVEN_MINORS=1
}
