#!/bin/bash

DISABLE_MULTILIB=1

VERSION="0.10.29"

DIR="gstreamer-${VERSION}"
TARBALL="gstreamer-${VERSION}.tar.bz2"

SRC1=(
http://gstreamer.freedesktop.org/src/gstreamer/${TARBALL}
)

MD5SUMS=(
c92d6bce4fc65fa9d5a3ad35cdd1a466
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR --sysconfdir=/etc \
    --localstatedir=/var || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  rm -rf $TMPROOT/var/lib/scrollkeeper
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://gstreamer.freedesktop.org/src/gstreamer/'
  VERSION_STRING='gstreamer-%version%.tar.bz2'
}
