#!/bin/bash

DISABLE_MULTILIB=1

VERSION="1.4.5"

DIR="imlib2-${VERSION}"
TARBALL="imlib2-${VERSION}.tar.gz"

SRC1=(
http://prdownloads.sourceforge.net/enlightenment/${TARBALL}
)

MD5SUMS=(
8406786d3852b1b1322c2e4bee3c9e5c
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR --sysconfdir=/etc || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS="http://sourceforge.net/projects/enlightenment/files/imlib2-src/%version%/"
  VERSION_STRING="imlib2-%version%.tar.gz"
  VERSION_FILTERS="or he ^\. to load"
}
