#!/bin/bash

DISABLE_MULTILIB=1

VERSION="1.4.8"

DIR="iptables-${VERSION}"
TARBALL="iptables-${VERSION}.tar.bz2"

SRC1=(
http://www.netfilter.org/projects/iptables/files/${TARBALL}
)

MD5SUMS=(
697ed89f37af4473a5f6349ba2700f2d
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR --libexecdir=/usr/$LIBSDIR || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://www.netfilter.org/projects/iptables/downloads.html'
  VERSION_STRING='iptables-%version%.tar.bz2'
  VERSION_FILTERS='[a-z] [A-Z]'
}
