#!/bin/bash

DISABLE_MULTILIB=1

VERSION="6u26"

TARBALL32="jdk-${VERSION}-dlj-linux-i586.bin"
TARBALL64="jdk-${VERSION}-dlj-linux-amd64.bin"

SRC1=(
http://dlc.sun.com/dlj/binaries/$TARBALL32
)

SRC2=(
http://dlc.sun.com/dlj/binaries/$TARBALL64
)

MD5SUMS=(
d54e58b69e4db80f267435be679a66b9
43f4e9699afce82d3ebae841c59d02fb
)

build(){
  local DIR BIN JARC
  case $($CC -dumpmachine | cut -f1 -d'-') in
    i*86)
      BIN=$TARBALL32
      JARC=i386
    ;;
    x86_64)
      BIN=$TARBALL64
      JARC=amd64
    ;;
    *)
      echo "Wrong arch!" >/dev/stderr
      return 1
  esac

  mkdir -p $TMPROOT/usr/$LIBSDIR $SRCDIR/jdk || return 1
  cd $SRCDIR/jdk || return 1
  sh $DOWNLOADDIR/$BIN --accept-license --unpack || return 1
  cd * || return 1
  DIR=$PWD
  cd ../ || return 1
  mv $DIR $TMPROOT/usr/$LIBSDIR/jdk || return 1
  mv $TMPROOT/usr/$LIBSDIR/jdk/include $TMPROOT/usr/ || return 1
  mkdir -p $TMPROOT/etc/{ld.so.conf,profile}.d

cat << EOF > $TMPROOT/etc/ld.so.conf.d/jdk.conf
/usr/$LIBSDIR/jdk/jre/lib/$JARC
/usr/$LIBSDIR/jdk/jre/lib/$JARC/client
/usr/$LIBSDIR/jdk/jre/lib/$JARC/jli
/usr/$LIBSDIR/jdk/jre/lib/$JARC/motif21
/usr/$LIBSDIR/jdk/jre/lib/$JARC/native_threads
/usr/$LIBSDIR/jdk/jre/lib/$JARC/server
/usr/$LIBSDIR/jdk/jre/lib/$JARC/xawt
EOF

cat << EOF > $TMPROOT/etc/profile.d/jdk.sh
PATH=\$PATH:/usr/$LIBSDIR/jdk/bin:/usr/$LIBSDIR/jdk/jre/bin

if [ -z "\$MOZ_PLUGIN_PATH" ]; then
  MOZ_PLUGIN_PATH=/usr/$LIBSDIR/jdk/jre/lib/$JARC
else
  MOZ_PLUGIN_PATH=\$MOZ_PLUGIN_PATH:/usr/$LIBSDIR/jdk/jre/lib/$JARC
fi

if [ -z "\$MANPATH" ]; then
  MANPATH=/usr/$LIBSDIR/jdk/man
else
  MANPATH=\$MANPATH:/usr/$LIBSDIR/jdk/man
fi

export PATH MOZ_PLUGIN_PATH MANPATH
EOF
  chmod 755 $TMPROOT/etc/profile.d/jdk.sh || return 1
  source $TMPROOT/etc/profile.d/jdk.sh || return 1
  cd $SRCDIR || return 1
  rm -rf jdk || return 1
}

version_check_info(){
  ADDRESS='https://jdk-distros.dev.java.net/developer.html'
  VERSION_STRING='jdk-%version%-dlj-linux-i586.bin'
}
