#!/bin/bash

DISABLE_MULTILIB=1

VERSION="2.32.1"

DIR="libbonobo-${VERSION}"
TARBALL="libbonobo-${VERSION}.tar.bz2"

SRC1=(
  $(gnome_mirrors libbonobo)
)

MD5SUMS=(
27fa902d4fdf6762ee010e7053aaf77b
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR --libexecdir=/usr/$LIBSDIR/bonobo \
    --sysconfdir=/etc/gnome --localstatedir=/var/lib || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://ftp.gnome.org/pub/GNOME/sources/libbonobo/%minor_version%/'
  VERSION_STRING='libbonobo-%version%.tar.bz2'
}
