#!/bin/bash

VERSION="1.3.2"

DIR="libevdev-${VERSION}"
TARBALL="libevdev-${VERSION}.tar.xz"

SRC1=(
http://www.freedesktop.org/software/libevdev/${TARBALL}
)

MD5SUMS=(
80c7b490bf3e7ec8e8b60d4fb307b664
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR --sysconfdir=/etc --localstatedir=/var \
    --disable-static || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://www.freedesktop.org/software/libevdev/'
  VERSION_STRING='libevdev-%version%.tar.xz'
}
