#!/bin/bash

VERSION="1.0.8"

DIR="libusb-${VERSION}"
TARBALL="libusb-${VERSION}.tar.bz2"

SRC1=(
http://prdownloads.sourceforge.net/libusb/${TARBALL}
)

MD5SUMS=(
37d34e6eaa69a4b645a19ff4ca63ceef
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --build=$BUILDHOST \
    --host=$BUILDTARGET --prefix=/usr --libdir=/usr/$LIBSDIR || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://sourceforge.net/projects/libusb/files/libusb-1.0/libusb-%version%/'
  VERSION_STRING='libusb-%version%.tar.bz2'
  VERSION_FILTERS='enter he ^\. usb or'
}
