#!/bin/bash

VERSION="7.10.3"

DIR="Mesa-${VERSION}"

SRC1=(
ftp://ftp.freedesktop.org/pub/mesa/$(cut -f1 -d'-' <<< $VERSION)/MesaLib-${VERSION}.tar.bz2
)

SRC2=(
ftp://ftp.freedesktop.org/pub/mesa/$(cut -f1 -d'-' <<< $VERSION)/MesaGLUT-${VERSION}.tar.bz2
)

MD5SUMS=(
8c38fe8266be8e1ed1d84076ba5a703b
1496415b89da9549f0f3b34d9622e2e2
)

build(){
  local CONF
  unset CFLAGS CXXFLAGS
  
  CONF=
  [ "$SYSTYPE" == "MULTILIB" ] && \
    [ "$BUILD" == "$BUILD32" ] && CONF="--enable-32-bit"
  
  mkdir -p $SRCDIR || return 1
  for x in MesaLib-${VERSION}.tar.bz2 \
           MesaGLUT-${VERSION}.tar.bz2; do
    echo -n "Unpacking ${x}..."
    tar xfj $DOWNLOADDIR/$x -C $SRCDIR || return 1
    echo " done"
  done
  
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure $CONF --prefix=/usr \
    --libdir=/usr/$LIBSDIR || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1

  if [ "$SYSTYPE" == "MULTILIB" ] && [ "$BUILD" == "$BUILD32" ]; then
    rm -rf $TMPROOT/$LIBSDIR/dri || return 1
  fi
  
  cd $SRCDIR || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='ftp://ftp.freedesktop.org/pub/mesa/%version%/'
  VERSION_STRING='MesaLib-%version%.tar.bz2'
  VERSION_FILTERS='beta current demos tmp older'
}
