#!/bin/bash

VERSION="8.0.1"

DIR="Mesa-${VERSION}"
TARBALL="MesaLib-${VERSION}.tar.bz2"

SRC1=(
ftp://ftp.freedesktop.org/pub/mesa/$(cut -f1 -d'-' <<< $VERSION)/$TARBALL
)

MD5SUMS=(
24eeebf66971809d8f40775a379b36c9
)

build(){
  local CONF
  unset CFLAGS CXXFLAGS
  
  CONF=
  [ "$SYSTYPE" == "MULTILIB" ] && \
    [ "$BUILD" == "$BUILD32" ] && CONF="--enable-32-bit"
  
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure $CONF --prefix=/usr \
    --libdir=/usr/$LIBSDIR --disable-gallium-llvm \
    --with-gallium-drivers="swrast" || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1

  if [ "$SYSTYPE" == "MULTILIB" ] && [ "$BUILD" == "$BUILD32" ]; then
    rm -rf $TMPROOT/$LIBSDIR/dri || return 1
  fi
  
  cd $SRCDIR || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='ftp://ftp.freedesktop.org/pub/mesa/%version%/'
  VERSION_STRING='MesaLib-%version%.tar.bz2'
  VERSION_FILTERS='beta current demos tmp older'
}
