#!/bin/bash

DONT_REMOVE=1
DISABLE_MULTILIB=1

VERSION="3.16"

DIR="module-init-tools-${VERSION}"
TARBALL="module-init-tools-${VERSION}.tar.bz2"

SRC1=(
http://www.kernel.org/pub/linux/utils/kernel/module-init-tools/${TARBALL}
)

MD5SUMS=(
bc44832c6e41707b8447e2847d2019f5
)

MyBuild(){
  
  MYDEST=$1
  
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  sed -i 's%$(PROGRAMS) $(MANS)%$(PROGRAMS)%' Makefile.in || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --build=$BUILDHOST \
    --host=$BUILDTARGET --prefix=/ --enable-zlib \
    --with-moddir=/$LIBSDIR/modules || return 1
  make
  mkdir -vp $MYDEST/sbin || return 1
  install -v -m 0755 build/{depmod,insmod,insmod.static,lsmod,modindex,modinfo,modprobe,rmmod} \
    $MYDEST/sbin || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

Tools_Build(){
  MyBuild $ROOT || return 1
}

build(){
  MyBuild $TMPROOT || return 1
}

version_check_info(){
  ADDRESS='http://www.kernel.org/pub/linux/utils/kernel/module-init-tools/'
  VERSION_STRING='module-init-tools-%version%.tar.bz2'
  VERSION_FILTERS='[a-z] [A-Z]'
}
