#!/bin/bash

DISABLE_MULTILIB=1

VERSION="0.9.5"

DIR="pcmanfm-${VERSION}"
TARBALL="pcmanfm-${VERSION}.tar.gz"

SRC1=(
http://prdownloads.sourceforge.net/pcmanfm/${TARBALL}
)

MD5SUMS=(
9b7ca698fa4464ac4306af039537ab12
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR --sysconfdir=/etc || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS="http://sourceforge.net/projects/pcmanfm/files/"
  VERSION_STRING="pcmanfm-%version%.tar.gz"
}
