#!/bin/bash

VERSION="0.99"

DIR="XML-SAX-${VERSION}"
TARBALL="XML-SAX-${VERSION}.tar.gz"

SRC1=(
http://search.cpan.org/CPAN/authors/id/G/GR/GRANTM/${TARBALL}
)

MD5SUMS=(
290f5375ae87fdebfdb5bc3854019f24
)

build(){
  local PV
  PV=$(cat /var/lib/packages/current/perl/version)
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  perl Makefile.PL || return 1
  make || return 1
  make test || return 1
  PERL5LIB=$TMPROOT/usr/$LIBSDIR/perl5/site_perl/$PV make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://search.cpan.org/~grantm/'
  VERSION_STRING='XML-SAX-%version%.tar.gz'
  VERSION_FILTERS='RTF Base'
}
