#!/bin/bash

VERSION="1.11"

DIR="XML-NamespaceSupport-${VERSION}"
TARBALL="XML-NamespaceSupport-${VERSION}.tar.gz"

SRC1=(
http://search.cpan.org/CPAN/authors/id/P/PE/PERIGRIN/${TARBALL}
)

MD5SUMS=(
222cca76161cd956d724286d36b607da
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  perl Makefile.PL || return 1
  make || return 1
  make test || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://search.cpan.org/~perigrin/'
  VERSION_STRING='XML-NamespaceSupport-%version%.tar.gz'
}
