#!/bin/bash

DISABLE_MULTILIB=1

VERSION="0.26"

DIR="pkg-config-${VERSION}"
TARBALL="pkg-config-${VERSION}.tar.gz"

SRC1=(
  http://pkgconfig.freedesktop.org/releases/$TARBALL
)

MD5SUMS=(
47525c26a9ba7ba14bf85e01509a7234
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" GLIB_LIBS="-L/usr/$LIBSDIR -lglib-2.0" \
    GLIB_CFLAGS="-I/usr/include/glib-2.0 -I/usr/$LIBSDIR/glib-2.0/include" \
    ./configure --prefix=/usr --libdir=/usr/$LIBSDIR \
    --with-pc-path=/usr/share/pkgconfig || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  mkdir -p $TMPROOT/etc/profile.d
  case $SYSTYPE in
    MULTILIB)
cat << "EOF" > $TMPROOT/etc/profile.d/pkg-config.sh || return 1
export PKG_CONFIG_PATH32=$PKG_CONFIG_PATH32:/usr/${LIBSDIR32}/pkgconfig:/usr/share/pkgconfig
export PKG_CONFIG_PATH64=$PKG_CONFIG_PATH64:/usr/${LIBSDIR64}/pkgconfig:/usr/share/pkgconfig
export PKG_CONFIG_PATH=$PKG_CONFIG_PATH64
EOF
    ;;
    *)
cat << "EOF" > $TMPROOT/etc/profile.d/pkg-config.sh || return 1
export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/$LIBSDIR/pkgconfig:/usr/share/pkgconfig
EOF
    ;;
  esac
  chmod 755 $TMPROOT/etc/profile.d/pkg-config.sh || return 1
  source $TMPROOT/etc/profile.d/pkg-config.sh || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://pkgconfig.freedesktop.org/releases/'
  VERSION_STRING='pkg-config-%version%.tar.gz'
}
