#!/bin/bash

DISABLE_MULTILIB=1

VERSION="1.16"

DIR="popt-${VERSION}"
TARBALL="popt-${VERSION}.tar.gz"

SRC1=(
http://rpm5.org/files/popt/${TARBALL}
)

MD5SUMS=(
3743beefa3dd6247a73f8f7a32c14c33
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://rpm5.org/files/popt/'
  VERSION_STRING='popt-%version%.tar.gz'
}
