#!/bin/bash

DISABLE_MULTILIB=1

VERSION="1.0.22"

DIR="sane-backends-${VERSION}"
TARBALL="sane-backends-${VERSION}.tar.gz"

SRC1=(
ftp://ftp2.sane-project.org/pub/sane/sane-backends-${VERSION}/${TARBALL}
)

MD5SUMS=(
fadf56a60f4776bfb24491f66b617cf5
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --sysconfdir=/etc --libdir=/usr/$LIBSDIR || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  set_multiarch $TMPROOT/usr/bin/sane-config || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='ftp://ftp2.sane-project.org/pub/sane/sane-backends-%version%/'
  VERSION_STRING='sane-backends-%version%.tar.gz'
}
