#!/bin/bash

DISABLE_MULTILIB=1

VERSION="2.0.3"

DIR="SDL2-${VERSION}"
TARBALL="SDL2-${VERSION}.tar.gz"

SRC1=(
http://ftp.br.freebsd.org/distfiles/${TARBALL}
http://www.libsdl.org/release/${TARBALL}
)

MD5SUMS=(
fe6c61d2e9df9ef570e7e80c6e822537
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  set_multiarch $TMPROOT/usr/bin/sdl-config || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://www.libsdl.org/release/'
  VERSION_STRING='SDL2-%version%.tar.gz'
  VERSION_FILTERS='mi de'
}
