#!/bin/bash

VERSION="4.6"

ENABLE_MULTILIB=1

DIR="strace-${VERSION}"
TARBALL="strace-${VERSION}.tar.xz"

SRC1=(
http://prdownloads.sourceforge.net/strace/${TARBALL}
)

MD5SUMS=(
e537b2b1afeec70c0e6e27a0d0fd671e
)

build(){
  mkdir -p $SRCDIR || return 1
  cd $SRCDIR || return 1
  rm -rf $DIR || return 1
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --build=$BUILDHOST \
    --host=$BUILDTARGET --prefix=/usr || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  set_multiarch $TMPROOT/usr/bin/strace || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://sourceforge.net/project/showfiles.php?group_id=2861&package_id=2819'
  VERSION_STRING='strace-%version%.tar.xz'
}
