#!/bin/bash

DISABLE_MULTILIB=1

VERSION="2.99.917"

DIR="xf86-video-intel-${VERSION}"
TARBALL="xf86-video-intel-${VERSION}.tar.bz2"

SRC1=(
http://xorg.freedesktop.org/releases/individual/driver/${TARBALL}
)

MD5SUMS=(
fa196a66e52c0c624fe5d350af7a5e7b
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR --sysconfdir=/etc --localstatedir=/var \
    --with-xorg-module-dir=/usr/$LIBSDIR/X11/modules || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://xorg.freedesktop.org/releases/individual/driver/'
  #VERSION_FILTERS='.90 .99'
  VERSION_STRING='xf86-video-intel-%version%.tar.bz2'
}
