#!/bin/bash

DISABLE_MULTILIB=1

VERSION="1.0.3"

DIR="xproxymanagementprotocol-${VERSION}"
TARBALL="xproxymanagementprotocol-${VERSION}.tar.bz2"

SRC1=(
http://xorg.freedesktop.org/releases/individual/proto/${TARBALL}
)

MD5SUMS=(
9de22ca1522008c28fb03dfc41ba2d30
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR --sysconfdir=/etc --localstatedir=/var || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://xorg.freedesktop.org/releases/individual/proto/'
  VERSION_STRING='xproxymanagementprotocol-%version%.tar.bz2'
  MIRRORS=(
    'http://xorg.freedesktop.org/releases/individual/proto/xproxymanagementprotocol-%version%.tar.bz2'
  )
}
