#!/bin/bash

[ "$(id -u)" != "0" ] && {
  echo "Run me as root please." >/dev/stderr
  exit 1
}

cd "$(dirname $0)" || exit 1
RBSDIR="$PWD"

source "$RBSDIR/shared" || exit 1
SRCDIR="$WORKDIR/setup_source"

[ "$Ralphs_Build_System" != "1" ] && {
  echo "This script can't run on a system that wasn't built by me." >/dev/stderr
  exit 1
}

profiles_exist $* || exit 1

download_sources $* || exit 1

for x in $*; do
  echo "Setting up ${x}'s source..."
  exec_profile $x source_setup || exit 1
done
