#!/bin/bash

DISABLE_MULTILIB=1

VERSION="2.0.0.22"
SYS_VERSION="2.0.0.22-1"

DIR="thunderbird-${VERSION}"
TARBALL="thunderbird-${VERSION}-source.tar.bz2"

DEPENDS=(
  desktop-file-utils
  libidl
)

SRC1=(
http://ftp.mozilla.org/pub/mozilla.org/thunderbird/releases/${VERSION}/source/${TARBALL}
)

MD5SUMS=(
080c26dcb0ed563519a6061139a0bf92
)

build(){
  local OSTEST
  unset CFLAGS CXXFLAGS
  OSTEST=$(gcc -dumpmachine | cut -f1 -d'-')
  
  mkdir -p $SRCDIR/$DIR || return 1
  echo -n "Unpacking ${TARBALL}..."
  tar xfj $DOWNLOADDIR/$TARBALL -C $SRCDIR/$DIR/ || return 1
  echo " Done."
  cd $SRCDIR/$DIR/mozilla || return 1
  
  do_patch thunderbird-${VERSION}-gcc-4.4.0-1.patch || return 1
  
cat > .mozconfig << EOF
. \$topsrcdir/mail/config/mozconfig
mk_add_options MOZ_OBJDIR=@TOPSRCDIR@/obj-@CONFIG_GUESS@

ac_cv_visibility_pragma=no

ac_add_options --prefix=/usr

ac_add_options --with-system-nss
ac_add_options --with-system-nspr

ac_add_options --with-system-zlib
ac_add_options --with-system-png
ac_add_options --with-system-jpeg
ac_add_options --enable-system-cairo

ac_add_options --enable-canvas
ac_add_options --enable-svg

ac_add_options --enable-strip
ac_add_options --disable-tests 
ac_add_options --disable-accessibility
ac_add_options --disable-installer 
ac_add_options --enable-official-branding
ac_add_options --enable-xinerama

ac_add_options --enable-single-profile
ac_add_options --disable-profilesharing

ac_add_options --disable-gnomevfs
ac_add_options --disable-gnomeui

ac_add_options --with-default-mozilla-five-home=/usr/${LIBSDIR}/thunderbird
export CC="gcc ${BUILD} -ffloat-store -fno-strict-aliasing"
export CXX="g++ ${BUILD} -ffloat-store -fno-strict-aliasing"
ac_add_options --libdir=/usr/${LIBSDIR}
EOF

  if [ "$SYSTYPE" == "MULTILIB" ] && [ "$BUILD" == "$BUILD32" ]; then
cat >> .mozconfig << EOF
ac_add_options --host=$BUILDTARGET
ac_add_options --build=$BUILDTARGET
mk_add_options CONFIG_GUESS=$BUILDTARGET
EOF
    OSTEST=$(echo $BUILDTARGET | cut -f1 -d'-')
  fi
  
  sed -i "s:@MOZ_GTK2_LIBS@:& -L/usr/${LIBSDIR} -lX11 -lXrender:g" \
    config/autoconf.mk.in || return 1
  make -f client.mk OS_TEST=$OSTEST build || return 1
  make -f client.mk OS_TEST=$OSTEST install DESTDIR=$TMPROOT || return 1
  
  mv $TMPROOT/usr/$LIBSDIR/thunderbird-${VERSION} \
    $TMPROOT/usr/$LIBSDIR/thunderbird || exit 1
  mv $TMPROOT/usr/bin/thunderbird \
    $TMPROOT/usr/$LIBSDIR/thunderbird/ || exit 1
  mv $TMPROOT/usr/include/thunderbird-$VERSION \
    $TMPROOT/usr/include/thunderbird || return 1
  rm -rf $TMPROOT/usr/share/aclocal \
    $TMPROOT/usr/bin/thunderbird-config \
    $TMPROOT/usr/share/idl || return 1
  sed -i "s%thunderbird-${VERSION}%thunderbird%g" \
    $TMPROOT/usr/$LIBSDIR/pkgconfig/*.pc \
    $TMPROOT/usr/$LIBSDIR/thunderbird/thunderbird || return 1
  mkdir -p $TMPROOT/usr/$LIBSDIR/thunderbird/chrome/icons || return 1
  ln -sfn ../../icons \
    $TMPROOT/usr/$LIBSDIR/thunderbird/chrome/icons/default || return 1
  
cat << "EOF" > $TMPROOT/usr/$LIBSDIR/thunderbird/defaults/profile/prefs.js
# Mozilla User Preferences
 /* Do not edit this file.
 *
 * If you make changes to this file while the browser is running,
 * the changes will be overwritten when the browser exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("font.default", "sans-serif");
user_pref("font.minimum-size.x-western", 11);
user_pref("font.name.monospace.x-western", "monospace");
user_pref("font.name.sans-serif.x-western", "sans-serif");
user_pref("font.name.serif.x-western", "sans-serif");
user_pref("font.size.variable.x-western", 12);
user_pref("network.protocol-handler.app.http", "firefox");
user_pref("network.protocol-handler.app.https", "firefox");
EOF
  
cat << EOF > $TMPROOT/usr/bin/thunderbird || return 1
#!/bin/bash

THUNDERBIRD=/usr/$LIBSDIR/thunderbird/thunderbird
if [ -z "\$(pidof thunderbird-bin)" ]; then
  \$THUNDERBIRD \$*
else
  if [ -z "\$1" ]; then
    \$THUNDERBIRD -remote "xfeDoCommand(openInbox)"
  else
    \$THUNDERBIRD -remote "openURL(\$1)"
  fi
fi
EOF
  chmod 755 $TMPROOT/usr/bin/thunderbird || return 1
  
  mkdir -p $TMPROOT/usr/share/applications || return 1
cat << EOF > $TMPROOT/usr/share/applications/thunderbird.desktop || return 1
[Desktop Entry]
Name=Mail
Comment=Mail
Exec=/usr/bin/thunderbird
StartupNotify=false
Icon=/usr/$LIBSDIR/thunderbird/icons/default.xpm
Terminal=0
Type=Application
Categories=Application;Network;
EOF
  cd $SRCDIR || return 1
  rm -rf $DIR || return 1
}

post_install(){
  update-desktop-database -q || return 1
}

post_upgrade(){
  post_install || return 1
}

version_check_info(){
  ADDRESS='ftp://ftp.mozilla.org/pub/mozilla.org/thunderbird/releases/%version%/source/'
  VERSION_STRING='thunderbird-%version%-source.tar.bz2'
  VERSION_FILTERS='[a-z] [A-Z]'
  MIRRORS=(
    'ftp://ftp.mozilla.org/pub/mozilla.org/thunderbird/releases/%version%/source/thunderbird-%version%-source.tar.bz2'
    'http://ftp.mozilla.org/pub/mozilla.org/thunderbird/releases/%version%/source/thunderbird-%version%-source.tar.bz2'
  )
}
