#!/bin/bash

VERSION="1.0.24.1"

DIR="alsa-lib-${VERSION}"
TARBALL="alsa-lib-${VERSION}.tar.bz2"

SRC1=(
ftp://ftp.alsa-project.org/pub/lib/${TARBALL}
)

MD5SUMS=(
7cc05f25e1d5b65da8fb3fdcd540f226
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR --sysconfdir=/etc || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='ftp://ftp.alsa-project.org/pub/lib/'
  VERSION_STRING='alsa-lib-%version%.tar.bz2'
  VERSION_FILTERS='[a-z] [A-Z]'
}
