#!/bin/bash

DISABLE_MULTILIB=1

VERSION="2.18.0"

DIR="at-spi2-atk-${VERSION}"
TARBALL="at-spi2-atk-${VERSION}.tar.xz"

SRC1=(
  $(gnome_mirrors at-spi2-atk)
)

MD5SUMS=(
df1bbe9f4cd55342e18097a0e4b6d380
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR --sysconfdir=/etc || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

post_install(){
  glib-compile-schemas /usr/share/glib-2.0/schemas || return 1
}

post_upgrade(){
  post_install
}

version_check_info(){
  ADDRESS='http://ftp.gnome.org/pub/GNOME/sources/at-spi2-atk/%minor_version%/'
  VERSION_STRING='at-spi2-atk-%version%.tar.xz'
  ONLY_EVEN_MINORS=1
}
