#!/bin/bash

DISABLE_MULTILIB=1

VERSION="2.26.2"

DIR="at-spi2-core-${VERSION}"
TARBALL="at-spi2-core-${VERSION}.tar.xz"

SRC1=(
  $(gnome_mirrors at-spi2-core)
)

MD5SUMS=(
4a042e4c801fdb793788b749eab21485
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR --sysconfdir=/etc || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://ftp.gnome.org/pub/GNOME/sources/at-spi2-core/%minor_version%/'
  VERSION_STRING='at-spi2-core-%version%.tar.xz'
  ONLY_EVEN_MINORS=1
}
