#!/bin/bash

DISABLE_MULTILIB=1

VERSION="2.26.1"

DIR="atk-${VERSION}"
TARBALL="atk-${VERSION}.tar.xz"

SRC1=(
  $(gnome_mirrors atk)
)

MD5SUMS=(
7cddcc313b9a3efd19b2ddf079ba68f5
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://ftp.gnome.org/pub/GNOME/sources/atk/%minor_version%/'
  VERSION_STRING='atk-%version%.tar.xz'
  ONLY_EVEN_MINORS=1
}
