#!/bin/bash

DISABLE_MULTILIB=1

VERSION="1.32.0"

DIR="atk-${VERSION}"
TARBALL="atk-${VERSION}.tar.bz2"

SRC1=(
  $(gnome_mirrors atk)
)

MD5SUMS=(
b9a19a3e426cd9ca930f0108c4ee343f
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://ftp.gnome.org/pub/GNOME/sources/atk/%minor_version%/'
  VERSION_STRING='atk-%version%.tar.bz2'
  ONLY_EVEN_MINORS=1
  MIRRORS=(
    "http://ftp.gnome.org/pub/GNOME/sources/atk/%minor_version%/atk-%version%.tar.bz2"
  )
}
