#!/bin/bash

DONT_REMOVE=1
DISABLE_MULTILIB=1

VERSION="1.15.1"

DIR="automake-${VERSION}"
TARBALL="automake-${VERSION}.tar.xz"

SRC1=(
http://ftp.gnu.org/gnu/automake/${TARBALL}
)

MD5SUMS=(
24cd3501b6ad8cd4d7e2546f07e8b4d4
)

build(){
  unpack_tarball $TARBALL
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --build=$BUILDHOST \
    --host=$BUILDTARGET --prefix=/usr || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://ftp.gnu.org/gnu/automake/'
  VERSION_STRING='automake-%version%.tar.xz'
}
