#!/bin/bash

DISABLE_MULTILIB=1

VERSION="0.1.10"

DIR="babl-${VERSION}"
TARBALL="babl-${VERSION}.tar.bz2"

SRC1=(
http://download.gimp.org/pub/babl/$(cut -f-2 -d'.' <<< $VERSION)/${TARBALL}
)

MD5SUMS=(
9e1542ab5c0b12ea3af076a9a2f02d79
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  PKG_CONFIG_PATH=$PWD:$PKG_CONFIG_PATH CC="$CC $BUILD" CXX="$CXX $BUILD" \
    ./configure --prefix=/usr --libdir=/usr/$LIBSDIR || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://download.gimp.org/pub/babl/%minor_version%/'
  VERSION_STRING='babl-%version%.tar.bz2'
}
