#!/bin/bash

DISABLE_MULTILIB=1

VERSION="0.1.50"

DIR="babl-${VERSION}"
TARBALL="babl-${VERSION}.tar.bz2"

SRC1=(
http://download.gimp.org/pub/babl/$(cut -f-2 -d'.' <<< $VERSION)/${TARBALL}
)

MD5SUMS=(
e7b937608a758004af5a9c254c77069b
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  PKG_CONFIG_PATH=$PWD:$PKG_CONFIG_PATH CC="$CC $BUILD" CXX="$CXX $BUILD" \
    ./configure --prefix=/usr --libdir=/usr/$LIBSDIR || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}
