#!/bin/bash

DONT_REMOVE=1
DISABLE_MULTILIB=1

VERSION="2.20.51.0.11"

DIR="binutils-${VERSION}"
TARBALL="binutils-${VERSION}.tar.bz2"

SRC1=(
  http://ftp.kernel.org/pub/linux/devel/binutils/${TARBALL}
)

MD5SUMS=(
d2306466e669700abbb3d1a64b10d5d2
)

Cross_Tools_Build(){
  local CONF PREF
  CONF=
  case $(echo $BUILDTARGET | cut -f1 -d'-') in
    i?86)
      CONF="--disable-multilib"
    ;;
    x86_64)
      case $SYSTYPE in
        64BIT)
          CONF="--enable-64-bit-bfd --disable-multilib"
        ;;
        MULTILIB)
          CONF="--enable-64-bit-bfd"
        ;;
      esac
    ;;
  esac
  PREF="$CTCDIR"
  if [ "$1" == "ToolsBuild" ]; then
    PREF="$TCDIR"
  else
    CONF="$CONF --with-sysroot=${ROOT}"
  fi
  
  CONF="--host="$BUILDHOST" --target="$BUILDTARGET" --prefix=$PREF --with-lib-path=$TCDIR/$LIBSDIR --disable-nls --enable-shared $CONF"
  
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
    
  mkdir -p $SRCDIR/binutils-build || return 1
  cd $SRCDIR/binutils-build || return 1
  if [ "$1" == "ToolsBuild" ]; then
    CC="$CC $BUILD" ../$DIR/configure $CONF || return 1
  else
    AR="ar" AS="as" ../$DIR/configure $CONF || return 1
  fi
  make configure-host || return 1
  make || return 1
  make install || return 1
  cp ../$DIR/include/libiberty.h $TCDIR/include || return 1
  cd ../ || return 1
  rm -rf $DIR binutils-build || return 1
}

Tools_Build(){
  Cross_Tools_Build ToolsBuild || return 1
  return 0
}

build(){
  local PATCHES CONF
  CONF=
  case $(echo $BUILDTARGET | cut -f1 -d'-') in
    i486|i586|i686)
      CONF="--disable-multilib"
    ;;
    x86_64)
      case $SYSTYPE in
        64BIT)
          CONF="--enable-64-bit-bfd --disable-multilib"
        ;;
        MULTILIB)
          CONF="--enable-64-bit-bfd"
        ;;
      esac
    ;;
  esac
  mkdir -p $SRCDIR || return 1
  cd $SRCDIR || return 1
  rm -rf $DIR binutils-build || return 1
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  
  mkdir -p $SRCDIR/binutils-build || return 1
  cd $SRCDIR/binutils-build || return 1
  CC="$CC $BUILD -isystem /usr/include" LDFLAGS="-Wl,-rpath-link,/${LIBSDIR}" \
  ../$DIR/configure --prefix=/usr --libdir=/usr/$LIBSDIR \
    --enable-shared $CONF || return 1
  make configure-host || return 1
  make tooldir=/usr/$LIBSDIR/binutils || return 1
  make install tooldir=/usr/$LIBSDIR/binutils DESTDIR=$TMPROOT || return 1
  mkdir -p $TMPROOT/usr/include
  cp ../$DIR/include/libiberty.h $TMPROOT/usr/include || return 1
  cd ../ || return 1
  rm -rf $DIR binutils-build || return 1
}

version_check_info(){
  ADDRESS='http://ftp.kernel.org/pub/linux/devel/binutils/'
  VERSION_STRING='binutils-%version%.tar.bz2'
  VERSION_FILTERS='[a-z]'
}
