#!/bin/bash

DONT_REMOVE=1
VERSION="2.4.3"

DIR="bison-${VERSION}"
TARBALL="bison-${VERSION}.tar.gz"

SRC1=(
http://ftp.gnu.org/gnu/bison/${TARBALL}
)

MD5SUMS=(
ea45c778b36bdc7a720096819e292a73
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --build=$BUILDHOST \
    --host=$BUILDTARGET --prefix=/usr \
    --libdir=/usr/$LIBSDIR || return 1
  echo '#define YYENABLE_NLS 1' >> config.h || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://ftp.gnu.org/gnu/bison/'
  VERSION_STRING='bison-%version%.tar.gz'
  MIRRORS=(
    'http://ftp.gnu.org/gnu/bison/bison-%version%.tar.gz'
  )
}
