#!/bin/bash

DISABLE_MULTILIB=1

VERSION="1.5"

DIR="cabextract-${VERSION}"
TARBALL="cabextract-${VERSION}.tar.gz"

SRC1=(
http://www.cabextract.org.uk/${TARBALL}
)

MD5SUMS=(
4e22fc3b36eb028acf2115b44f85930d
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://www.cabextract.org.uk/'
  VERSION_STRING='cabextract-%version%.tar.gz'
  MIRRORS=(
    'http://www.cabextract.org.uk/cabextract-%version%.tar.gz'
  )
}
