#!/bin/bash

VERSION="1.14.12"

DIR="cairo-${VERSION}"
TARBALL="cairo-${VERSION}.tar.xz"

SRC1=(
http://cairographics.org/releases/${TARBALL}
)

MD5SUMS=(
9f0db9dbfca0966be8acd682e636d165
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR --enable-tee || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://cairographics.org/releases/'
  VERSION_STRING='cairo-%version%.tar.xz'
  VERSION_FILTERS='[a-z] [A-Z]'
}
