#!/bin/bash

DONT_REMOVE=1
VERSION="0.10.0"

DIR="check-${VERSION}"
TARBALL="check-${VERSION}.tar.gz"

SRC1=(
http://prdownloads.sourceforge.net/check/${TARBALL}
)

MD5SUMS=(
53c5e5c77d090e103a17f3ed7fd7d8b8
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" \
    ./configure --prefix=/usr --libdir=/usr/$LIBSDIR || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://sourceforge.net/projects/check/files/'
  VERSION_STRING='check-%version%.tar.gz'
}
