#!/bin/bash

DISABLE_MULTILIB=1

VERSION="6.8.2"

DIR="dhcpcd-${VERSION}"
TARBALL="dhcpcd-${VERSION}.tar.bz2"

SRC1=(
http://roy.marples.name/downloads/dhcpcd/${TARBALL}
)

MD5SUMS=(
947f2964cf280edc27746c93b83128b0
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --build=$BUILDHOST \
    --host=$BUILDTARGET --prefix=/usr --libdir=/usr/$LIBSDIR \
    --libexecdir=/usr/$LIBSDIR/dhcpcd --dbdir=/var/tmp || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://roy.marples.name/downloads/dhcpcd/'
  VERSION_STRING='dhcpcd-%version%.tar.bz2'
  VERSION_FILTERS='[a-z] 99'
}
