#!/bin/bash

DISABLE_MULTILIB=1

VERSION="3.6"

DIR="diffutils-${VERSION}"
TARBALL="diffutils-${VERSION}.tar.xz"

SRC1=(
http://ftp.gnu.org/gnu/diffutils/${TARBALL}
)

MD5SUMS=(
07cf286672ced26fba54cd0313bdc071
)

Tools_Build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --build=${BUILDHOST} \
    --host=${BUILDTARGET} --prefix=$TCDIR || return 1
    
  sed -i '/rpl_$/d' lib/config.h || return 1
    
  make || return 1
  make install || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --build=${BUILDHOST} \
    --host=${BUILDTARGET} --prefix=/usr || return 1
    
  sed -i '/rpl_$/d' lib/config.h || return 1
    
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://ftp.gnu.org/gnu/diffutils/'
  VERSION_STRING='diffutils-%version%.tar.xz'
}
