#!/bin/bash

DISABLE_MULTILIB=1

VERSION="4.1"

DIR="dosfstools-${VERSION}"
TARBALL="dosfstools-${VERSION}.tar.xz"

SRC1=(
https://github.com/dosfstools/dosfstools/releases/download/v$VERSION/$TARBALL
)

MD5SUMS=(
07a1050db1a898e9a2e03b0c4569c4bd
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --build=$BUILDHOST \
    --host=$BUILDTARGET --prefix=/usr --sbindir=/sbin || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='https://github.com/dosfstools/dosfstools/releases'
  VERSION_STRING='dosfstools-%version%.tar.xz'
}
