#!/bin/bash

DONT_REMOVE=1
VERSION="1.44.2"

DIR="e2fsprogs-${VERSION}"
TARBALL="e2fsprogs-${VERSION}.tar.gz"

SRC1=(
http://prdownloads.sourceforge.net/e2fsprogs/${TARBALL}
)

MD5SUMS=(
97b1c3603e5465667317775cf020e1a9
)

Tools_Build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  sed -i -e "/libdir.*=.*\/lib/s@/lib@/${LIBSDIR}@g" configure || return 1
  cd $SRCDIR || return 1
  rm -rf e2fsprogs-build || return 1
  mkdir -p $SRCDIR/e2fsprogs-build || return 1
  cd $SRCDIR/e2fsprogs-build || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ../$DIR/configure \
    --build=$BUILDHOST --host=$BUILDTARGET --prefix=/usr --with-root-prefix="" \
    --enable-elf-shlibs --disable-fsck || return 1
  make || return 1
  make install DESTDIR=$ROOT || return 1
  make install-libs DESTDIR=$ROOT || return 1
  cd ../ || return 1
  rm -rf $DIR e2fsprogs-build || return 1
}

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  sed -i "/libdir.*=.*\/lib/s@/lib@/${LIBSDIR}@g" configure || return 1
  cd $SRCDIR || return 1
  rm -rf e2fsprogs-build || return 1
  mkdir -p $SRCDIR/e2fsprogs-build || return 1
  cd $SRCDIR/e2fsprogs-build || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" CFLAGS="$CFLAGS -fPIC" ../$DIR/configure \
    --build=$BUILDHOST --host=$BUILDTARGET --prefix=/usr --with-root-prefix="" \
    --enable-elf-shlibs --disable-libblkid \
    --disable-libuuid --disable-fsck --disable-uuidd || return 1
  make LIBUUID="-luuid" STATIC_LIBUUID="-luuid" \
    LIBBLKID="-lblkid" STATIC_LIBBLKID="-lblkid" || return 1
  make LN='ln -s' install DESTDIR=$TMPROOT || return 1
  make install-libs DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR e2fsprogs-build || return 1
}

version_check_info(){
  ADDRESS='http://sourceforge.net/project/showfiles.php?group_id=2406&package_id=2374'
  VERSION_STRING='e2fsprogs-%version%.tar.gz'
  VERSION_FILTERS='[A-Z] [a-z]'
}
