#!/bin/bash

VERSION="0.6"

DIR="eggdbus-${VERSION}"
TARBALL="eggdbus-${VERSION}.tar.gz"

SRC1=(
  http://hal.freedesktop.org/releases/$TARBALL
)

MD5SUMS=(
b43d2a6c523fcb8b9d0b0300c4222386
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR --libexecdir=/usr/sbin --sysconfdir=/etc \
    --localstatedir=/var --disable-man-pages || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://hal.freedesktop.org/releases/'
  VERSION_STRING='eggdbus-%version%.tar.gz'
  MIRRORS=(
    'http://hal.freedesktop.org/releases/eggdbus-%version%.tar.gz'
  )
}
