#!/bin/bash

DISABLE_MULTILIB=1

VERSION="0.1.8"

DIR="epdfview-${VERSION}"
TARBALL="epdfview-${VERSION}.tar.bz2"

#my_src1(){
#  svn co -r {$(echo $VERSION | cut -f2- -d'-' | sed 's%....%&-%;s%..$%-&%')} \
#    svn://svn.emma-soft.com/epdfview/trunk $DIR || return 1
#  echo -n "Making ${TARBALL}..."
#  tar cfJ $TARBALL $DIR || return 1
#  mkdir -p $DOWNLOADDIR || return 1
#  mv $TARBALL $DOWNLOADDIR/ || return 1
#  echo " Done."
#}

SRC1=(
  http://anduin.linuxfromscratch.org/sources/BLFS/conglomeration/epdfview/${TARBALL}
)

MD5SUMS=(
e50285b01612169b2594fea375f53ae4
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  ##./autogen.sh || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR --libexecdir=/usr/sbin --sysconfdir=/etc \
    --localstatedir=/var/lib || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  sed -i -e 's%ePDFViewer%PDF Viewer%' \
    -e 's%Viewer\;Office\;GTK%Application\;Utility%' \
    -e 's%icon_epdfview-48%epdfview%' \
    $TMPROOT/usr/share/applications/epdfview.desktop || return 1
  mkdir -p $TMPROOT/usr/share/pixmaps || return 1
  cp $TMPROOT/usr/share/epdfview/pixmaps/icon_epdfview-48.png \
    $TMPROOT/usr/share/pixmaps/epdfview.png || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}
