#!/bin/bash

VERSION="2.1.0"

DIR="expat-${VERSION}"
TARBALL="expat-${VERSION}.tar.gz"

SRC1=(
http://prdownloads.sourceforge.net/expat/${TARBALL}
)

MD5SUMS=(
dd7dab7a5fea97d2a6a43f511449b7cd
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR || return 1
  make || return 1
  make install prefix=$TMPROOT/usr libdir=$TMPROOT/usr/$LIBSDIR || return 1
  rm $TMPROOT/usr/$LIBSDIR/*.la || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://sourceforge.net/projects/expat/files/expat/'
  VERSION_STRING='expat-%version%.tar.gz'
  VERSION_FILTERS='[a-z][a-z] [A-Z][A-Z]'
}
