#!/bin/bash

DISABLE_MULTILIB=1

VERSION="1.29.9.2"

DIR="faac-$VERSION"
TARBALL="faac-${VERSION}.tar.gz"

SRC1=(
http://prdownloads.sourceforge.net/faac/${TARBALL}
)

MD5SUMS=(
2b58d621fad8fda879f07b7cad8bfe10
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/${DIR} || return 1

  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR --sysconfdir=/etc || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

#version_check_info(){
#  ADDRESS='https://sourceforge.net/projects/faac/files/latest/download'
#  VERSION_STRING='faac-%version%.tar.gz'
#}
