#!/bin/bash

DISABLE_MULTILIB=1

VERSION="1.12"

DIR="feh-${VERSION}"
TARBALL="feh-${VERSION}.tar.bz2"

SRC1=(
http://www.chaosdorf.de/~derf/feh/${TARBALL}
)

MD5SUMS=(
26097651037ee0c2507e5af14f659f7c
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  make CC="$CC $BUILD" CXX="$CXX $BUILD" PREFIX=/usr || return 1
  make install PREFIX=/usr DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS="http://www.chaosdorf.de/~derf/feh/"
  VERSION_STRING="feh-%version%.tar.bz2"
}
