#!/bin/bash

DISABLE_MULTILIB=1

VERSION="0.6.2"

DIR="ffmpeg-${VERSION}"
TARBALL="${DIR}.tar.bz2"

SRC1=(
http://www.ffmpeg.org/releases/$TARBALL
)

MD5SUMS=(
f7819307dad55aa0d6b40ac0e862884d
)

build(){
  unpack_tarball "$TARBALL" || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure \
    --arch=$(echo $BUILDTARGET | cut -f1 -d'-') --prefix=/usr \
    --libdir=/usr/$LIBSDIR --enable-shared --enable-pthreads --enable-libfaac \
    --enable-libfaad --enable-libxvid --enable-gpl --enable-nonfree \
    --enable-encoder=mp4a --enable-decoder=mp4a --enable-postproc \
    --enable-swscale --enable-x11grab --enable-ffplay \
    --enable-libmp3lame || return 1
  make CC="$CC $BUILD" CXX="$CXX $BUILD" || return 1
  make install DESTDIR=$TMPROOT || return 1
  
  if [ "lib" != "$LIBSDIR" ] && [ -d "$TMPROOT/usr/lib" ]; then
    cp -a $TMPROOT/usr/lib/* $TMPROOT/usr/$LIBSDIR || return 1
    rm -rf $TMPROOT/usr/lib
  fi
  
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://www.ffmpeg.org/releases/'
  VERSION_STRING='ffmpeg-%version%.tar.bz2'
  VERSION_FILTERS='export checkout git snapshot'
}
