#!/bin/bash

DISABLE_MULTILIB=1

VERSION="4.0"

TARBALL="firefox-${VERSION}.tar.bz2"
TARBALL86="firefox-${VERSION}-x86.tar.bz2"
TARBALL64="firefox-${VERSION}-x86_64.tar.bz2"

my_src1(){
  NOTARBALL=1
  mkdir -p $DOWNLOADDIR || return 1
  cd $DOWNLOADDIR || return 1
  if [ ! -e "$TARBALL86" ]; then
    download http://releases.mozilla.org/pub/mozilla.org/firefox/releases/${VERSION}/linux-i686/en-US/${TARBALL} || return 1
    mv $TARBALL $TARBALL86 || return 1
  fi
  if [ ! -e "$TARBALL64" ]; then
    download http://releases.mozilla.org/pub/mozilla.org/firefox/releases/${VERSION}/linux-x86_64/en-US/${TARBALL} || return 1
    mv $TARBALL $TARBALL64 || return 1
  fi
  return
}

build(){
  local TB
  case $(gcc -dumpmachine | cut -f1 -d'-') in
    i686)
      TB=$TARBALL86
    ;;
    x86_64)
      TB=$TARBALL64
    ;;
    *)
      echo "ARCH not supported" > /dev/stderr
      return 1
    ;;
  esac
  
  echo -n "Unpacking ${TB}..."
  mkdir -p $TMPROOT/usr/$LIBSDIR || return 1
  tar xfj $DOWNLOADDIR/$TB -C $TMPROOT/usr/$LIBSDIR/ || return 1
  echo " Done."
  
  mkdir -p $TMPROOT/usr/bin || return 1
  ln -sfn ../$LIBSDIR/firefox/firefox $TMPROOT/usr/bin/firefox || return 1
  
  mkdir -p $TMPROOT/usr/share/applications || return 1
cat << EOF > $TMPROOT/usr/share/applications/firefox.desktop || return 1
[Desktop Entry]
Name=Browser
Comment=Browser
Exec=/usr/bin/firefox
StartupNotify=false
Icon=/usr/$LIBSDIR/firefox/icons/mozicon128.png
Terminal=0
Type=Application
Categories=Application;Network;
EOF
  chown -R root:root $TMPROOT || return 1
}

version_check_info(){
  ADDRESS='ftp://ftp.mozilla.org/pub/mozilla.org/firefox/releases/%version%/source/'
  VERSION_STRING='firefox-%version%.source.tar.bz2'
  VERSION_FILTERS='[a-z] [A-Z]'
}
