#!/bin/bash

DISABLE_MULTILIB=1

VERSION="44.0"

TARBALL="firefox-${VERSION}.tar"

MOZTARBALL="firefox-${VERSION}.tar.bz2"

my_src1(){
  mkdir 32 64 || return 1
  cd 32 || return 1
  download https://ftp.mozilla.org/pub/mozilla.org/firefox/releases/${VERSION}/linux-i686/en-US/$MOZTARBALL || return 1
  cd ../64 || return 1
  download https://ftp.mozilla.org/pub/mozilla.org/firefox/releases/${VERSION}/linux-x86_64/en-US/$MOZTARBALL || return 1
  cd ../ || return 1
  echo -n "Making ${TARBALL}..."
  tar cf $TARBALL 32 64 || return 1
  mkdir -p $DOWNLOADDIR || return 1
  mv $TARBALL $DOWNLOADDIR/ || return 1
  echo " Done."
  return
}

build(){
  local B
  case $(gcc -dumpmachine | cut -f1 -d'-') in
    i686)
      B=32
    ;;
    x86_64)
      B=64
    ;;
    *)
      echo "ARCH not supported" > /dev/stderr
      return 1
    ;;
  esac
  
  echo -n "Unpacking ${TARBALL}->${B}/${MOZTARBALL}..."
  mkdir -p $TMPROOT/usr/$LIBSDIR || return 1
  tar xfO $DOWNLOADDIR/$TARBALL $B/$MOZTARBALL | \
    tar xj -C $TMPROOT/usr/$LIBSDIR/ || return 1
  echo " Done."
  
  mkdir -p $TMPROOT/usr/bin || return 1
  ln -sfn ../$LIBSDIR/firefox/firefox $TMPROOT/usr/bin/firefox || return 1
  
  mkdir -p $TMPROOT/usr/share/applications || return 1
cat << EOF > $TMPROOT/usr/share/applications/firefox.desktop || return 1
[Desktop Entry]
Name=Browser
Comment=Browser
Exec=/usr/bin/firefox
StartupNotify=false
Icon=/usr/$LIBSDIR/firefox/icons/mozicon128.png
Terminal=0
Type=Application
Categories=Application;Network;
EOF
  chown -R root:root $TMPROOT || return 1
}

version_check_info(){
  ADDRESS='https://ftp.mozilla.org/pub/mozilla.org/firefox/releases/%version%/linux-i686/en-US/'
  VERSION_STRING='firefox-%version%.tar.bz2'
  VERSION_FILTERS='[a-z] [A-Z]'
}
