#!/bin/bash

VERSION="2.9.1"

DIR="freetype-${VERSION}"
TARBALL="freetype-${VERSION}.tar.bz2"

SRC1=(
http://prdownloads.sourceforge.net/freetype/${TARBALL}
)

MD5SUMS=(
60ef7d8160cd4bf8cb118ee9d65367ca
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR --sysconfdir=/etc --localstatedir=/var || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  #######set_multiarch $TMPROOT/usr/bin/freetype-config || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://sourceforge.net/projects/freetype/files/freetype2/'
  VERSION_STRING='freetype2/%version%/'
  VERSION_FILTERS='[a-z][a-z] [A-Z][A-Z]'
}