#!/bin/bash

VERSION="2.4.7"

DIR="freetype-${VERSION}"
TARBALL="freetype-${VERSION}.tar.bz2"

SRC1=(
http://prdownloads.sourceforge.net/freetype/${TARBALL}
)

MD5SUMS=(
dbadce8f0c5e70a0b7c51eadf2dd9394
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR --sysconfdir=/etc --localstatedir=/var || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  set_multiarch $TMPROOT/usr/bin/freetype-config || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://sourceforge.net/project/showfiles.php?group_id=3157&package_id=3121'
  VERSION_STRING='freetype-%version%.tar.bz2'
  VERSION_FILTERS='rc'
}
