#!/bin/bash

DISABLE_MULTILIB=1

VERSION="1.0.1"

DIR="fribidi-${VERSION}"
TARBALL="fribidi-${VERSION}.tar.bz2"

SRC1=(
https://github.com/fribidi/fribidi/releases/download/v$VERSION/$TARBALL
)

MD5SUMS=(
43dc37bd95551d69a7b04c05f1d95721
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='https://github.com/fribidi/fribidi/releases'
  VERSION_STRING='fribidi-%version%.tar.bz2'
}
