#!/bin/bash

DONT_REMOVE=1
VERSION="1.15"

DIR="gdbm-${VERSION}"
TARBALL="gdbm-${VERSION}.tar.gz"

SRC1=(
http://ftp.gnu.org/gnu/gdbm/${TARBALL}
)

MD5SUMS=(
8d990067ae46c75d16e8a9c79b0c4fd7
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" \
    ./configure --prefix=/usr --libdir=/usr/$LIBSDIR --enable-libgdbm-compat || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://ftp.gnu.org/gnu/gdbm/'
  VERSION_STRING='gdbm-%version%.tar.gz'
  VERSION_FILTERS='latest'
}
