#!/bin/bash

DISABLE_MULTILIB=1

VERSION="0.1.8"

DIR="gegl-${VERSION}"
TARBALL="gegl-${VERSION}.tar.bz2"

SRC1=(
ftp://ftp.gimp.org/pub/gegl/$(cut -f-2 -d'.' <<< $VERSION)/${TARBALL}
)

MD5SUMS=(
c8279b86b3d584ee4f503839fc500425
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='ftp://ftp.gimp.org/pub/gegl/%minor_version%/'
  VERSION_STRING='gegl-%version%.tar.bz2'
  MINOR_VERSION='0.1'
}
