#!/bin/bash

DISABLE_MULTILIB=1

VERSION="0.4.2"

DIR="gegl-${VERSION}"
TARBALL="gegl-${VERSION}.tar.bz2"

SRC1=(
http://download.gimp.org/pub/gegl/$(cut -f-2 -d'.' <<< $VERSION)/${TARBALL}
)

MD5SUMS=(
47b8f88c466e0a38f5e8d6181bba89bd
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}
