#!/bin/bash

DISABLE_MULTILIB=1

VERSION="4.2.3"

DIR="giflib-${VERSION}"
TARBALL="giflib-${VERSION}.tar.bz2"

SRC1=(
  http://prdownloads.sourceforge.net/giflib/$TARBALL
)

MD5SUMS=(
be1f5749c24644257a88c9f42429343d
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  sed -i "s/all: allhtml/all:/" doc/Makefile.in || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR --sysconfdir=/etc --disable-docs || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://sourceforge.net/projects/giflib/files/'
  VERSION_STRING='giflib-%version%.tar.bz2'
  VERSION_FILTERS='/'
}
