#!/bin/bash

DISABLE_MULTILIB=1

VERSION="5.1.0"

DIR="giflib-${VERSION}"
TARBALL="giflib-${VERSION}.tar.bz2"

SRC1=(
  http://prdownloads.sourceforge.net/giflib/$TARBALL
)

MD5SUMS=(
c7e9f1c10b755ab955156d4c1ac7fc5d
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR --sysconfdir=/etc || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://sourceforge.net/projects/giflib/files/'
  VERSION_STRING='giflib-%version%.tar.bz2'
  VERSION_FILTERS='/'
}
