#!/bin/bash

DISABLE_MULTILIB=1

VERSION="2.10.2"

DIR="gimp-${VERSION}"
TARBALL="gimp-${VERSION}.tar.bz2"

SRC1=(
http://download.gimp.org/pub/gimp/v2.$(echo $VERSION | cut -f2 -d'.')/${TARBALL}
)

MD5SUMS=(
66b527cac13485be411dd254896c20ae
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR --sysconfdir=/etc || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  sed -i -e 's%GNU Image Manipulation Program%Image Editor%' \
    $TMPROOT/usr/share/applications/gimp.desktop || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://download.gimp.org/pub/gimp/v%minor_version%/'
  VERSION_STRING='gimp-%version%.tar.bz2'
  ONLY_EVEN_MINORS=1
}
