#!/bin/bash

DISABLE_MULTILIB=1

VERSION="2.6.10"

DIR="gimp-${VERSION}"
TARBALL="gimp-${VERSION}.tar.bz2"

SRC1=(
http://gimp.mirrors.hoobly.com/gimp/v2.6/${TARBALL}
ftp://ftp.cs.umn.edu/pub/gimp/v2.6/${TARBALL}
ftp://ftp.gimp.org/pub/gimp/v2.6/${TARBALL}
)

MD5SUMS=(
b92710ad9f1b52fec98554d765473819
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR --sysconfdir=/etc || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  sed -i -e 's%GNU Image Manipulation Program%Image Editor%' \
    $TMPROOT/usr/share/applications/gimp.desktop || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='ftp://ftp.gimp.org/pub/gimp/v%minor_version%/'
  VERSION_STRING='gimp-%version%.tar.bz2'
  ONLY_EVEN_MINORS=1
}
