#!/bin/bash

DISABLE_MULTILIB=1

VERSION="2.16.1"

DIR="git-${VERSION}"
TARBALL="git-${VERSION}.tar.xz"

SRC1=(
http://kernel.org/pub/software/scm/git/${TARBALL}
http://mirror.anl.gov/pub/software/scm/git/$TARBALL
)

MD5SUMS=(
57b94ffae92d4e8f4c7c46dd95ed99b1
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr --sysconfdir=/etc \
    --libexecdir=/usr/$LIBSDIR || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://kernel.org/pub/software/scm/git/'
  VERSION_STRING='git-%version%.tar.xz'
  VERSION_FILTERS='rc manpages htmldocs core'
}
