#!/bin/bash

VERSION="2.56.1"

DIR="glib-${VERSION}"
TARBALL="glib-${VERSION}.tar.xz"

SRC1=(
  $(gnome_mirrors glib)
)

MD5SUMS=(
988af38524804ea1ae6bc9a2bad181ff
)

build(){
  local FFIV
  FFIV=$(cat /var/lib/packages/current/libffi/version)
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" \
    LIBFFI_CFLAGS="-I/usr/$LIBSDIR/libffi-$FFIV/include" \
    LIBFFI_LIBS="-L/usr/$LIBSDIR -lffi" ./configure --build=$BUILDTARGET \
    --host=$BUILDTARGET --prefix=/usr --libdir=/usr/$LIBSDIR || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://ftp.gnome.org/pub/GNOME/sources/glib/%minor_version%/'
  VERSION_STRING='glib-%version%.tar.xz'
  ONLY_EVEN_MINORS=1
}
