#!/bin/bash

VERSION="2.42.1"

DIR="glib-${VERSION}"
TARBALL="glib-${VERSION}.tar.xz"

SRC1=(
  $(gnome_mirrors glib)
)

MD5SUMS=(
89c4119e50e767d3532158605ee9121a
)

build(){
  local FFIV
  FFIV=$(cat /var/lib/packages/current/libffi/version)
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" \
    LIBFFI_CFLAGS="-I/usr/$LIBSDIR/libffi-$FFIV/include" \
    LIBFFI_LIBS="-L/usr/$LIBSDIR -lffi" ./configure --build=$BUILDTARGET \
    --host=$BUILDTARGET --prefix=/usr --libdir=/usr/$LIBSDIR || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}
