#!/bin/bash

DISABLE_MULTILIB=1

VERSION="2.56.1"

DIR="glib-networking-${VERSION}"
TARBALL="glib-networking-${VERSION}.tar.xz"

SRC1=(
  $(gnome_mirrors glib-networking)
)

MD5SUMS=(
456572f1e8fea32ef747541d64508a8e
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  rm -rf build
  mkdir build || return 1
  cd build || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" meson --prefix=/usr \
      -Dlibproxy_support=false \
      -Dca_certificates_path=/etc/ssl/ca-bundle.crt --libdir=/usr/$LIBSDIR || return 1
  ninja || return 1
  ls
  DESTDIR=$TMPROOT ninja install || return 1
  cd ../../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://ftp.gnome.org/pub/GNOME/sources/glib-networking/%minor_version%/'
  VERSION_STRING='glib-networking-%version%.tar.xz'
  ONLY_EVEN_MINORS=1
}
