#!/bin/bash

VERSION="9.0.0"

DIR="glu-${VERSION}"
TARBALL="glu-${VERSION}.tar.bz2"

SRC1=(
ftp://ftp.freedesktop.org/pub/mesa/glu/$TARBALL
)

MD5SUMS=(
be9249132ff49275461cf92039083030
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR --disable-static || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd $SRCDIR || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='ftp://ftp.freedesktop.org/pub/mesa/glu/'
  VERSION_STRING='glu-%version%.tar.bz2'
}
