#!/bin/bash

DISABLE_MULTILIB=1

VERSION="3.12.0"

DIR="gnome-icon-theme-${VERSION}"
TARBALL="gnome-icon-theme-${VERSION}.tar.xz"

SRC1=(
  $(gnome_mirrors gnome-icon-theme)
)

MD5SUMS=(
f14bed7f804e843189ffa7021141addd
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR --libexecdir=/usr/sbin --sysconfdir=/etc/gnome \
    --localstatedir=/var/lib || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://ftp.gnome.org/pub/GNOME/sources/gnome-icon-theme/%minor_version%/'
  VERSION_STRING='gnome-icon-theme-%version%.tar.xz'
  ONLY_EVEN_MINORS=1
}
