#!/bin/bash

VERSION="1.44.0"

DIR="gobject-introspection-${VERSION}"
TARBALL="gobject-introspection-${VERSION}.tar.xz"

SRC1=(
  $(gnome_mirrors gobject-introspection)
)

MD5SUMS=(
7ef8a1db7f74f4193a2397b1587eb913
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR --libexecdir=/usr/sbin \
    --sysconfdir=/etc || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  
  if [ "$SYSTYPE" == "MULTILIB" ]; then
    sed -i "s%/usr/bin/python%&-${USE_ARCH}%" \
      $(grep -l /usr/bin/python $TMPROOT/usr/bin/*) || return 1
    set_multiarch $TMPROOT/usr/bin/* || return 1
  fi
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://ftp.gnome.org/pub/GNOME/sources/gobject-introspection/%minor_version%/'
  VERSION_STRING='gobject-introspection-%version%.tar.xz'
  ONLY_EVEN_MINORS=1
}
