#!/bin/bash

VERSION="0.10.7"

DIR="gobject-introspection-${VERSION}"
TARBALL="gobject-introspection-${VERSION}.tar.bz2"

SRC1=(
  $(gnome_mirrors gobject-introspection)
)

MD5SUMS=(
86d039314b38a8c7dd315a71a50e086d
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR --libexecdir=/usr/sbin \
    --sysconfdir=/etc || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  if [ "$SYSTYPE" == "MULTILIB" ]; then
    for x in $(grep -l /usr/bin/python $TMPROOT/usr/bin/*); do
      sed -i "s%/usr/bin/python%&-${USE_ARCH}%" $x || return 1
    done
    set_multiarch $TMPROOT/usr/bin/* || return 1
  fi
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://ftp.gnome.org/pub/GNOME/sources/gobject-introspection/%minor_version%/'
  VERSION_STRING='gobject-introspection-%version%.tar.bz2'
  VERSION_FILTERS="cache"
  #ONLY_EVEN_MINORS=1
}
