#!/bin/bash

DISABLE_MULTILIB=1

VERSION="2.10.1"

DIR="gtksourceview-${VERSION}"
TARBALL="gtksourceview-${VERSION}.tar.bz2"

SRC1=(
  $(gnome_mirrors gtksourceview)
)

MD5SUMS=(
1ed3eae620ec95b82baae9de6600af22
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR --libexecdir=/usr/sbin --sysconfdir=/etc/gnome \
    --localstatedir=/var/lib || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://ftp.gnome.org/pub/GNOME/sources/gtksourceview/%minor_version%/'
  VERSION_STRING='gtksourceview-%version%.tar.bz2'
  ONLY_EVEN_MINORS=1
}
