#!/bin/bash

VERSION="0.9.37"

DIR="harfbuzz-${VERSION}"
TARBALL="harfbuzz-${VERSION}.tar.bz2"

SRC1=(
http://www.freedesktop.org/software/harfbuzz/release/${TARBALL}
)

MD5SUMS=(
bfe733250e34629a188d82e3b971bc1e
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR --sysconfdir=/etc || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://www.freedesktop.org/software/harfbuzz/release/'
  VERSION_STRING='harfbuzz-%version%.tar.bz2'
}
