#!/bin/bash

VERSION="1.8.1"

DIR="harfbuzz-${VERSION}"
TARBALL="harfbuzz-${VERSION}.tar.bz2"

SRC1=(
http://www.freedesktop.org/software/harfbuzz/release/${TARBALL}
)

MD5SUMS=(
97cb89c6e2a914c05c8b7e858703885f
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR --sysconfdir=/etc || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://www.freedesktop.org/software/harfbuzz/release/'
  VERSION_STRING='harfbuzz-%version%.tar.bz2'
}
