#!/bin/bash

DISABLE_MULTILIB=1

VERSION="0.13"

DIR="hicolor-icon-theme-${VERSION}"
TARBALL="hicolor-icon-theme-${VERSION}.tar.gz"

SRC1=(
http://icon-theme.freedesktop.org/releases/${TARBALL}
)

MD5SUMS=(
21d0f50aa6b8eef02846cda9e5e9324c
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://icon-theme.freedesktop.org/releases/'
  VERSION_STRING='hicolor-icon-theme-%version%.tar.gz'
}
