#!/bin/bash

DISABLE_MULTILIB=1

VERSION="3.10.9"

DIR="hplip-${VERSION}"
TARBALL="hplip-${VERSION}.tar.gz"

SRC1=(
http://prdownloads.sourceforge.net/hplip/${TARBALL}
)

MD5SUMS=(
609718830a26874fc0ea84a47b8132f3
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR --with-cupsbackenddir=/usr/$LIBSDIR/cups/backend \
    --with-cupsfilterdir=/usr/$LIBSDIR/cups/filter \
    --enable-hpijs-install || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd $SRCDIR || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://sourceforge.net/projects/hplip/files/'
  VERSION_STRING='hplip-%version%.tar.gz'
}
