#!/bin/bash

DISABLE_MULTILIB=1

VERSION="3.10.5"

DIR="hplip-${VERSION}"
TARBALL="hplip-${VERSION}.tar.gz"

SRC1=(
http://prdownloads.sourceforge.net/hplip/${TARBALL}
)

MD5SUMS=(
a4a3679d5987520226ef70d834b63b88
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd $SRCDIR || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://sourceforge.net/projects/hplip/files/'
  VERSION_STRING='hplip-%version%.tar.gz'
}
