#!/bin/bash

DISABLE_MULTILIB=1

VERSION="6.7.5-10"

DIR="ImageMagick-${VERSION}"
TARBALL="ImageMagick-${VERSION}.tar.xz"

SRC1=(
ftp://ftp.imagemagick.org/pub/ImageMagick/legacy/${TARBALL}
)

MD5SUMS=(
b5298daceff12d0fa723b4b0e4a845bc
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" LDFLAGS="-L/usr/${LIBSDIR}" ./configure \
    $CONF --prefix=/usr --libdir=/usr/$LIBSDIR --sysconfdir=/etc || return 1
  make CC="$CC $BUILD" CXX="$CXX $BUILD" || return 1
  make install DESTDIR=$TMPROOT || return 1
  set_multiarch $TMPROOT/usr/bin/{Magick,Magick++,Wand}-config || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='ftp://ftp.imagemagick.org/pub/ImageMagick/legacy/'
  VERSION_STRING='ImageMagick-%version%.tar.xz'
  VERSION_FILTERS='[0-9][0-9][0-9][0-9]'
}
