#!/bin/bash

DISABLE_MULTILIB=1

VERSION="7.0.8-3"

DIR="ImageMagick-${VERSION}"
TARBALL="ImageMagick-${VERSION}.tar.xz"

SRC1=(
ftp://ftp.imagemagick.org/pub/ImageMagick/releases/${TARBALL}
ftp://ftp.imagemagick.org/pub/ImageMagick/${TARBALL}
)

MD5SUMS=(
d98d4a737d3059934d9a538da84e6854
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" LDFLAGS="-L/usr/${LIBSDIR}" ./configure \
    $CONF --prefix=/usr --libdir=/usr/$LIBSDIR --sysconfdir=/etc || return 1
  make CC="$CC $BUILD" CXX="$CXX $BUILD" || return 1
  make install DESTDIR=$TMPROOT || return 1
  set_multiarch $TMPROOT/usr/bin/{Magick,Magick++,Wand}-config || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='ftp://ftp.imagemagick.org/pub/ImageMagick/'
  VERSION_STRING='ImageMagick-%version%.tar.xz'
  VERSION_FILTERS='[0-9][0-9][0-9][0-9]'
}
