#!/bin/bash

DISABLE_MULTILIB=1

VERSION="6.7.2"

DIR="ImageMagick-${VERSION}-10"
TARBALL="ImageMagick-${VERSION}-10.tar.bz2"

SRC1=(
ftp://ftp.imagemagick.org/pub/ImageMagick/${TARBALL}
)

MD5SUMS=(
073ec5d7f2a22db96a0e87e4322b75f9
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" LDFLAGS="-L/usr/${LIBSDIR}" ./configure \
    $CONF --prefix=/usr --libdir=/usr/$LIBSDIR --sysconfdir=/etc || return 1
  make CC="$CC $BUILD" CXX="$CXX $BUILD" || return 1
  make install DESTDIR=$TMPROOT || return 1
  set_multiarch $TMPROOT/usr/bin/{Magick,Magick++,Wand}-config || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='ftp://ftp.imagemagick.org/pub/ImageMagick/'
  VERSION_STRING='ImageMagick-%version%-10.tar.bz2'
  VERSION_FILTERS='[0-9][0-9][0-9][0-9]'
}
