#!/bin/bash

DISABLE_MULTILIB=1

VERSION="1.5.0"

DIR="imlib2-${VERSION}"
TARBALL="imlib2-${VERSION}.tar.gz"

SRC1=(
https://git.enlightenment.org/legacy/imlib2.git/snapshot/$TARBALL
)

MD5SUMS=(
ae2f2c2dd03b0bf2ce547920f23321cb
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  ./autogen.sh
  make distclean
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR --sysconfdir=/etc || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS="https://git.enlightenment.org/legacy/imlib2.git/"
  VERSION_STRING='imlib2-%version%.tar.gz'
}
