#!/bin/bash

DISABLE_MULTILIB=1

VERSION="1.4.4"

DIR="imlib2-${VERSION}"
TARBALL="imlib2-${VERSION}.tar.gz"

SRC1=(
http://prdownloads.sourceforge.net/enlightenment/${TARBALL}
)

MD5SUMS=(
20d59c7cda06742015baade6f5975415
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR --sysconfdir=/etc || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS="http://sourceforge.net/projects/enlightenment/files/"
  VERSION_STRING="imlib2-%version%.tar.gz"
  VERSION_FILTERS='/'
}
