#!/bin/bash

DISABLE_MULTILIB=1

VERSION="0.51.0"

DIR="intltool-${VERSION}"
TARBALL="intltool-${VERSION}.tar.gz"

SRC1=(
  https://launchpad.net/intltool/trunk/$VERSION/+download/$TARBALL
)

MD5SUMS=(
12e517cac2b57a0121cda351570f1e63
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  sed -i 's:\\\${:\\\$\\{:' intltool-update.in || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR --libexecdir=/usr/sbin --sysconfdir=/etc/gnome \
    --localstatedir=/var/lib || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  rm -rf $TMPROOT/var/lib/scrollkeeper
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='https://launchpad.net/intltool/+download'
  VERSION_STRING='intltool-%version%.tar.gz'
}
