#!/bin/bash

DISABLE_MULTILIB=1

VERSION="4.17.0"

DIR="iproute2-${VERSION}"
TARBALL="iproute2-${VERSION}.tar.xz"

SRC1=(
http://www.kernel.org/pub/linux/utils/net/iproute2/$TARBALL
)

MD5SUMS=(
6f3a87fe2d97c28214fc2faab2c257d6
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  sed -i '/^TARGETS/s@arpd@@g' misc/Makefile || return 1
  make CC="$CC $BUILD -I/usr/include/libnl3" CXX="$CXX $BUILD" \
    LIBDIR=/usr/$LIBSDIR SBINDIR=/sbin || return 1
  make LIBDIR=/usr/$LIBSDIR  SBINDIR=/sbin install \
    DESTDIR=$TMPROOT || return 1
  if [ "$LIBSDIR" != "lib" ] && [ -d "$TMPROOT/usr/lib" ]; then
    cp -a $TMPROOT/usr/lib $TMPROOT/usr/$LIBSDIR || return 1
    rm -rf $TMPROOT/usr/lib || return 1
  fi
  for x in $TMPROOT/etc/iproute2/*; do
    [ -f "$x" ] && mv $x ${x}.tmpnew
  done
  [ -e "$TMPROOT/sbin/arpd" ] && {
    mkdir -p $TMPROOT/usr/sbin
    mv $TMPROOT/sbin/arpd $TMPROOT/usr/sbin/ || return 1
  }
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://www.kernel.org/pub/linux/utils/net/iproute2/'
  VERSION_STRING='iproute2-%version%.tar.xz'
}
