#!/bin/bash

DISABLE_MULTILIB=1

VERSION="1.4.13"

DIR="iptables-${VERSION}"
TARBALL="iptables-${VERSION}.tar.bz2"

SRC1=(
http://www.netfilter.org/projects/iptables/files/${TARBALL}
)

MD5SUMS=(
40a15608ec57b50e9377cace546dd115
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  sed -i \
    '/if_packet/i#define __aligned_u64 __u64 __attribute__((aligned(8)))' \
    extensions/libxt_pkttype.c || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR --libexecdir=/usr/$LIBSDIR || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://www.netfilter.org/projects/iptables/downloads.html'
  VERSION_STRING='iptables-%version%.tar.bz2'
  VERSION_FILTERS='[a-z] [A-Z]'
}
