#!/bin/bash

DISABLE_MULTILIB=1

VERSION="1.1.0"

DIR="irssi-${VERSION}"
TARBALL="irssi-${VERSION}.tar.xz"

SRC1=(
https://github.com/irssi/irssi/releases/download/$VERSION/$TARBALL
)

MD5SUMS=(
159ac7a24a06b439ce227dcce51271a0
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR --sysconfdir=/etc || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='https://github.com/irssi/irssi/releases'
  VERSION_STRING='irssi-%version%.tar.xz'
  VERSION_FILTERS='rc'
}
