#!/bin/bash

DISABLE_MULTILIB=1

VERSION="171"

TARBALL32="jdk-8u${VERSION}-linux-i586.tar.gz"
TARBALL64="jdk-8u${VERSION}-linux-x64.tar.gz"

SRC1=(
http://ghaffarian.net/downloads/Java/$TARBALL32
http://mirrors.linuxeye.com/jdk/$TARBALL32
http://build.funtoo.org/distfiles/oracle-java/$TARBALL32
http://enos.itcollege.ee/~jpoial/allalaadimised/jdk8/$TARBALL32
https://www.reucon.com/cdn/java/$TARBALL32
)

SRC2=(
http://ghaffarian.net/downloads/Java/$TARBALL64
http://mirrors.linuxeye.com/jdk/$TARBALL64
http://build.funtoo.org/distfiles/oracle-java/$TARBALL64
http://enos.itcollege.ee/~jpoial/allalaadimised/jdk8/$TARBALL64
https://www.reucon.com/cdn/java/$TARBALL64
)

MD5SUMS=(
ba5d42b4237cd576ea4209b1dffef6a3
43dafc862dd98bcff889e1239625e7a3
)

build(){
  local DIR BIN JARC
  case $($CC -dumpmachine | cut -f1 -d'-') in
    i*86)
      TARBALL=$TARBALL32
      JARC=i386
    ;;
    x86_64)
      TARBALL=$TARBALL64
      JARC=amd64
    ;;
    *)
      echo "Wrong arch!" >/dev/stderr
      return 1
  esac
  
  mkdir -p $TMPROOT/usr/$LIBSDIR || return 1
  tar xvfz $DOWNLOADDIR/$TARBALL -C $TMPROOT/usr/$LIBSDIR || return 1
  cd $TMPROOT/usr/$LIBSDIR/* || return 1
  DIR=$PWD
  cd ../ || return 1
  mv $DIR $TMPROOT/usr/$LIBSDIR/jdk || return 1
  mv $TMPROOT/usr/$LIBSDIR/jdk/include $TMPROOT/usr/ || return 1
  mkdir -p $TMPROOT/etc/{ld.so.conf,profile}.d

cat << EOF > $TMPROOT/etc/ld.so.conf.d/jdk.conf
/usr/$LIBSDIR/jdk/jre/lib/$JARC
/usr/$LIBSDIR/jdk/jre/lib/$JARC/client
/usr/$LIBSDIR/jdk/jre/lib/$JARC/jli
/usr/$LIBSDIR/jdk/jre/lib/$JARC/motif21
/usr/$LIBSDIR/jdk/jre/lib/$JARC/native_threads
/usr/$LIBSDIR/jdk/jre/lib/$JARC/server
/usr/$LIBSDIR/jdk/jre/lib/$JARC/xawt
EOF

cat << EOF > $TMPROOT/etc/profile.d/jdk.sh
PATH=\$PATH:/usr/$LIBSDIR/jdk/bin:/usr/$LIBSDIR/jdk/jre/bin

if [ -z "\$MOZ_PLUGIN_PATH" ]; then
  MOZ_PLUGIN_PATH=/usr/$LIBSDIR/jdk/jre/lib/$JARC
else
  MOZ_PLUGIN_PATH=\$MOZ_PLUGIN_PATH:/usr/$LIBSDIR/jdk/jre/lib/$JARC
fi

if [ -z "\$MANPATH" ]; then
  MANPATH=/usr/$LIBSDIR/jdk/man
else
  MANPATH=\$MANPATH:/usr/$LIBSDIR/jdk/man
fi

export PATH MOZ_PLUGIN_PATH MANPATH
EOF
  chmod 755 $TMPROOT/etc/profile.d/jdk.sh || return 1
  source $TMPROOT/etc/profile.d/jdk.sh || return 1
  ##cd $SRCDIR || return 1
  ##rm -rf jdk || return 1
}

version_check_info(){
  ADDRESS='https://java.com/en/download/'
  VERSION_STRING='Version 8 Update %version%$'
}
