#!/bin/bash

DISABLE_MULTILIB=1

VERSION="1.4.2"

DIR="json-glib-${VERSION}"
TARBALL="json-glib-${VERSION}.tar.xz"

SRC1=(
  $(gnome_mirrors json-glib)
)

MD5SUMS=(
35107e23a7bbbc70f31c34f7b9adf1c3
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr --libdir=/usr/$LIBSDIR || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://ftp.gnome.org/pub/GNOME/sources/json-glib/%minor_version%/'
  VERSION_STRING='json-glib-%version%.tar.xz'
  ONLY_EVEN_MINORS=1
}
