#!/bin/bash

DISABLE_MULTILIB=1

VERSION="3.99.5"

DIR="lame-${VERSION}"
TARBALL="lame-${VERSION}.tar.gz"

SRC1=(
http://prdownloads.sourceforge.net/lame/${TARBALL}
)

MD5SUMS=(
84835b313d4a8b68f5349816d33e07ce
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR --enable-mp3rtp || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://sourceforge.net/projects/lame/files/lame/'
  VERSION_STRING='lame-%version%.tar.gz'
  VERSION_FILTERS="[a-z] 398"
}
