#!/bin/bash

DISABLE_MULTILIB=1

VERSION="1.5.0" #1.4.3 breaks xorg-server-1.19.6 (1.4.2 last good, trying 1.5.0)

DIR="libepoxy-${VERSION}"
TARBALL="libepoxy-${VERSION}.tar.xz"

SRC1=(
https://github.com/anholt/libepoxy/releases/download/$VERSION/$TARBALL
)

MD5SUMS=(
63fe3847789258254dcd7e3fdb9e7f5e
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='https://github.com/anholt/libepoxy/releases/'
  VERSION_STRING='libepoxy-%version%.tar.xz'
  VERSION_FILTERS='1.4.3'
}
