#!/bin/bash

VERSION="3.2.1"

DIR="libffi-${VERSION}"
TARBALL="libffi-${VERSION}.tar.gz"

SRC1=(
ftp://sources.redhat.com/pub/libffi/$TARBALL
)

MD5SUMS=(
83b89587607e3eb65c70d361f13bab43
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR --sysconfdir=/etc || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='ftp://sources.redhat.com/pub/libffi/'
  VERSION_STRING='libffi-%version%.tar.gz'
  VERSION_FILTERS='rc'
}
