#!/bin/bash

DISABLE_MULTILIB=1

VERSION="1.3.0.2"

DIR="libfm-${VERSION}"
TARBALL="libfm-${VERSION}.tar.xz"

SRC1=(
http://prdownloads.sourceforge.net/pcmanfm/${TARBALL}
)

MD5SUMS=(
02a024714d51e0d37afc7bd596a44f3b
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR --sysconfdir=/etc --with-extra-only \
    --with-gtk=no --disable-static || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS="https://sourceforge.net/projects/pcmanfm/files/PCManFM%20%2B%20Libfm%20%28tarball%20release%29/LibFM/"
  VERSION_STRING="libfm-%version%.tar.xz"
}
