#!/bin/bash

VERSION="1.6.3"

DIR="libgcrypt-${VERSION}"
TARBALL="libgcrypt-${VERSION}.tar.bz2"

SRC1=(
ftp://ftp.gnupg.org/gcrypt/libgcrypt/${TARBALL}
)

MD5SUMS=(
4262c3aadf837500756c2051a5c4ae5e
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --build=$BUILDHOST \
    --host=$BUILDTARGET --prefix=/usr \
    --libdir=/usr/$LIBSDIR --sysconfdir=/etc --localstatedir=/var || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  set_multiarch $TMPROOT/usr/bin/libgcrypt-config || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='ftp://ftp.gnupg.org/gcrypt/libgcrypt/'
  VERSION_STRING='libgcrypt-%version%.tar.bz2'
  MIRRORS=(
    'ftp://ftp.gnupg.org/gcrypt/libgcrypt/libgcrypt-%version%.tar.bz2'
  )
}
