#!/bin/bash

DISABLE_MULTILIB=1

VERSION="3.0.1"

DIR="libgnome-keyring-${VERSION}"
TARBALL="libgnome-keyring-${VERSION}.tar.bz2"

SRC1=(
  $(gnome_mirrors libgnome-keyring)
)

MD5SUMS=(
a29f6cb3c7717c5f43b5f50995df2ec7
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR --libexecdir=/usr/$LIBSDIR/libgnome-keyring \
    --sysconfdir=/etc/gnome --localstatedir=/var/lib || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://ftp.gnome.org/pub/GNOME/sources/libgnome-keyring/%minor_version%/'
  VERSION_STRING='libgnome-keyring-%version%.tar.bz2'
  ONLY_EVEN_MINORS=1
}
