#!/bin/bash

VERSION="1.3.1"

DIR="libjpeg-turbo-${VERSION}"
TARBALL="libjpeg-turbo-${VERSION}.tar.gz"

SRC1=(
http://downloads.sourceforge.net/libjpeg-turbo/${TARBALL}
)

MD5SUMS=(
2c3a68129dac443a72815ff5bb374b05
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  sed -i -e "/^docdir/     s:$:/libjpeg-turbo-${VERSION}:" \
       -e "/^exampledir/ s:$:/libjpeg-turbo-${VERSION}:" Makefile.in || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --host=$BUILDTARGET --prefix=/usr \
    --libdir=/usr/$LIBSDIR --mandir=/usr/share/man --with-jpeg8 \
    --disable-static --enable-shared || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

