#!/bin/bash

DISABLE_MULTILIB=1

VERSION="2.0.3"

DIR="libmng-${VERSION}"
TARBALL="libmng-${VERSION}.tar.gz"

SRC1=(
http://prdownloads.sourceforge.net/libmng/${TARBALL}
)

MD5SUMS=(
7e9a12ba2a99dff7e736902ea07383d4
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  sed -i "s:#include <jpeg:#include <stdio.h>\n&:" libmng_types.h || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://sourceforge.net/project/showfiles.php?group_id=5635&package_id=5691'
  VERSION_STRING='libmng-%version%.tar.gz'
  VERSION_FILTERS='devel'
  MIRRORS=(
    'http://prdownloads.sourceforge.net/libmng/libmng-%version%.tar.gz'
  )
}
