#!/bin/bash

DISABLE_MULTILIB=1

VERSION="2.0.3"

DIR="libmng-${VERSION}"
TARBALL="libmng-${VERSION}.tar.xz"

SRC1=(
http://prdownloads.sourceforge.net/libmng/${TARBALL}
)

MD5SUMS=(
e9e899adb1b681b17f14d91e261878c5
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  sed -i "s:#include <jpeg:#include <stdio.h>\n&:" libmng_types.h || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='https://sourceforge.net/projects/libmng/files/libmng-devel/'
  VERSION_STRING='libmng-devel/%version%/stats/timeline'
  VERSION_FILTERS='devel mng'
}
