#!/bin/bash

DISABLE_MULTILIB=1

VERSION="1.3.0"

DIR="libmypaint-${VERSION}"
TARBALL="libmypaint-${VERSION}.tar.xz"

SRC1=(
https://github.com/mypaint/libmypaint/releases/download/v$VERSION/$TARBALL
)

MD5SUMS=(
2e7200c7873514dfca26eea9e3d273f5
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='https://github.com/mypaint/libmypaint/releases/'
  VERSION_STRING='libmypaint-%version%.tar.xz'
  VERSION_FILTERS='[a-z]'
}
