#!/bin/bash

DISABLE_MULTILIB=1

VERSION="1.1.1"

DIR="libnftnl-${VERSION}"
TARBALL="libnftnl-${VERSION}.tar.bz2"

SRC1=(
https://www.netfilter.org/projects/libnftnl/files/$TARBALL
)

MD5SUMS=(
c2d35f59cef2d142d5fa19e456b4afdc
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --build=$BUILDHOST \
    --host=$BUILDTARGET --prefix=/usr --libdir=/usr/$LIBSDIR || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='https://www.netfilter.org/projects/libnftnl/downloads.html'
  VERSION_STRING='libnftnl-%version%.tar.bz2'
  #VERSION_FILTERS=latest
}
