#!/bin/bash

DISABLE_MULTILIB=1

VERSION="0.7.7"

DIR="libnotify-${VERSION}"
TARBALL="libnotify-${VERSION}.tar.xz"

SRC1=(
  $(gnome_mirrors libnotify)
)

MD5SUMS=(
e9d911f6a22435e0b922f2fe71212b59
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://ftp.gnome.org/pub/GNOME/sources/libnotify/%minor_version%/'
  VERSION_STRING='libnotify-%version%.tar.xz'
  #ONLY_EVEN_MINORS=1
}
