#!/bin/bash

DISABLE_MULTILIB=1

VERSION="1.2.0"

DIR="libnsl-${VERSION}"
TARBALL="libnsl-${VERSION}.tar.gz"

SRC1=(
https://github.com/thkukuk/libnsl/archive/v1.2.0/$TARBALL
)

MD5SUMS=(
05222024777e12e2f6d48f2e7d067ac7
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  autoreconf -fi
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr --sysconfdir=/etc \
    --libdir=/usr/$LIBSDIR || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

#version_check_info(){
#  ADDRESS='https://sourceforge.net/projects/libpng/files/libpng16/'
#  VERSION_STRING='libpng16/%version%/stats/timeline'
#  VERSION_FILTERS='[a-z]'
#}
