#!/bin/bash

DISABLE_MULTILIB=1

VERSION="3.2.25"

DIR="libnl-${VERSION}"
TARBALL="libnl-${VERSION}.tar.gz"

SRC1=(
http://www.infradead.org/~tgr/libnl/files/${TARBALL}
)

MD5SUMS=(
03f74d0cd5037cadc8cdfa313bbd195c
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR --sysconfdir=/etc --localstatedir=/var || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://www.infradead.org/~tgr/libnl/files/'
  VERSION_STRING='libnl-%version%.tar.gz'
  VERSION_FILTERS='doc rc'
}
