#!/bin/bash

DISABLE_MULTILIB=1

VERSION="1.3.2"

DIR="libogg-${VERSION}"
TARBALL="libogg-${VERSION}.tar.gz"

SRC1=(
http://downloads.xiph.org/releases/ogg/${TARBALL}
)

MD5SUMS=(
b72e1a1dbadff3248e4ed62a4177e937
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
  --libdir=/usr/$LIBSDIR || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://downloads.xiph.org/releases/ogg/'
  VERSION_STRING='libogg-%version%.tar.gz'
  VERSION_FILTERS='beta rc'
}
