#!/bin/bash

VERSION="1.4.5"

DIR="libpng-${VERSION}"
TARBALL="libpng-${VERSION}.tar.bz2"

SRC1=(
http://prdownloads.sourceforge.net/libpng/${TARBALL}
ftp://ftp.simplesystems.org/pub/libpng/png/src/$TARBALL
)

MD5SUMS=(
d500e117e4a08d5ca3bd51dca0a0bc5f
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  set_multiarch $TMPROOT/usr/bin/libpng*-config || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='ftp://ftp.simplesystems.org/pub/libpng/png/src/'
  VERSION_STRING='libpng-%version%.tar.bz2'
}
