#!/bin/bash

VERSION="1.6.34"

DIR="libpng-${VERSION}"
TARBALL="libpng-${VERSION}.tar.xz"

SRC1=(
http://prdownloads.sourceforge.net/libpng/${TARBALL}
ftp://ftp.simplesystems.org/pub/libpng/png/src/$TARBALL
)

MD5SUMS=(
c05b6ca7190a5e387b78657dbe5536b2
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  set_multiarch $TMPROOT/usr/bin/libpng*-config || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='https://sourceforge.net/projects/libpng/files/libpng16/'
  VERSION_STRING='libpng16/%version%/stats/timeline'
  VERSION_FILTERS='[a-z]'
}
