#!/bin/bash

DISABLE_MULTILIB=1

VERSION="2.32.0"

DIR="librsvg-${VERSION}"
TARBALL="librsvg-${VERSION}.tar.bz2"

SRC1=(
  $(gnome_mirrors librsvg)
)

MD5SUMS=(
b015a9bd80143ec876af489d882dc28b
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR --sysconfdir=/etc || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

post_install(){
  setup-gtk || return 1
}

post_upgrade(){
  post_install
}

version_check_info(){
  ADDRESS='http://ftp.gnome.org/pub/GNOME/sources/librsvg/%minor_version%/'
  VERSION_STRING='librsvg-%version%.tar.bz2'
  ONLY_EVEN_MINORS=1
}
