#!/bin/bash

DISABLE_MULTILIB=1

VERSION="2.40.6"

DIR="librsvg-${VERSION}"
TARBALL="librsvg-${VERSION}.tar.xz"

SRC1=(
  $(gnome_mirrors librsvg)
)

MD5SUMS=(
259fd160b47ec11f3c27d7e18e507c99
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR --sysconfdir=/etc || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

post_install(){
  setup-gtk || return 1
}

post_upgrade(){
  post_install
}

version_check_info(){
  ADDRESS='http://ftp.gnome.org/pub/GNOME/sources/librsvg/%minor_version%/'
  VERSION_STRING='librsvg-%version%.tar.xz'
  MINOR_VERSION=2.36
  ONLY_EVEN_MINORS=1
}
