#!/bin/bash

DISABLE_MULTILIB=1

VERSION="1.0.28"

DIR="libsndfile-${VERSION}"
TARBALL="libsndfile-${VERSION}.tar.gz"

DEPENDS=(
  make
)

SRC1=(
http://www.mega-nerd.com/libsndfile/files/${TARBALL}
)

MD5SUMS=(
646b5f98ce89ac60cdb060fcd398247c
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://www.mega-nerd.com/libsndfile/'
  VERSION_STRING='libsndfile-%version%.tar.gz'
  MIRRORS=(
    "http://www.mega-nerd.com/libsndfile/libsndfile-%version%.tar.gz"
  )
}
