#!/bin/bash

DONT_REMOVE=1
VERSION="4.7"

DIR="libtasn1-${VERSION}"
TARBALL="libtasn1-${VERSION}.tar.gz"

SRC1=(
http://ftp.gnu.org/gnu/libtasn1/${TARBALL}
)

MD5SUMS=(
12d10ca4ae0a3b95f7aa06a076da39ec
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" \
    ./configure --prefix=/usr --libdir=/usr/$LIBSDIR || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://ftp.gnu.org/gnu/libtasn1/'
  VERSION_STRING='libtasn1-%version%.tar.gz'
}
