#!/bin/bash

VERSION="4.0.9"

DIR="tiff-${VERSION}"
TARBALL="tiff-${VERSION}.tar.gz"

SRC1=(
http://download.osgeo.org/libtiff/${TARBALL}
http://download.osgeo.org/libtiff/old/${TARBALL}
)

MD5SUMS=(
54bad211279cc93eb4fca31ba9bfdc79
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://download.osgeo.org/libtiff/'
  VERSION_STRING='tiff-%version%.tar.gz'
  VERSION_FILTERS='alpha beta'
}
