#!/bin/bash

VERSION="4.0.6"

DIR="tiff-${VERSION}"
TARBALL="tiff-${VERSION}.tar.gz"

SRC1=(
ftp://ftp.remotesensing.org/libtiff/${TARBALL}
ftp://ftp.remotesensing.org/libtiff/old/${TARBALL}
)

MD5SUMS=(
d1d2e940dea0b5ad435f21f03d96dd72
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='ftp://ftp.remotesensing.org/libtiff/'
  VERSION_STRING='tiff-%version%.tar.gz'
  VERSION_FILTERS='alpha beta'
}
