#!/bin/bash

DISABLE_MULTILIB=1

VERSION="1.3.6"

DIR="libvorbis-${VERSION}"
TARBALL="libvorbis-${VERSION}.tar.gz"

SRC1=(
http://downloads.xiph.org/releases/vorbis/${TARBALL}
)

MD5SUMS=(
d3190649b26572d44cd1e4f553943b31
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
  --libdir=/usr/$LIBSDIR || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://downloads.xiph.org/releases/vorbis/'
  VERSION_STRING='libvorbis-%version%.tar.gz'
  VERSION_FILTERS='beta rc'
}
