#!/bin/bash

VERSION="1.1.32"

DIR="libxslt-${VERSION}"
TARBALL="libxslt-${VERSION}.tar.gz"

SRC1=(
http://xmlsoft.org/sources/$TARBALL
)

MD5SUMS=(
1fc72f98e98bf4443f1651165f3aa146
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  set_multiarch $TMPROOT/usr/bin/xslt-config || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://xmlsoft.org/sources/'
  VERSION_STRING='libxslt-%version%.tar.gz'
  VERSION_FILTERS='[a-z]'
}
