#!/bin/bash

DISABLE_MULTILIB=1

VERSION="3.2.11"

DIR="linux-${VERSION}"
TARBALL="linux-${VERSION}.tar.xz"

SRC1=(
http://www.kernel.org/pub/linux/kernel/v$(cut -f-2 -d'.'<<<$VERSION)/${TARBALL}
http://www.kernel.org/pub/linux/kernel/v$(cut -f-2 -d'.'<<<$VERSION)/testing/$TARBALL
http://www.kernel.org/pub/linux/kernel/v$(cut -f-1 -d'.'<<<$VERSION).0/${TARBALL}
)

MD5SUMS=(
0e3d5a3dab51b3c36940461582bc06df
)

source_setup(){
  local CONFIG
  if [ "$VERSION" != "$(uname -r)" ]; then
    echo "VERSION=$VERSION but running kernel is version $(uname -r)!"
    echo "If you just upgraded your kernel, reboot before setting up the source."
    return 1
  fi
  if [ ! -d "$SRCDIR/$DIR" ]; then
    mkdir -p $SRCDIR || return 1
    echo -n "Unpacking ${TARBALL}..."
    tar xfJ $DOWNLOADDIR/$TARBALL -C $SRCDIR || return 1
    echo "Done."
  fi
  cd $SRCDIR/$DIR || return 1
  make mrproper || return 1
  
  CONFIG=$(grep /boot/ /var/lib/packages/current/linux/filelist | grep config | sed q)
  if [ -e "$CONFIG" ]; then
    cp $CONFIG .config || return 1
  else
    cp /boot/$(basename $(grep " / " /etc/fstab | cut -f1 -d' '))/$(basename $CONFIG) .config || return 1
  fi
  
  for d in modules firmware; do
    sed -i "s%/lib/${d}%/${LIBSDIR}/${d}%g" $(grep -rl "/lib/${d}" *)
  done
  
  make scripts || return 1
  make prepare || return 1
  make modules_prepare || return 1
  ln -vsfn $SRCDIR/$DIR /$LIBSDIR/modules/$(uname -r)/build || return 1
  ln -vsfn $SRCDIR/$DIR /$LIBSDIR/modules/$(uname -r)/source || return 1
  ln -vsfn $SRCDIR/$DIR /usr/src/linux || return 1
  cd $SRCDIR || return 1
}

Tools_Build(){
  local KARCH KCONF MODDIR KNAME
  case $($CC -dumpmachine | cut -f1 -d'-') in
    i?86)
      KARCH=i386
      KCONF="x86-kernel.config"
    ;;
    x86_64)
      KARCH=x86_64
      KCONF="x86_64-kernel.config"
    ;;
    *)
      echo "error not ready for this arch!"
      return 1
    ;;
  esac
  if [ -e "$CONFDIR/$KCONF" ]; then
    KCONF="$CONFDIR/$KCONF"
    echo "Using custom kernel config. ($(basename ${KCONF}))"
  else
    if [ -e "$CONFDIR/${KCONF}.default" ]; then
      KCONF="$CONFDIR/${KCONF}.default"
      echo "Using default kernel config. ($(basename ${KCONF}))"
    else
      echo "No kernel config found in CONFDIR!" >/dev/stderr
      return 1
    fi
  fi
  unpack_tarball $TARBALL || return 1
  make mrproper || return 1
  sed '/=m/d' $KCONF > .config || return 1
  
  for d in modules firmware; do
    sed -i "s%/lib/${d}%/${LIBSDIR}/${d}%g" $(grep -rl "/lib/${d}" *)
  done
  
  yes "" | make ARCH=$KARCH CROSS_COMPILE=${BUILDTARGET}- oldconfig || return 1
  make ARCH=$KARCH CROSS_COMPILE=${BUILDTARGET}- || return 1
  mkdir -p $ROOT/boot || return 1
  KNAME=$(basename $KCONF | cut -f1 -d'.')-${VERSION}
  cp -v arch/$KARCH/boot/bzImage ${ROOT}/boot/$KNAME || return 1
  ln -vsfn $KNAME ${ROOT}/boot/vmlinuz || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

build(){
  local KARCH KCONF MODDIR KNAME
  case $($CC -dumpmachine | cut -f1 -d'-') in
    i486|i586|i686)
      KARCH=i386
      KCONF="x86-kernel.config"
    ;;
    x86_64)
      KARCH=x86_64
      KCONF="x86_64-kernel.config"
    ;;
    *)
      echo "error not ready for this arch!"
      return 1
    ;;
  esac
  if [ -e "$CONFDIR/$KCONF" ]; then
    KCONF="$CONFDIR/$KCONF"
    echo "Using custom kernel config. ($(basename ${KCONF}))"
  else
    if [ -e "$CONFDIR/${KCONF}.default" ]; then
      KCONF="$CONFDIR/${KCONF}.default"
      echo "Using default kernel config. ($(basename ${KCONF}))"
    else
      echo "No kernel config found in CONFDIR!" >/dev/stderr
      return 1
    fi
  fi
  
  #if [ ! -d "$HDSRCDIR/$DIR" ]; then
  #  mkdir -p $HDSRCDIR || return 1
  #  echo -n "Unpacking ${TARBALL}..."
  #  tar xfJ $DOWNLOADDIR/$TARBALL -C $HDSRCDIR || return 1
  #  echo "Done."
  #fi
  
  if [ ! -d "$SRCDIR/$DIR" ]; then
    mkdir -p $SRCDIR || return 1
    echo -n "Unpacking ${TARBALL}..."
    tar xfJ $DOWNLOADDIR/$TARBALL -C $SRCDIR || return 1
    echo "Done."
  fi
  cd $SRCDIR/$DIR || return 1
  
  make mrproper || return 1
  cp $KCONF .config || return 1
  
  
  for d in modules firmware; do
    sed -i "s%/lib/${d}%/${LIBSDIR}/${d}%g" $(grep -rl "/lib/${d}" *)
  done
  
  
  yes "" | make oldconfig || return 1
  make || return 1
  make INSTALL_MOD_PATH=$TMPROOT modules_install || return 1
  
  MODDIR="${TMPROOT}/$LIBSDIR/modules/$(uname -r)/"
  find $TMPROOT -type f -name '*.ko' | while read mod; do
    echo "xz -z9: $(echo $mod | sed "s%^${MODDIR}%%")"
    strip --strip-unneeded $mod >& /dev/null
    xz -z9 $mod || return 1
    mv -f ${mod}.xz ${mod} || return 1
  done
  mkdir -p $TMPROOT/boot || return 1
  KNAME=$(basename $KCONF | cut -f1 -d'.')-${VERSION}
  cp -v arch/$KARCH/boot/bzImage $TMPROOT/boot/$KNAME || return 1
  ln -vsfn $KNAME $TMPROOT/boot/vmlinuz || return 1
  cp -v System.map $TMPROOT/boot/${KNAME}-System.map || return 1
  cp -v .config $TMPROOT/boot/${KNAME}.config || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://www.kernel.org/pub/linux/kernel/v%minor_version%/'
  VERSION_STRING='linux-%version%.tar.xz'
  VERSION_FILTERS='rc'
  #ONLY_EVEN_MINORS=1
}
