#!/bin/bash

DISABLE_MULTILIB=1

VERSION="0.5.3"

DIR="lxappearance-${VERSION}"
TARBALL="lxappearance-${VERSION}.tar.gz"

SRC1=(
http://prdownloads.sourceforge.net/lxde/${TARBALL}
)

MD5SUMS=(
9dfdc9bd45519d51b9df2ad6650c36f5
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR --sysconfdir=/etc || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS="http://sourceforge.net/projects/lxde/files/LXAppearance"
  VERSION_STRING="lxappearance-%version%.tar.gz"
}
