#!/bin/bash

DISABLE_MULTILIB=1

VERSION="0.2.0"

DIR="lxterminal-${VERSION}"
TARBALL="lxterminal-${VERSION}.tar.gz"

SRC1=(
http://prdownloads.sourceforge.net/lxde/${TARBALL}
)

MD5SUMS=(
e80ad1b6e26212f3d43908c2ad87ba4d
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  sed -i -e 's%<CTRL><SHIFT>C%<CTRL>C%' \
    -e 's%<CTRL><SHIFT>V%<CTRL>V%' \
    -e 's%<CTRL><SHIFT>T%<CTRL>T%' \
    src/lxterminal.h || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR --sysconfdir=/etc || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS="http://sourceforge.net/projects/lxde/files/LXTerminal (terminal emulator)/LXTerminal %version%/"
  VERSION_STRING="lxterminal-%version%.tar.gz"
}
