#!/bin/bash

DONT_REMOVE=1
DISABLE_MULTILIB=1

VERSION="4.2.1"

DIR="make-${VERSION}"
TARBALL="make-${VERSION}.tar.bz2"

SRC1=(
http://ftp.gnu.org/gnu/make/${TARBALL}
)

MD5SUMS=(
15b012617e7c44c0ed482721629577ac
)

Tools_Build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  sed -i '211,217 d; 219,229 d; 232 d' glob/glob.c || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --build=$BUILDHOST \
    --host=$BUILDTARGET --prefix=$TCDIR || return 1
  make || return 1
  make install || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  sed -i '211,217 d; 219,229 d; 232 d' glob/glob.c || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --build=$BUILDHOST \
    --host=$BUILDTARGET --prefix=/usr || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://ftp.gnu.org/gnu/make/'
  VERSION_STRING='make-%version%.tar.bz2'
}
