#!/bin/bash

DONT_REMOVE=1
DISABLE_MULTILIB=1
#
#
#  MAKE 4.1 Segfaults!!!
#
#
VERSION="4.0"

DIR="make-${VERSION}"
TARBALL="make-${VERSION}.tar.bz2"

SRC1=(
http://ftp.gnu.org/gnu/make/${TARBALL}
)

MD5SUMS=(
571d470a7647b455e3af3f92d79f1c18
)

Tools_Build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --build=$BUILDHOST \
    --host=$BUILDTARGET --prefix=$TCDIR || return 1
  make || return 1
  make install || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --build=$BUILDHOST \
    --host=$BUILDTARGET --prefix=/usr || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://ftp.gnu.org/gnu/make/'
  VERSION_STRING='make-%version%.tar.bz2'
  VERSION_FILTERS='4.1'
}
