#!/bin/bash

DISABLE_MULTILIB=1

VERSION="3.78"

DIR="man-pages-${VERSION}"
TARBALL="man-pages-${VERSION}.tar.xz"

SRC1=(
http://www.kernel.org/pub/linux/docs/man-pages/${TARBALL}
)

MD5SUMS=(
6539fe50977cd7108a6a1bcad0fdb024
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  make install prefix=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://www.kernel.org/pub/linux/docs/man-pages/'
  VERSION_STRING='man-pages-%version%.tar.xz'
}
