#!/bin/bash

DISABLE_MULTILIB=1

VERSION="1.2.0"

DIR="medit-${VERSION}"
TARBALL="medit-${VERSION}.tar.bz2"

SRC1=(
http://prdownloads.sourceforge.net/mooedit/${TARBALL}
)

MD5SUMS=(
8388a8e275d0e1fa6cd19f7bb081279a
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR --sysconfdir=/etc || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

