#!/bin/bash

DISABLE_MULTILIB=1

VERSION="1.1.0"

DIR="menu-cache-${VERSION}"
TARBALL="menu-cache-${VERSION}.tar.xz"

SRC1=(
http://prdownloads.sourceforge.net/lxde/${TARBALL}
)

MD5SUMS=(
99999a0bca48b980105208760c8fd893
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR --sysconfdir=/etc || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS="http://sourceforge.net/projects/lxde/files/menu-cache/menu-cache %version%/"
  VERSION_STRING="menu-cache-%version%.tar.xz"
}
