#!/bin/bash

VERSION="11.0.2"

DIR="mesa-${VERSION}"
TARBALL="mesa-${VERSION}.tar.xz"

SRC1=(
ftp://ftp.freedesktop.org/pub/mesa/$(cut -f1 -d'-' <<< $VERSION)/$TARBALL
)

MD5SUMS=(
2b3369d64481c1f72ce2d88f7acdb0fb
)

build(){
  unset CFLAGS CXXFLAGS

  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  
  autoreconf -fi || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --build=$BUILDHOST \
    --host=$BUILDTARGET --target=$BUILDTARGET --prefix=/usr \
    --libdir=/usr/$LIBSDIR \
            --enable-texture-float         \
            --enable-gles1                 \
            --enable-gles2                 \
            --enable-osmesa                \
            --enable-xa                    \
            --enable-gbm                   \
            --enable-glx-tls               \
            --with-egl-platforms="drm,x11" \
            --with-gallium-drivers="nouveau,r600,svga,swrast" \
            --enable-sysfs || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1

  if [ "$SYSTYPE" == "MULTILIB" ] && [ "$BUILD" == "$BUILD32" ]; then
    rm -rf $TMPROOT/$LIBSDIR/dri || return 1
  fi
  
  cd $SRCDIR || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='ftp://ftp.freedesktop.org/pub/mesa/%version%/'
  VERSION_STRING='mesa-%version%.tar.xz'
  VERSION_FILTERS='[a-z]'
}
