#!/bin/bash

VERSION="10.4.2"

DIR="Mesa-${VERSION}"
TARBALL="MesaLib-${VERSION}.tar.bz2"

SRC1=(
ftp://ftp.freedesktop.org/pub/mesa/$(cut -f1 -d'-' <<< $VERSION)/$TARBALL
)

MD5SUMS=(
ca915badc9c676f811a5ee514748ef78
)

build(){
  unset CFLAGS CXXFLAGS

  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  
  autoreconf -fi || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --build=$BUILDHOST \
    --host=$BUILDTARGET --target=$BUILDTARGET --prefix=/usr \
    --libdir=/usr/$LIBSDIR \
            --enable-texture-float         \
            --enable-gles1                 \
            --enable-gles2                 \
            --enable-osmesa                \
            --enable-xa                    \
            --enable-gbm                   \
            --enable-glx-tls               \
            --with-egl-platforms="drm,x11" \
            --with-gallium-drivers="nouveau,r600,svga,swrast" \
            --enable-sysfs || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1

  if [ "$SYSTYPE" == "MULTILIB" ] && [ "$BUILD" == "$BUILD32" ]; then
    rm -rf $TMPROOT/$LIBSDIR/dri || return 1
  fi
  
  cd $SRCDIR || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='ftp://ftp.freedesktop.org/pub/mesa/%version%/'
  VERSION_STRING='MesaLib-%version%.tar.bz2'
  VERSION_FILTERS='[a-z]'
}
