#!/bin/bash

DONT_REMOVE=1
DISABLE_MULTILIB=1

VERSION="3.16"

DIR="module-init-tools-${VERSION}"
TARBALL="module-init-tools-${VERSION}.tar.bz2"

SRC1=(
http://www.kernel.org/pub/linux/utils/kernel/module-init-tools/${TARBALL}
)

MD5SUMS=(
bc44832c6e41707b8447e2847d2019f5
)

MyBuild(){
  
  MYDEST=$1
  
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  #for x in modprobe.conf.5 modules.dep.5 depmod.conf.5 depmod.8 insmod.8 \
  #  lsmod.8 rmmod.8 modprobe.8; do
  #  touch $x || return 1
  #done
  ##echo '.so man5/modprobe.conf.5' > modprobe.d.5 || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --build=$BUILDHOST \
    --host=$BUILDTARGET --prefix=/ --enable-zlib \
    --with-moddir=/$LIBSDIR/modules || return 1
  #sed -i '/MAN5 =/d;/MAN8 =/d' Makefile || return 1
  #sed -i 's%modindex_LDADD = $(LDADD) libmodtools.a%& \\%' Makefile || return 1
  make
  cd ../ || return 1
  rm -rf $DIR || return 1
  read
  return 1
  make install DESTDIR=$MYDEST || return 1
  mv $MYDEST/bin/lsmod $MYDEST/sbin/ || return 1

}

Tools_Build(){
  MyBuild $ROOT || return 1
}

build(){
  MyBuild $TMPROOT || return 1
}

version_check_info(){
  ADDRESS='http://www.kernel.org/pub/linux/utils/kernel/module-init-tools/'
  VERSION_STRING='module-init-tools-%version%.tar.bz2'
  VERSION_FILTERS='[a-z] [A-Z]'
}
