#!/bin/bash

DONT_REMOVE=1
VERSION="1.0.2"

DIR="mpc-${VERSION}"
TARBALL="mpc-${VERSION}.tar.gz"

SRC1=(
http://www.multiprecision.org/mpc/download/$TARBALL
)

MD5SUMS=(
68fadff3358fb3e7976c7a398a0af4c3
)

Cross_Tools_Build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  LDFLAGS="-Wl,-rpath,$CTCDIR/lib" \
    ./configure --prefix=$CTCDIR --libdir=$CTCDIR/lib --with-mpfr=$CTCDIR || return 1
  make || return 1
  make install || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

Tools_Build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --build=$BUILDHOST \
    --host=$BUILDTARGET --prefix=$TCDIR --libdir=$TCDIR/$LIBSDIR \
    --enable-shared || return 1
  make || return 1
  make install || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --build=$BUILDHOST --host=$BUILDTARGET \
    --prefix=/usr --libdir=/usr/$LIBSDIR --enable-shared || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://www.multiprecision.org/index.php?prog=mpc&page=download'
  VERSION_STRING='mpc-%version%.tar.gz'
}
