#!/bin/bash

VERSION="2.4.2"

DIR="mpfr-${VERSION}"
TARBALL="mpfr-${VERSION}.tar.bz2"

SRC1=(
  ftp://sources.redhat.com/pub/gcc/infrastructure/$TARBALL
)

MD5SUMS=(
89e59fe665e2b3ad44a6789f40b059a0
)

Cross_Tools_Build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  LDFLAGS="-Wl,-rpath,$CTCDIR/${LIBSDIR}" \
    ./configure --prefix=$CTCDIR --enable-shared \
    --with-gmp=$CTCDIR || return 1
  make || return 1
  make install || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

Tools_Build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --build=$BUILDHOST \
    --host=$BUILDTARGET --prefix=$TCDIR --libdir=$TCDIR/$LIBSDIR \
    --enable-shared || return 1
  make || return 1
  make install || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --build=$BUILDHOST \
    --host=$BUILDTARGET --prefix=/usr --sysconfdir=/etc --libdir=/usr/$LIBSDIR \
    --enable-shared || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='ftp://sources.redhat.com/pub/gcc/infrastructure/'
  VERSION_STRING='mpfr-%version%.tar.bz2'
  MIRRORS=(
    'ftp://sources.redhat.com/pub/gcc/infrastructure/mpfr-%version%.tar.bz2'
  )
}
