#!/bin/bash

DONT_REMOVE=1
VERSION="3.1.3"

DIR="mpfr-${VERSION}"
TARBALL="mpfr-${VERSION}.tar.xz"

SRC1=(
http://www.mpfr.org/mpfr-current/$TARBALL
)

MD5SUMS=(
6969398cd2fbc56a6af570b5273c56a9
)

Cross_Tools_Build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  LDFLAGS="-Wl,-rpath,$CTCDIR/lib" \
    ./configure --prefix=$CTCDIR --enable-shared \
    --with-gmp=$CTCDIR || return 1
  make || return 1
  make install || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

Tools_Build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --build=$BUILDHOST \
    --host=$BUILDTARGET --prefix=$TCDIR --libdir=$TCDIR/$LIBSDIR \
    --enable-shared || return 1
  make || return 1
  make install || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --build=$BUILDHOST \
    --host=$BUILDTARGET --prefix=/usr --sysconfdir=/etc --libdir=/usr/$LIBSDIR \
    --enable-shared || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://www.mpfr.org/mpfr-current/'
  VERSION_STRING='mpfr-%version%.tar.xz'
}
