#!/bin/bash

DISABLE_MULTILIB=1

VERSION="1.3.0"

DIR="mypaint-brushes-${VERSION}"
TARBALL="mypaint-brushes-v${VERSION}.tar.gz"

SRC1=(
https://github.com/Jehan/mypaint-brushes/archive/v$VERSION/$TARBALL
)

MD5SUMS=(
679190d88f67a94db57ac99017f966f5
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
cat << "EOF" | patch -Np1 || return 1
diff --git a/autogen.sh b/autogen.sh
index 18ad577..166fc3d 100755
--- a/autogen.sh
+++ b/autogen.sh
@@ -90,6 +90,9 @@ fi
 echo -n "checking for automake >= $AUTOMAKE_REQUIRED_VERSION ... "
 if ($AUTOMAKE --version) < /dev/null > /dev/null 2>&1; then
    AUTOMAKE=$AUTOMAKE
+elif (automake-1.16 --version) < /dev/null > /dev/null 2>&1; then
+   AUTOMAKE=automake-1.16
+   ACLOCAL=aclocal-1.16
 elif (automake-1.15 --version) < /dev/null > /dev/null 2>&1; then
    AUTOMAKE=automake-1.15
    ACLOCAL=aclocal-1.15
EOF
  ./autogen.sh
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

#version_check_info(){
#  ADDRESS='https://github.com/mypaint/libmypaint/releases/'
#  VERSION_STRING='libmypaint-%version%.tar.xz'
#  VERSION_FILTERS='[a-z]'
#}
