#!/bin/bash

DISABLE_MULTILIB=1

VERSION="2.8.7"

DIR="nano-${VERSION}"
TARBALL="nano-${VERSION}.tar.gz"

SRC1=(
http://ftp.gnu.org/pub/gnu/nano/${TARBALL}
)

MD5SUMS=(
90020cdacf4a63c16ed122b206e67085
)

MyBuild(){
  
  MYDEST=$1
  
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --build=$BUILDHOST \
    --host=$BUILDTARGET --prefix=/usr --sysconfdir=/etc \
    --infodir=/usr/share/info --mandir=/usr/share/man --enable-color \
    --enable-multibuffer --enable-nanorc || return 1
  make || return 1
  make install DESTDIR=$MYDEST || return 1
  mkdir -p $MYDEST/etc || return 1
  cp $MYDEST/usr/share/nano/nanorc.nanorc $MYDEST/etc/nanorc.new || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

Tools_Build(){
  MyBuild $ROOT || return 1
}

build(){
  MyBuild $TMPROOT || return 1
}

version_check_info(){
  ADDRESS='http://ftp.gnu.org/pub/gnu/nano/'
  VERSION_STRING="nano-%version%.tar.gz"
  ONLY_EVEN_MINORS=1
  MIRRORS=(
    'http://ftp.gnu.org/pub/gnu/nano/nano-%version%.tar.gz'
  )
}
