#!/bin/bash

DONT_REMOVE=1

VERSION="5.9"

DIR="ncurses-${VERSION}"
TARBALL="ncurses-${VERSION}.tar.gz"

SRC1=(
http://ftp.gnu.org/gnu/ncurses/${TARBALL}
)

MD5SUMS=(
8cb9c412e5f2d96bc6f459aa8c6282a1
)

doncpatch(){
cat << "MEOF" | patch -Np1 || return 1
Submitted By:			Douglas R. Reno <renodr2002@gmail.com>
Date:				2015-04-15
Initial Package Version:	5.9
Upstream Status: 		Unknown
Origin:				ftp://invisible-island.net/ncurses/5.9/ncurses-5.9-20141206.patch.gz
Description:			Fixes a compilation issue with GCC 5.1. Note that this patch was trimmed from the above patch.

Index: ncurses-5.9/ncurses/base/MKlib_gen.sh
===========================================================================================

--- ncurses-5.9-20141129+/ncurses/base/MKlib_gen.sh	2011-06-04 19:14:08.000000000 +0000
+++ ncurses-5.9-20141206/ncurses/base/MKlib_gen.sh	2014-12-06 18:56:25.000000000 +0000
@@ -474,11 +474,22 @@
 	-e 's/gen_$//' \
 	-e 's/  / /g' >>$TMP
 
+cat >$ED1 <<EOF
+s/  / /g
+s/^ //
+s/ $//
+s/P_NCURSES_BOOL/NCURSES_BOOL/g
+EOF
+
+# A patch discussed here:
+#	https://gcc.gnu.org/ml/gcc-patches/2014-06/msg02185.html
+# introduces spurious #line markers.  Work around that by ignoring the system's
+# attempt to define "bool" and using our own symbol here.
+sed -e 's/bool/P_NCURSES_BOOL/g' $TMP > $ED2
+cat $ED2 >$TMP
+
 $preprocessor $TMP 2>/dev/null \
-| sed \
-	-e 's/  / /g' \
-	-e 's/^ //' \
-	-e 's/_Bool/NCURSES_BOOL/g' \
+| sed -f $ED1 \
 | $AWK -f $AW2 \
 | sed -f $ED3 \
 | sed \
MEOF
}

Cross_Tools_Build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  ./configure --prefix=$TCDIR --without-shared --without-debug || return 1
  make -C include || return 1
  make -C progs tic || return 1
  install -m755 progs/tic $CTCDIR/bin/ || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

Tools_Build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  doncpatch || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --build=$BUILDHOST \
    --host=$BUILDTARGET --prefix=$TCDIR --libdir=$TCDIR/$LIBSDIR \
    --with-shared --without-debug --without-ada --enable-overwrite \
    --with-build-cc=gcc || return 1
  make || return 1
  make install || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

build(){
  local v
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  doncpatch || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --build=$BUILDHOST \
    --host=$BUILDTARGET --prefix=/usr --libdir=/$LIBSDIR --with-shared \
    --without-debug || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  mkdir -p $TMPROOT/usr/$LIBSDIR || return 1
  mv -v $TMPROOT/$LIBSDIR/lib{panel,menu,form,ncurses,ncurses++,curses}.a \
    $TMPROOT/usr/$LIBSDIR || return 1
  rm -v $TMPROOT/$LIBSDIR/lib{ncurses,menu,panel,form,curses}.so || return 1
  v=$(echo ${VERSION} | cut -b1)
  ln -svf ../../$LIBSDIR/libncurses.so.$v $TMPROOT/usr/$LIBSDIR/libcurses.so || return 1
  ln -svf ../../$LIBSDIR/libncurses.so.$v $TMPROOT/usr/$LIBSDIR/libncurses.so || return 1
  ln -svf ../../$LIBSDIR/libmenu.so.$v $TMPROOT/usr/$LIBSDIR/libmenu.so || return 1
  ln -svf ../../$LIBSDIR/libpanel.so.$v $TMPROOT/usr/$LIBSDIR/libpanel.so || return 1
  ln -svf ../../$LIBSDIR/libform.so.$v $TMPROOT/usr/$LIBSDIR/libform.so || return 1
  chmod 755 $TMPROOT/$LIBSDIR/lib{panel,menu,form,ncurses}.so.$VERSION
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://ftp.gnu.org/gnu/ncurses/'
  VERSION_STRING='ncurses-%version%.tar.gz'
  VERSION_FILTERS='5.9'
}
