#!/bin/bash

DISABLE_MULTILIB=1

VERSION="0.9.0"

DIR="nftables-${VERSION}"
TARBALL="nftables-${VERSION}.tar.bz2"

SRC1=(
http://www.netfilter.org/projects/nftables/files/${TARBALL}
)

MD5SUMS=(
d4dcb61df80aa544b2e142e91d937635
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR --libexecdir=/usr/$LIBSDIR --sbindir=/sbin \
    --disable-man-doc || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://www.netfilter.org/projects/nftables/downloads.html'
  VERSION_STRING='nftables-%version%.tar.bz2'
  VERSION_FILTERS='[a-z] [A-Z] 0.099 0.8.2'
}
