#!/bin/bash

DISABLE_MULTILIB=1

VERSION="3_19"

TVERSION="$(tr '_' '.' <<< "$VERSION")"
DIR="nss-${TVERSION}"
TARBALL="nss-${TVERSION}-with-nspr-4.10.8.tar.gz"

SRC1=(
http://ftp.mozilla.org/pub/mozilla.org/security/nss/releases/NSS_${VERSION}_RTM/src/$TARBALL
)

MD5SUMS=(
41c156420b5215fb19b46da85e66e4d8
)

build(){
  local NSPRCONF NSSV
  
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR/nss || return 1
  
  if [ "$LIBSDIR" == "$LIBSDIR64" ]; then
    make CC="$CC $BUILD" CXX="$CXX $BUILD" USE_64=1 BUILD_OPT=1 PKG_CONFIG_ALLOW_SYSTEM_LIBS=1 \
      nss_build_all || return 1
  else
    make CC="$CC $BUILD" CXX="$CXX $BUILD" BUILD_OPT=1 PKG_CONFIG_ALLOW_SYSTEM_LIBS=1 \
      nss_build_all || return 1
  fi
  
  cd $SRCDIR/$DIR/nspr || return 1
  
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --build=$BUILDHOST \
    --host=$BUILDTARGET --prefix=/usr --libdir=/usr/$LIBSDIR || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  
cat > $TMPROOT/usr/bin/nss-config << "FOOEOF"
#!/bin/bash

prefix=@prefix@

major_version=@MOD_MAJOR_VERSION@
minor_version=@MOD_MINOR_VERSION@
patch_version=@MOD_PATCH_VERSION@

usage()
{
	cat <<EOF
Usage: nss-config [OPTIONS] [LIBRARIES]
Options:
	[--prefix[=DIR]]
	[--exec-prefix[=DIR]]
	[--includedir[=DIR]]
	[--libdir[=DIR]]
	[--version]
	[--libs]
	[--cflags]
Dynamic Libraries:
	nss
	nssutil
	ssl
	smime
	softokn
EOF
	exit $1
}

if test $# -eq 0; then
	usage 1 1>&2
fi

lib_ssl=yes
lib_smime=yes
lib_nss=yes
lib_nssutil=yes
lib_softokn=yes

while test $# -gt 0; do
  case "$1" in
  -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
  *) optarg= ;;
  esac

  case $1 in
    --prefix=*)
      prefix=$optarg
      ;;
    --prefix)
      echo_prefix=yes
      ;;
    --exec-prefix=*)
      exec_prefix=$optarg
      ;;
    --exec-prefix)
      echo_exec_prefix=yes
      ;;
    --includedir=*)
      includedir=$optarg
      ;;
    --includedir)
      echo_includedir=yes
      ;;
    --libdir=*)
      libdir=$optarg
      ;;
    --libdir)
      echo_libdir=yes
      ;;
    --version)
      echo ${major_version}.${minor_version}.${patch_version}
      ;;
    --cflags)
      echo_cflags=yes
      ;;
    --libs)
      echo_libs=yes
      ;;
    ssl)
      lib_ssl=yes
      ;;
    smime)
      lib_smime=yes
      ;;
    nss)
      lib_nss=yes
      ;;
    nssutil)
      lib_nssutil=yes
      ;;
    softokn)
      lib_softokn=yes
      ;;
    *)
      usage 1 1>&2
      ;;
  esac
  shift
done

# Set variables that may be dependent upon other variables
if test -z "$exec_prefix"; then
    exec_prefix=${prefix}
fi
if test -z "$includedir"; then
    includedir=${prefix}/include/nss
fi
if test -z "$libdir"; then
    libdir=${exec_prefix}/@libdir@
fi

if test "$echo_prefix" = "yes"; then
    echo $prefix
fi

if test "$echo_exec_prefix" = "yes"; then
    echo $exec_prefix
fi

if test "$echo_includedir" = "yes"; then
    echo $includedir
fi

if test "$echo_libdir" = "yes"; then
    echo $libdir
fi

if test "$echo_cflags" = "yes"; then
    echo -I$includedir
fi

if test "$echo_libs" = "yes"; then
      libdirs="-L$libdir"
      if test -n "$lib_ssl"; then
	libdirs="$libdirs -lssl${major_version}"
      fi
      if test -n "$lib_smime"; then
	libdirs="$libdirs -lsmime${major_version}"
      fi
      if test -n "$lib_nss"; then
	libdirs="$libdirs -lnss${major_version}"
      fi
      if test -n "$lib_nssutil"; then
        libdirs="$libdirs -lnssutil${major_version}"
      fi
      if test -n "$lib_softokn"; then
        libdirs="$libdirs -lsoftokn${major_version} -lsqlite3"
      fi
      echo $libdirs
fi
FOOEOF
  
  NSSV=$(cut -f1 -d'_'<<< ${VERSION})
  
  sed -i -e "s/@MOD_MAJOR_VERSION@/${NSSV}/" \
       -e "s/@MOD_MINOR_VERSION@/$(cut -f2 -d'_'<<< ${VERSION})/" \
       -e "s/@MOD_PATCH_VERSION@/$(cut -f3 -d'_'<<< ${VERSION})/" \
       -e "s/@prefix@/\/usr/" \
       -e "s/@libdir@/${LIBSDIR}/" \
       $TMPROOT/usr/bin/nss-config || return 1
  chmod 755 $TMPROOT/usr/bin/nss-config || return 1
  
cat > $TMPROOT/usr/$LIBSDIR/pkgconfig/nss.pc << EOF
prefix=/usr
exec_prefix=/usr/bin
libdir=/usr/$LIBSDIR
includedir=/usr/include/nss

Name: NSS
Description: Network Security Services
Version: $TVERSION
Requires: sqlite3 nspr >= $($NSPRCONF --version | cut -f-2 -d'.')
Libs: -L\${libdir} -lssl${NSSV} -lsmime${NSSV} -lnss${NSSV} -lnssutil${NSSV}
Cflags: -I\${includedir}
EOF
  
  cd $SRCDIR/$DIR || return 1
  
  install -v -m755 dist/*.OBJ/lib/*.so $TMPROOT/usr/$LIBSDIR || return 1
  install -v -m644 dist/*.OBJ/lib/{*.chk,*.a} $TMPROOT/usr/$LIBSDIR || return 1
  
  mkdir -p $TMPROOT/usr/include/nss || return 1
  install -v -m644 dist/{public,private}/nss/* $TMPROOT/usr/include/nss/ || return 1
  find $TMPROOT/usr/include -type f -exec chmod 644 {} \; || return 1
  
  cd $SRCDIR || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://ftp.mozilla.org/pub/mozilla.org/security/nss/releases/'
  VERSION_STRING='NSS_%version%_RTM'
}
