#!/bin/bash

DISABLE_MULTILIB=1

VERSION="195.36.24"

DISABLE_STRIP=1

TARBALL="NVIDIA-Linux-x86-${VERSION}-pkg1.run"
DIR="NVIDIA-Linux-x86-${VERSION}-pkg1"

SRC1=(
http://us.download.nvidia.com/XFree86/Linux-x86/$VERSION/$TARBALL
ftp://download.nvidia.com/XFree86/Linux-x86/$VERSION/$TARBALL
)

MD5SUMS=(
4d0449184a4aebaa262b2ec55ceb258a
)

build(){
  case $($CC -dumpmachine | cut -f1 -d'-') in
    i?86) ;;
    *)
      echo "I can only be installed on x86!"
      return 1
    ;;
  esac
  
  $RBSDIR/setup-source linux || return 1
  mkdir -p $SRCDIR || return 1
  cd $SRCDIR || return 1
  rm -rf $DIR || return 1
  
  sh $DOWNLOADDIR/$TARBALL --extract-only || return 1
  
  cd $DIR || return 1
  cd usr/src/nv || return 1
  for f in Makefile.kbuild Makefile.nvidia; do
    sed -i 's%modprobe%true%g;s%sh makedevices.sh%@true%g' $f || return 1
    sed -i 's%depmod%true%g;s%-o root -g root%%g' $f || return 1
  done
  sed -i 's%rmmod_sanity_check)%foo1)%' conftest.sh || return 1
  sed -i 's%suser_sanity_check)%foo2)%' conftest.sh || return 1
  
  make MODULE_ROOT=$TMPROOT/lib/modules/$(uname -r)/kernel/drivers install || return 1
  gzip -v9 $TMPROOT/lib/modules/$(uname -r)/kernel/drivers/video/nvidia.ko || return 1
  mv $TMPROOT/lib/modules/$(uname -r)/kernel/drivers/video/nvidia.ko.gz \
    $TMPROOT/lib/modules/$(uname -r)/kernel/drivers/video/nvidia.ko || return 1

  cd $SRCDIR/$DIR
  mkdir -pv $TMPROOT/usr/{bin,${LIBSDIR}/{tls,X11/modules/{drivers,extensions}}} \
    $TMPROOT/usr/share/{applications,doc/NVIDIA_GLX,man/man1,pixmaps} || return 1
  
  for x in libGL libGLcore libnvidia-tls libnvidia-cfg; do
    install -vm 0755 usr/lib/${x}.so.${VERSION} \
      $TMPROOT/usr/$LIBSDIR/ || return 1
    ln -vsf ${x}.so.${VERSION} \
      $TMPROOT/usr/$LIBSDIR/${x}.so || return 1
    ln -vsf ${x}.so.${VERSION} \
      $TMPROOT/usr/$LIBSDIR/${x}.so.1 || return 1
  done
  
  install -vm 0755 usr/X11R6/lib/modules/drivers/nvidia_drv.so \
    $TMPROOT/usr/$LIBSDIR/X11/modules/drivers || return 1

  install -vm 0755 usr/X11R6/lib/modules/extensions/libglx.so.${VERSION} \
    $TMPROOT/usr/$LIBSDIR/X11/modules/extensions/libglx.so || return 1
  
  install -vm 0755 usr/lib/tls/libnvidia-tls.so.${VERSION} \
    $TMPROOT/usr/$LIBSDIR/tls/ || return 1
  
  install -vm 0755 usr/X11R6/lib/libXvMCNVIDIA.so.${VERSION} \
    $TMPROOT/usr/$LIBSDIR || return 1
  
  cp -rv usr/share/doc/* $TMPROOT//usr/share/doc/NVIDIA_GLX/ || return 1
  
  cp -va usr/share/pixmaps/* $TMPROOT/usr/share/pixmaps/ || return 1
  
  for x in nvidia-settings nvidia-xconfig; do
    install -vm 0755 usr/bin/$x $TMPROOT/usr/bin || exit 1
    zcat usr/share/man/man1/${x}.1.gz > \
      $TMPROOT/usr/share/man/man1/${x}.1 || exit 1
  done

  sed -e "s%__UTILS_PATH__%/usr/bin%" -e "s%__DOCS_PATH__%${DOCDIR}%" \
    -e "s%__PIXMAP_PATH__%/usr/share/pixmaps%" \
    usr/share/applications/nvidia-settings.desktop > \
    $TMPROOT/usr/share/applications/nvidia-settings.desktop || exit 1
  
  cd $SRCDIR || return 1
  rm -rf $DIR || return 1
}

pre_install(){
  rm -f /usr/$LIBSDIR/libGL.*
}

pre_upgrade(){
  pre_install
}

post_install(){
  depmod || return 1
}

post_upgrade(){
  post_install || return 1
}

version_check_info(){
  ADDRESS='ftp://download.nvidia.com/XFree86/Linux-x86/%version%/'
  VERSION_STRING='NVIDIA-Linux-x86-%version%-pkg1.run'
  VERSION_FILTERS='latest'
}
