#!/bin/bash

VERSION="1.1.0g"

DIR="openssl-${VERSION}"
TARBALL="openssl-${VERSION}.tar.gz"

SRC1=(
ftp://ftp.openssl.org/source/${TARBALL}
)

MD5SUMS=(
ba5f1b8b835b88cadbce9b35ed9531a6
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  MACHINE=$(echo $BUILDTARGET | cut -f1 -d'-') ./config --prefix=/usr \
  --openssldir=/etc/ssl --libdir=$LIBSDIR shared zlib-dynamic || return 1
  make CC="$CC $BUILD" || return 1
  make MANSUFFIX=ssl DESTDIR=$TMPROOT install || return 1
  rm $TMPROOT/usr/$LIBSDIR/*.a || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='ftp://ftp.openssl.org/source/'
  VERSION_STRING='openssl-%version%.tar.gz'
  VERSION_FILTERS='engine BOGUS beta fips pre'
}
