#!/bin/bash

DISABLE_MULTILIB=1

VERSION="0.23.1"

DIR="p11-kit-${VERSION}"
TARBALL="p11-kit-${VERSION}.tar.gz"

SRC1=(
http://p11-glue.freedesktop.org/releases/${TARBALL}
)

MD5SUMS=(
96f073270c489c9a594e1c9413f42db8
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR --sysconfdir=/etc --localstatedir=/var \
    --without-trust-paths || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://p11-glue.freedesktop.org/releases/'
  VERSION_STRING='p11-kit-%version%.tar.gz'
}
