#!/bin/bash

DISABLE_MULTILIB=1

VERSION="1.41.0"

DIR="pango-${VERSION}"
TARBALL="pango-${VERSION}.tar.xz"

SRC1=(
  $(gnome_mirrors pango)
)

MD5SUMS=(
f3c0d6931aefd40f5afac2566faf2717
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR --sysconfdir=/usr/$LIBSDIR || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://ftp.gnome.org/pub/GNOME/sources/pango/%minor_version%/'
  VERSION_STRING='pango-%version%.tar.xz'
}
