#!/bin/bash

DISABLE_MULTILIB=1

VERSION="2.1.11"

DIR="pciutils-${VERSION}"
TARBALL="pciutils-${VERSION}.tar.xz"

SRC1=(
https://www.kernel.org/pub/software/utils/pciutils/${TARBALL}
)

MD5SUMS=(
1fc64d6b1ec6854bea0ccb0ef89639f6
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  make CC="$CC $BUILD" CXX="$CXX $BUILD" \
    CFLAGS="$CFLAGS" PREFIX=/usr || return 1
  make install PREFIX=$TMPROOT/usr ROOT=$TMPROOT/ || return 1
  mkdir -vp $TMPROOT/usr/{include/pci,${LIBSDIR}} || return 1
  install -v -m 0644 lib/*.h $TMPROOT/usr/include/pci/ || return 1
  install -v -m 0644 lib/libpci.a $TMPROOT/usr/${LIBSDIR}/ || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='https://www.kernel.org/pub/software/utils/pciutils/'
  VERSION_STRING='pciutils-%version%.tar.xz'
  MINOR_VERSION='2.1'
}
