#!/bin/bash

DISABLE_MULTILIB=1

VERSION="1.2.5"

DIR="pcmanfm-${VERSION}"
TARBALL="pcmanfm-${VERSION}.tar.xz"

SRC1=(
http://prdownloads.sourceforge.net/pcmanfm/${TARBALL}
)

MD5SUMS=(
b4d1f8ce08d87e4f27805a246fc51ac2
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR --sysconfdir=/etc || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS="https://sourceforge.net/projects/pcmanfm/files/PCManFM%20%2B%20Libfm%20%28tarball%20release%29/PCManFM/"
  VERSION_STRING="pcmanfm-%version%.tar.xz"
}
