#!/bin/bash

VERSION="8.42"

DIR="pcre-${VERSION}"
TARBALL="pcre-${VERSION}.tar.bz2"

SRC1=(
ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/${TARBALL}
)

MD5SUMS=(
085b6aa253e0f91cae70b3cdbe8c1ac2
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR --docdir=/usr/share/doc/pcre-$VERSION \
            --enable-unicode-properties       \
            --enable-pcre16                   \
            --enable-pcre32                   \
            --enable-pcregrep-libz            \
            --enable-pcregrep-libbz2          \
            --enable-pcretest-libreadline     \
            --disable-static || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  set_multiarch $TMPROOT/usr/bin/pcre-config || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/'
  VERSION_STRING='pcre-%version%.tar.bz2'
}
