#!/bin/bash

DISABLE_MULTILIB=1

VERSION="8.38"

DIR="pcre-${VERSION}"
TARBALL="pcre-${VERSION}.tar.bz2"

SRC1=(
ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/${TARBALL}
)

MD5SUMS=(
00aabbfe56d5a48b270f999b508c5ad2
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr --enable-utf8 \
  --libdir=/usr/$LIBSDIR || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  set_multiarch $TMPROOT/usr/bin/pcre-config || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/'
  VERSION_STRING='pcre-%version%.tar.bz2'
}
