#!/bin/bash

DONT_REMOVE=1

VERSION="5.26.2"

DIR="perl-${VERSION}"
TARBALL="perl-${VERSION}.tar.gz"

SRC1=(
http://ftp.funet.fi/pub/CPAN/src/${TARBALL}
http://www.cpan.org/src/5.0/${TARBALL}
)

MD5SUMS=(
dc0fea097f3992a8cd53f8ac0810d523
)

Tools_Build(){
  local MYBUILD MYLIBSDIR
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  
  MYBUILD=$BUILD
  MYLIBSDIR=$LIBSDIR
  if [ "$SYSTYPE" == "MULTILIB" ]; then
    MYBUILD=$BUILD32
    MYLIBSDIR=$LIBSDIR32
  fi
  
  sed -i "s@/usr/include@/${TCDIR}/include@g" ext/Errno/Errno_pm.PL || return 1
  CC="$CC $MYBUILD" CXX="$CXX $MYBUILD" ./configure.gnu --prefix=$TCDIR \
    -Dcc="$CC $MYBUILD" || return 1
  make || return 1
  make install || return 1
  ln -sfv $TCDIR/bin/perl /usr/bin || return 1
  cd $SRCDIR || return 1
  rm -rf $DIR || return 1
}

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  chown -R root:root $PWD || return 1
  
  
cat << "EOF" | patch -Np1 || return 1
diff -Naur perl-5.20.1/Configure perl-5.20.1.patched/Configure
--- perl-5.20.1/Configure	2014-09-14 07:30:59.000000000 -0400
+++ perl-5.20.1.patched/Configure	2014-12-19 10:38:49.000000000 -0500
@@ -6500,6 +6500,7 @@
 : The default "style" setting is made in installstyle.U
 case "$installstyle" in
 *lib/perl5*) set dflt privlib lib/$package/$version ;;
+*lib64/perl5*) set dflt privlib lib64/$package/$version ;;
 *)	 set dflt privlib lib/$version ;;
 esac
 eval $prefixit
@@ -6748,6 +6749,7 @@
 case "$sitelib" in
 '') case "$installstyle" in
 	*lib/perl5*) dflt=$siteprefix/lib/$package/site_$prog/$version ;;
+	*lib64/perl5*) dflt=$siteprefix/lib64/$package/site_$prog/$version ;;
 	*)	 dflt=$siteprefix/lib/site_$prog/$version ;;
 	esac
 	;;
@@ -7166,6 +7168,7 @@
 		prog=`echo $package | $sed 's/-*[0-9.]*$//'`
 		case "$installstyle" in
 		*lib/perl5*) dflt=$vendorprefix/lib/$package/vendor_$prog/$version ;;
+		*lib64/perl5*) dflt=$vendorprefix/lib64/$package/vendor_$prog/$version ;;
 		*)	     dflt=$vendorprefix/lib/vendor_$prog/$version ;;
 		esac
 		;;
EOF
  
  sed -i -e '/^BUILD_ZLIB/s/True/False/' \
       -e '/^INCLUDE/s,\./zlib-src,/usr/include,' \
       -e '/^LIB/s,\./zlib-src,/usr/lib64,' \
       cpan/Compress-Raw-Zlib/config.in || return 1
  
  echo 'installstyle="${LIBSDIR}/perl5"' >> hints/linux.sh || return 1
  
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure.gnu --prefix=/usr \
    -Dvendorprefix=/usr \
    -Dman1dir=/usr/share/man/man1 \
    -Dman3dir=/usr/share/man/man3 \
    -Dpager="/bin/less -isR" \
    -Dlibpth="/usr/local/$LIBSDIR /$LIBSDIR /usr/$LIBSDIR" \
    -Dcc="$CC $BUILD" \
    -Dusethreads -Duseshrplib || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  set_multiarch $TMPROOT/usr/bin/perl{,${VERSION}} || return 1
  cd $SRCDIR || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://ftp.funet.fi/pub/CPAN/src/'
  VERSION_STRING='perl-%version%.tar.gz'
  VERSION_FILTERS="RC"
  ONLY_EVEN_MINORS=1
}
