#!/bin/bash

DISABLE_MULTILIB=1

VERSION="2.7.8"

DIR="pidgin-${VERSION}"
TARBALL="pidgin-${VERSION}.tar.bz2"

SRC1=(
http://prdownloads.sourceforge.net/pidgin/${TARBALL}
)

MD5SUMS=(
737d6a2a5bc04fe11eb0c3e0958d29fe
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR --sysconfdir=/etc/gnome --disable-meanwhile \
    --disable-avahi --disable-nm --disable-tcl --disable-vv \
    --disable-idn --disable-nss || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://sourceforge.net/projects/pidgin/files/'
  VERSION_STRING='pidgin-%version%.tar.bz2'
}
