#!/bin/bash

DISABLE_MULTILIB=1

VERSION="2.7.0"

DIR="pidgin-${VERSION}"
TARBALL="pidgin-${VERSION}.tar.bz2"

SRC1=(
http://prdownloads.sourceforge.net/pidgin/${TARBALL}
)

MD5SUMS=(
63a36f91d29f5ac5a402ffd2d7dbbb72
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR --sysconfdir=/etc/gnome --disable-meanwhile \
    --disable-avahi --disable-nm --disable-tcl --disable-vv \
    --disable-gstreamer --disable-idn --disable-nss || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://www.pidgin.im/download/source/'
  VERSION_STRING='pidgin-%version%.tar.bz2'
}
