#!/bin/bash

DISABLE_MULTILIB=1

VERSION="0.4.9"

DIR="poppler-data-${VERSION}"
TARBALL="poppler-data-${VERSION}.tar.gz"

SRC1=(
http://poppler.freedesktop.org/${TARBALL}
)

MD5SUMS=(
35cc7beba00aa174631466f06732be40
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  make install prefix=/usr DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://poppler.freedesktop.org/'
  VERSION_STRING='poppler-data-%version%.tar.gz'
}
