#!/bin/bash

DISABLE_MULTILIB=1

VERSION="0.16.4"

DIR="poppler-${VERSION}"
TARBALL="poppler-${VERSION}.tar.gz"

SRC1=(
http://www.vi.kernel.org/pub/mirrors/gentoo/source/distfiles/$TARBALL
http://poppler.freedesktop.org/${TARBALL}
)

MD5SUMS=(
2b996ca77dad04b422f67238daab48e7
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR --enable-xpdf-headers --enable-zlib || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://poppler.freedesktop.org/'
  VERSION_STRING='poppler-%version%.tar.gz'
  VERSION_FILTERS='data'
  ONLY_EVEN_MINORS=1
}
