#!/bin/bash

DISABLE_MULTILIB=1

VERSION="0.29.0"

DIR="poppler-${VERSION}"
TARBALL="poppler-${VERSION}.tar.xz"

SRC1=(
http://poppler.freedesktop.org/${TARBALL}
)

MD5SUMS=(
7a5d87b7f62db636cc59f73bbd240811
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR --enable-xpdf-headers --enable-zlib || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://poppler.freedesktop.org/'
  VERSION_STRING='poppler-%version%.tar.xz'
  VERSION_FILTERS='data'
}
