#!/bin/bash

DISABLE_MULTILIB=1

VERSION="23.1"

DIR="psmisc-${VERSION}"
TARBALL="psmisc-${VERSION}.tar.xz"

SRC1=(
http://prdownloads.sourceforge.net/psmisc/${TARBALL}
)

MD5SUMS=(
bbba1f701c02fb50d59540d1ff90d8d1
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --build=$BUILDHOST \
    --host=$BUILDTARGET --prefix=/usr --exec-prefix="" || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  mkdir -p $TMPROOT/usr/bin || return 1
  mv $TMPROOT/bin/pstree* $TMPROOT/usr/bin || return 1
  ln -sfn killall $TMPROOT/bin/pidof || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='https://sourceforge.net/projects/psmisc/files/psmisc/'
  VERSION_STRING='psmisc-%version%.tar.xz'
}
