#!/bin/bash

DONT_REMOVE=1
DISABLE_MULTILIB=1

VERSION="11.1"

DIR="pulseaudio-${VERSION}"
TARBALL="pulseaudio-${VERSION}.tar.xz"

SRC1=(
https://www.freedesktop.org/software/pulseaudio/releases/${TARBALL}
)

MD5SUMS=(
390de38231d5cdd6b43ada8939eb74f1
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1

cat << "EOF" | patch -Np1 || return 1
diff -Naur pulseaudio-11.1/configure.ac pulseaudio-11.1.patched/configure.ac
--- pulseaudio-11.1/configure.ac	2017-09-05 06:46:23.000000000 -0400
+++ pulseaudio-11.1.patched/configure.ac	2018-02-12 01:49:39.927467634 -0500
@@ -607,6 +607,9 @@
     [AC_MSG_ERROR([*** Your Linux kernel does not support memfd shared memory.
                   *** Use linux v3.17 or higher for such a feature.])])
 
+AS_IF([test "x$HAVE_MEMFD" = "x1"],
+    AC_CHECK_FUNCS([memfd_create]))
+
 AC_SUBST(HAVE_MEMFD)
 AM_CONDITIONAL([HAVE_MEMFD], [test "x$HAVE_MEMFD" = x1])
 AS_IF([test "x$HAVE_MEMFD" = "x1"], AC_DEFINE([HAVE_MEMFD], 1, [Have memfd shared memory.]))
diff -Naur pulseaudio-11.1/src/pulsecore/memfd-wrappers.h pulseaudio-11.1.patched/src/pulsecore/memfd-wrappers.h
--- pulseaudio-11.1/src/pulsecore/memfd-wrappers.h	2016-08-23 08:50:11.000000000 -0400
+++ pulseaudio-11.1.patched/src/pulsecore/memfd-wrappers.h	2018-02-12 01:49:39.927467634 -0500
@@ -20,13 +20,14 @@
   License along with PulseAudio; if not, see <http://www.gnu.org/licenses/>.
 ***/
 
-#ifdef HAVE_MEMFD
+#if defined(HAVE_MEMFD) && !defined(HAVE_MEMFD_CREATE)
 
 #include <sys/syscall.h>
 #include <fcntl.h>
 
 /*
- * No glibc wrappers exist for memfd_create(2), so provide our own.
+ * Before glibc version 2.27 there was no wrapper for memfd_create(2),
+ * so we have to provide our own.
  *
  * Also define memfd fcntl sealing macros. While they are already
  * defined in the kernel header file <linux/fcntl.h>, that file as
@@ -63,6 +64,6 @@
 #define F_SEAL_WRITE    0x0008  /* prevent writes */
 #endif
 
-#endif /* HAVE_MEMFD */
+#endif /* HAVE_MEMFD && !HAVE_MEMFD_CREATE */
 
 #endif
EOF
  
  AUTOPOINT='intltoolize --automake --copy' autoreconf -fiv || return 1
  
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --build=$BUILDHOST \
    --host=$BUILDTARGET --prefix=/usr --sysconfdir=/etc --without-caps || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  sed -i '/load-module module-console-kit/s/^/#/' $TMPROOT/etc/pulse/default.pa || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='https://www.freedesktop.org/software/pulseaudio/releases/'
  VERSION_STRING='pulseaudio-%version%.tar.xz'
  #VERSION_FILTERS=latest
}
