#!/bin/bash

DONT_REMOVE=1
DISABLE_MULTILIB=1

VERSION="12.0"

DIR="pulseaudio-${VERSION}"
TARBALL="pulseaudio-${VERSION}.tar.xz"

SRC1=(
https://www.freedesktop.org/software/pulseaudio/releases/${TARBALL}
)

MD5SUMS=(
0
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1

  AUTOPOINT='intltoolize --automake --copy' autoreconf -fiv || return 1
  
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --build=$BUILDHOST \
    --host=$BUILDTARGET --prefix=/usr --sysconfdir=/etc --without-caps || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  sed -i '/load-module module-console-kit/s/^/#/' $TMPROOT/etc/pulse/default.pa || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='https://www.freedesktop.org/software/pulseaudio/releases/'
  VERSION_STRING='pulseaudio-%version%.tar.xz'
  #VERSION_FILTERS=latest
}
