#!/bin/bash

DISABLE_MULTILIB=1

VERSION="1.8.10"

DIR="pycairo-${VERSION}"
TARBALL="pycairo-${VERSION}.tar.bz2"

SRC1=(
http://cairographics.org/releases/${TARBALL}
)

MD5SUMS=(
ddc544943d791e3c22ca8f019e10e1e3
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://cairographics.org/releases/'
  VERSION_STRING='pycairo-%version%.tar.bz2'
}
