#!/bin/bash

VERSION="3.5.0"

DIR="Python-${VERSION}"
TARBALL="Python-${VERSION}.tar.xz"

SRC1=(
http://www.python.org/ftp/python/${VERSION}/${TARBALL}
)

MD5SUMS=(
d149d2812f10cbe04c042232e7964171
)

build(){
  local PY b
  PY=python3
  
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr/$LIBSDIR/$PY \
    --includedir=/usr/$LIBSDIR/$PY/include \
    --enable-shared || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  
  mv $TMPROOT/usr/$LIBSDIR/$PY/share $TMPROOT/usr/ || return 1
  mv $TMPROOT/usr/$LIBSDIR/$PY/lib/{pkgconfig,*so*} $TMPROOT/usr/$LIBSDIR/ || return 1
  
  sed -i "s@includedir=@&\"/usr/$LIBSDIR/$PY/include\"   \#@" \
    $TMPROOT/usr/$LIBSDIR/$PY/bin/python3.?m-config || return 1
  
  mkdir -p $TMPROOT/usr/bin || return 1
  for file in $TMPROOT/usr/$LIBSDIR/$PY/bin/*; do
    b=$(basename $file)
    if [ ! -e "/usr/$LIBSDIR/python/bin/$b" ]; then
      ln -sfn ../$LIBSDIR/$PY/bin/$b \
        $TMPROOT/usr/bin/$b || return 1
    fi
  done
  
  set_multiarch $TMPROOT/usr/bin/* || return 1
  
  cd $SRCDIR || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://www.python.org/ftp/python/%version%/'
  VERSION_STRING='Python-%version%.tar.xz'
  VERSION_FILTERS='[a-z]'
  MINOR_VERSION=3
}
