#!/bin/bash

VERSION="2.7.10"

DIR="Python-${VERSION}"
TARBALL="Python-${VERSION}.tar.xz"

SRC1=(
http://www.python.org/ftp/python/${VERSION}/${TARBALL}
)

MD5SUMS=(
c685ef0b8e9f27b5e3db5db12b268ac6
)

build(){
  local PY
  PY=python
  
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr/$LIBSDIR/$PY \
    --includedir=/usr/$LIBSDIR/$PY/include \
    --enable-shared || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  
  mv $TMPROOT/usr/$LIBSDIR/$PY/share $TMPROOT/usr/ || return 1
  mv $TMPROOT/usr/$LIBSDIR/$PY/lib/{pkgconfig,*so*} $TMPROOT/usr/$LIBSDIR/ || return 1
  
  mkdir -p $TMPROOT/usr/bin || return 1
  for file in $TMPROOT/usr/$LIBSDIR/$PY/bin/*; do
    ln -sfn ../$LIBSDIR/$PY/bin/$(basename $file) \
      $TMPROOT/usr/bin/$(basename $file) || return 1
  done
  
  set_multiarch $TMPROOT/usr/bin/* || return 1
  
  cd $SRCDIR || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://www.python.org/ftp/python/%version%/'
  VERSION_STRING='Python-%version%.tar.xz'
  VERSION_FILTERS='[a-z]'
  MINOR_VERSION=2
}
