#!/bin/bash

DISABLE_MULTILIB=1

VERSION="2.3.0"

DIR=qemu-${VERSION}
TARBALL="qemu-${VERSION}.tar.bz2"

SRC1=(
http://wiki.qemu-project.org/download/${TARBALL}
)

MD5SUMS=(
2fab3ea4460de9b57192e5b8b311f221
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --sysconfdir=/etc --libdir=/usr/$LIBSDIR --enable-kvm \
    --audio-drv-list=alsa || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://wiki.qemu-project.org/download/'
  VERSION_STRING='qemu-%version%.tar.bz2'
  VERSION_FILTERS=rc
}
