#!/bin/bash

DISABLE_MULTILIB=1

VERSION="2.11.1"

DIR=qemu-${VERSION}
TARBALL="qemu-${VERSION}.tar.xz"

SRC1=(
https://download.qemu.org/$TARBALL
)

MD5SUMS=(
0ee48c0f0cae47cc5d05408e03cd199e
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --sysconfdir=/etc --libdir=/usr/$LIBSDIR --enable-kvm \
    --audio-drv-list=alsa || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='https://www.qemu.org/download/'
  VERSION_STRING='qemu-%version%.tar.xz'
  VERSION_FILTERS=rc
}
