#!/bin/bash

DISABLE_MULTILIB=1

VERSION="3.6.27"

DIR="reiserfsprogs-${VERSION}"
TARBALL="reiserfsprogs-${VERSION}.tar.xz"

SRC1=(
https://www.kernel.org/pub/linux/kernel/people/jeffm/reiserfsprogs/v${VERSION}/${TARBALL}
)

MD5SUMS=(
90c139542725efc6da3a6b1709695395
)

MyBuild(){
  
  MYDEST=$1
  
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" CFLAGS="$CFLAGS -fgnu89-inline" \
    ./configure --build=$BUILDHOST \
    --host=$BUILDTARGET --prefix=/usr --sbindir=/sbin || return 1
  make || return 1
  make install DESTDIR=$MYDEST || return 1
  ln -sfn reiserfsck $MYDEST/sbin/fsck.reiserfs || return 1
  ln -sfn mkreiserfs $MYDEST/sbin/mkfs.reiserfs || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

Tools_Build(){
  MyBuild $ROOT || return 1
}

build(){
  MyBuild $TMPROOT || return 1
}

version_check_info(){
  ADDRESS='https://www.kernel.org/pub/linux/kernel/people/jeffm/reiserfsprogs/v%version%/'
  VERSION_STRING='reiserfsprogs-%version%.tar.xz'
  VERSION_FILTERS='x'
}
