#!/bin/bash

DISABLE_MULTILIB=1

VERSION="0.1.3"

DIR="screenlets"
TARBALL="screenlets-${VERSION}.tar.gz"

SRC1=(
http://launchpad.net/screenlets/trunk/${VERSION}/+download/${TARBALL}
)

MD5SUMS=(
9e86e433e0a45e3614c8709ce184ad1b
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  python setup.py build || return 1
  python setup.py install --root $TMPROOT || return 1
  if [ ! -e "$TMPROOT/usr/$LIBSDIR" ]; then
    mv $TMPROOT/usr/lib $TMPROOT/usr/$LIBSDIR || return 1
  fi
  rm -rf $TMPROOT/usr/share/screenlets/{Brightness,CompositeManager} \
    $TMPROOT/usr/share/screenlets/{EvolutionContacts,Example,MainMenu} \
    $TMPROOT/usr/share/screenlets/{Mount,NowPlaying,Places,Test} \
    $TMPROOT/usr/share/screenlets/{VolumeControl,WindowList,Youtube} || return 1
  rm -rf $TMPROOT/usr/bin
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS="https://launchpad.net/screenlets"
  VERSION_STRING="screenlets-%version%.tar.gz"
}
