#!/bin/bash

DISABLE_MULTILIB=1

VERSION="2.0.7"

DIR="SDL2-${VERSION}"
TARBALL="SDL2-${VERSION}.tar.gz"

SRC1=(
http://www.libsdl.org/release/${TARBALL}
)

MD5SUMS=(
cdb071009d250e1782371049f0d5ca42
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  set_multiarch $TMPROOT/usr/bin/sdl2-config || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://www.libsdl.org/release/'
  VERSION_STRING='SDL2-%version%.tar.gz'
  VERSION_FILTERS='mi de'
}
