#!/bin/bash

DISABLE_MULTILIB=1

VERSION="1.3.9"

DIR="serf-${VERSION}"
TARBALL="serf-${VERSION}.tar.bz2"

SRC1=(
https://archive.apache.org/dist/serf/${TARBALL}
)

MD5SUMS=(
370a6340ff20366ab088012cd13f2b57
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  
  sed -i -e "/Append/s:RPATH=libdir,::" \
      -e "/Default/s:lib_static,::" \
      -e "/Alias/s:install_static,::" \
      -e "/  print/{s/print/print(/; s/$/)/}"  SConstruct || return 1
  
  scons PREFIX=/usr || return 1
  scons install --install-sandbox=$TMPROOT
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='https://archive.apache.org/dist/serf/'
  VERSION_STRING='serf-%version%.tar.bz2'
}
