#!/bin/bash

DISABLE_MULTILIB=1

VERSION="1.3.8"

DIR="serf-${VERSION}"
TARBALL="serf-${VERSION}.tar.bz2"

SRC1=(
http://serf.googlecode.com/svn/src_releases/${TARBALL}
)

MD5SUMS=(
2e4efe57ff28cb3202a112e90f0c2889
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  
  sed -e "/Append/s:RPATH=libdir,::" \
      -e "/Default/s:lib_static,::" \
      -e "/Alias/s:install_static,::"  SConstruct || return 1
  
  scons PREFIX=/usr || return 1
  scons install --install-sandbox=$TMPROOT
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://serf.googlecode.com/svn/src_releases/'
  VERSION_STRING='serf-%version%.tar.bz2'
}
