#!/bin/bash

DISABLE_MULTILIB=1

VERSION="1.1.0"

DIR="sessreg-${VERSION}"
TARBALL="sessreg-${VERSION}.tar.bz2"

SRC1=(
http://xorg.freedesktop.org/releases/individual/app/${TARBALL}
)

MD5SUMS=(
e238c89dabc566e1835e1ecb61b605b9
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1

cat << "EOF" | patch -Np1 || return 1
diff -Naur sessreg-1.1.0/man/Makefile.am sessreg-1.1.0.patched/man/Makefile.am
--- sessreg-1.1.0/man/Makefile.am	2015-01-20 05:00:27.000000000 +0000
+++ sessreg-1.1.0.patched/man/Makefile.am	2015-05-07 18:32:11.000000000 +0000
@@ -11,7 +11,8 @@
 filenames.sed: filenames.sed.c
 	$(AM_V_GEN)$(CPP) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
 	    $(AM_CPPFLAGS) $(CPPFLAGS) $(srcdir)/filenames.sed.c | \
-	    $(SED) -n -e '/s|__/ p' -e '/^\/__/ p' > $@
+	    grep -v "^#" | $(SED) -e '/^s|.*|g$$/!{/s|__/{N;N;s/[[:space:]]//g;}}' | \
+ 	    grep 's|__' > $@
 
 # String replacements in MAN_SUBSTS now come from xorg-macros.m4 via configure
 MAN_SUBSTS += -f filenames.sed
EOF
  
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR --sysconfdir=/etc --localstatedir=/var || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://xorg.freedesktop.org/releases/individual/app/'
  VERSION_STRING='sessreg-%version%.tar.bz2'
}
