#!/bin/bash

DISABLE_MULTILIB=1

VERSION="0.80"

DIR="shared-mime-info-${VERSION}"
TARBALL="shared-mime-info-${VERSION}.tar.bz2"

SRC1=(
http://freedesktop.org/~hadess/${TARBALL}
)

MD5SUMS=(
eb8d24a6a80888849c9db7f30232ba6a
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

post_install(){
  update-mime-database /usr/share/mime || return 1
}

post_upgrade(){
  post_install || return 1
}

version_check_info(){
  ADDRESS='http://freedesktop.org/~hadess/'
  VERSION_STRING='shared-mime-info-%version%.tar.bz2'
}
