#!/bin/bash

VERSION="4.23"

ENABLE_MULTILIB=1

DIR="strace-${VERSION}"
TARBALL="strace-${VERSION}.tar.xz"

SRC1=(
https://github.com/strace/strace/releases/download/v${VERSION}/${TARBALL}
)

MD5SUMS=(
fad4bba0947553cef34d46a9fd78f039
)

build(){
  mkdir -p $SRCDIR || return 1
  cd $SRCDIR || return 1
  rm -rf $DIR || return 1
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --build=$BUILDHOST \
    --host=$BUILDTARGET --prefix=/usr || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  set_multiarch $TMPROOT/usr/bin/strace || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='https://github.com/strace/strace/releases'
  VERSION_STRING='strace-%version%.tar.xz'
}
