#!/bin/bash

DISABLE_MULTILIB=1

VERSION="1.10.0"

DIR="subversion-${VERSION}"
TARBALL="subversion-${VERSION}.tar.bz2"

SRC1=(
http://apache.osuosl.org/subversion/${TARBALL}
)

MD5SUMS=(
0126847f9e8cb8ed0b90a6a18b203309
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  groupadd svn
  useradd -c "SVN Owner" -d /home/svn -m -g svn -s /bin/false svn
  CC="$CC $BUILD" CXX="$CXX $BUILD" \
    ./configure --prefix=/usr --libdir=/usr/$LIBSDIR --with-serf=/usr \
    --with-lz4=internal \
    --with-utf8proc=internal || return 1
  make || return 1
  make swig-pl || return 1
  make install DESTDIR=$TMPROOT || return 1
  make install-swig-pl DESTDIR=$TMPROOT || return 1
  
  install -v -d -m755 $TMPROOT/usr/share/doc/subversion-${VERSION} || return 1
  cp -v -R doc/* $TMPROOT/usr/share/doc/subversion-${VERSION} || return 1
  install -d -m0755 $TMPROOT/srv || return 1
  install -d -m0755 -o svn -g svn $TMPROOT/srv/svn/repositories || return 1
  mkdir -p $TMPROOT/etc/rc.d
cat << "EOF" > $TMPROOT/etc/rc.d/rc.subversion
#!/bin/bash

. /etc/rc.d/rc.conf
. /etc/rc.d/rc.functions

case $1 in
  start)
    print_msg "Starting Subversion"
    loadproc /usr/bin/svnserve -d -r /srv/svn/repositories
  ;;
  stop)
    print_msg "Stopping Subversion"
    killproc svnserve
  ;;
  restart)
    $0 stop
    sleep 1
    $0 start
  ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
  ;;
esac
EOF
  chmod 744 $TMPROOT/etc/rc.d/rc.subversion || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://apache.osuosl.org/subversion/'
  VERSION_STRING='subversion-%version%.tar.bz2'
  VERSION_FILTERS='[a-z]'
}
