#!/bin/bash

DISABLE_MULTILIB=1

VERSION="3.0.12"

DIR="swig-${VERSION}"
TARBALL="swig-${VERSION}.tar.gz"

SRC1=(
http://downloads.sourceforge.net/swig/${TARBALL}
)

MD5SUMS=(
82133dfa7bba75ff9ad98a7046be687c
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure  --prefix=/usr --libdir=/usr/$LIBSDIR \
     --without-clisp --without-maximum-compile-warnings || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

#version_check_info(){
#  ADDRESS='http://ftp.gnu.org/gnu/make/'
#  VERSION_STRING='make-%version%.tar.bz2'
#  VERSION_FILTERS='4.1'
#}
