#!/bin/bash

DISABLE_MULTILIB=1
DISABLE_STRIP=1

VERSION="6.03"

DIR="syslinux-${VERSION}"
TARBALL="syslinux-${VERSION}.tar.xz"

SRC1=(
http://www.kernel.org/pub/linux/utils/boot/syslinux/${TARBALL}
http://www.kernel.org/pub/linux/utils/boot/syslinux/Testing/$(cut -f1 -d'-' <<< $VERSION)/$TARBALL
)

MD5SUMS=(
92a253df9211e9c20172796ecf388f13
)

build(){
  unpack_tarball $TARBALL || return 1
  case $($CC -dumpmachine | cut -f1 -d'-') in
    i?86)
    ;;
    x86_64)
      cd $SRCDIR/$DIR || return 1
      make clean
      make CC="$CC $BUILD" || return 1
    ;;
    *)
      echo "error not ready for this arch!"
      return 1
    ;;
  esac
  mkdir -vp $TMPROOT/usr/src || return 1
  cp -va $SRCDIR/$DIR $TMPROOT/usr/src/ || return 1
  ln -vsfn $DIR $TMPROOT/usr/src/syslinux || return 1
  cd $SRCDIR || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://www.kernel.org/pub/linux/utils/boot/syslinux/'
  VERSION_STRING='syslinux-%version%.tar.xz'
}
