#!/bin/bash

DISABLE_MULTILIB=1
DISABLE_STRIP=1

VERSION="4.02"

DIR="syslinux-${VERSION}"
TARBALL="syslinux-${VERSION}.tar.bz2"

SRC1=(
http://www.kernel.org/pub/linux/utils/boot/syslinux/${TARBALL}
)

MD5SUMS=(
52912c03f5c275d6c0ac09180ebab81f
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  make clean
  make CC="$CC $BUILD" || return 1
  mkdir -vp $TMPROOT/usr/src || return 1
  cp -va $SRCDIR/$DIR $TMPROOT/usr/src/ || return 1
  ln -vsfn $DIR $TMPROOT/usr/src/syslinux || return 1
  cd $SRCDIR || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://www.kernel.org/pub/linux/utils/boot/syslinux/'
  VERSION_STRING='syslinux-%version%.tar.bz2'
}
