#!/bin/bash

VERSION="2.1.1"

DIR="talloc-${VERSION}"
TARBALL="talloc-${VERSION}.tar.gz"

SRC1=(
http://samba.org/ftp/talloc/${TARBALL}
)

MD5SUMS=(
5dffb86414218a91864ed4453ba9be07
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://samba.org/ftp/talloc/'
  VERSION_STRING='talloc-%version%.tar.gz'
  MIRRORS=(
    'http://samba.org/ftp/talloc/talloc-%version%.tar.gz'
  )
}
