#!/bin/bash

DISABLE_MULTILIB=1

VERSION="008"

DIR="usbutils-${VERSION}"
TARBALL="usbutils-${VERSION}.tar.xz"

SRC1=(
http://www.kernel.org/pub/linux/utils/usb/usbutils/${TARBALL}
http://mirror.anl.gov/pub/linux/utils/usb/usbutils/$TARBALL
)

MD5SUMS=(
2780b6ae21264c888f8f30fb2aab1259
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  ./configure --help
  return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" LIBUSB_CFLAGS="$CFLAGS" \
    LIBUSB_LIBS="-lusb" ./configure --build=$BUILDHOST \
    --host=$BUILDTARGET --prefix=/usr || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://www.kernel.org/pub/linux/utils/usb/usbutils/'
  VERSION_STRING='usbutils-%version%.tar.xz'
}
