#!/bin/bash

DONT_REMOVE=1
VERSION="2.25.2"

DIR="util-linux-${VERSION}"
TARBALL="util-linux-${VERSION}.tar.xz"

SRC1=(
http://www.kernel.org/pub/linux/utils/util-linux/v$(echo $VERSION | cut -f-2 -d'.')/${TARBALL}
)

MD5SUMS=(
cab3d7be354000f629bc601238b629b3
)

Tools_Build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --build=$BUILDHOST \
    --host=$BUILDTARGET --libdir=$TCDIR/$LIBSDIR --includedir=$TCDIR/include \
    --enable-arch --disable-login-utils --disable-makeinstall-chown \
    --without-python || return 1
  make || return 1
  make install DESTDIR=$ROOT || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --build=$BUILDHOST \
    --host=$BUILDTARGET --libdir=/$LIBSDIR \
    --enable-arch --disable-login-utils --disable-makeinstall-chown \
    --without-python || return 1
  make || return 1
  make install DESTDIR=$ROOT || return 1
  cd $SRCDIR || return 1
  rm -rf $DIR || return 1
}

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure ADJTIME_PATH=/var/lib/hwclock/adjtime \
    --libdir=/$LIBSDIR --enable-partx --disable-wall --enable-write --enable-arch || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  find $TMPROOT -name '*.la' -exec rm {} \; || return 1
  mv $TMPROOT/usr/bin/logger $TMPROOT/bin || return 1
  mkdir -p $TMPROOT/{etc,var/lib/hwclock}
cat << "EOF" > $TMPROOT/etc/fstab.tmpnew
/dev/hdz1  swap          swap      sw                         0 0
/dev/hdz2  /boot         ext3      defaults                   0 0
/dev/hdz3  /somemount1   ext3      defaults                   1 1
/dev/hdz4  /somemount2   reiserfs  defaults                   0 0
proc       /proc         proc      defaults                   0 0
sysfs      /sys          sysfs     defaults                   0 0
devpts     /dev/pts      devpts    gid=4,mode=620             0 0
shm        /dev/shm      tmpfs     defaults                   0 0
usbfs      /proc/bus/usb usbfs     devgid=15,devmode=0666     0 0
EOF
  cd $SRCDIR || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://www.kernel.org/pub/linux/utils/util-linux/v%minor_version%/'
  VERSION_STRING='util-linux-%version%.tar.xz'
  VERSION_FILTERS="rc docs pre"
}
