#!/bin/bash

DISABLE_MULTILIB=1
DISABLE_STRIP=1

VERSION="5.0.12-104815"

TARBALL="VirtualBox-${VERSION}-Linux_amd64.run"
DIR="VirtualBox-${VERSION}"

SRC1=(
http://download.virtualbox.org/virtualbox/$(echo ${VERSION} | cut -f1 -d'-')/$TARBALL
)

MD5SUMS=(
c84e53278a99c56187611f84c9eb23be
)

build(){
  case $($CC -dumpmachine | cut -f1 -d'-') in
    x86_64)
      true
    ;;
    *)
      echo "I can only be installed on x86_64!"
      return 1
    ;;
  esac
  local INST
  mkdir -p $SRCDIR/$DIR || return 1
  
  sh $DOWNLOADDIR/$TARBALL --noexec --target $SRCDIR/$DIR || return 1
  
  INST=$TMPROOT/opt/VirtualBox/
  mkdir -vp $TMPROOT/usr/{bin,share/{applications,pixmaps},src} \
    $INST || return 1
  
  tar xvfj $SRCDIR/$DIR/VirtualBox.tar.bz2 -C $INST || return 1
  
  chown -R root:root $INST || return 1
  
  cd $INST/components || return 1
  
  for x in ../*.so*; do
    ln -vsfn $x . || return 1
  done
  
  chmod u+s $INST/VirtualBox || return 1
  
  mv -v $INST/src $TMPROOT/usr/src/VirtualBox || return 1
  
  mv -v $INST/virtualbox.desktop $TMPROOT/usr/share/applications/ || return 1
  sed -i -e 's%Sun VirtualBox%Virtual Machine Manager%' -e '/\.pdf$/d' \
    $TMPROOT/usr/share/applications/virtualbox.desktop || return 1
  
  mv -v $INST/VBox.png $TMPROOT/usr/share/pixmaps/ || return 1
  
  for x in VirtualBox VBoxManage VBoxSDL VBoxHeadless vboxwebsrv; do
    ln -sfnv ../../opt/VirtualBox/$x $TMPROOT/usr/bin/$x || return 1
    ln -sfnv ../../opt/VirtualBox/$x $TMPROOT/usr/bin/$(echo $x | tr [A-Z] [a-z]) || return 1
  done
  
  mkdir -vp $TMPROOT/etc/rc.d || return 1
  
  groupadd vboxusers
  
cat << "EOF" > $TMPROOT/etc/rc.d/rc.virtualbox || return 1
#!/bin/bash

. /etc/rc.d/rc.conf
. /etc/rc.d/rc.functions

case $1 in
  start)
    for x in vboxnetadp vboxnetflt vboxdrv; do
      print_msg "virtualbox :: loading $x"
      loadproc modprobe $x
    done
  ;;
  stop)
    for x in vboxdrv vboxnetflt vboxnetadp; do
      print_msg "virtualbox :: unloading $x"
      loadproc modprobe -r $x
    done
  ;;
  restart)
    $0 stop
    sleep 1
    $0 start
  ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
  ;;
esac
EOF
  chmod 755 $TMPROOT/etc/rc.d/rc.virtualbox || return 1
  
  cd $SRCDIR || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://download.virtualbox.org/virtualbox/%version%/'
  VERSION_STRING='VirtualBox-%version%-Linux_amd64.run'
  VERSION_FILTERS='TXT de im rd rp ox Us BETA'
}
