#!/bin/bash

DISABLE_MULTILIB=1

VERSION="1.19.5"

DIR="wget-${VERSION}"
TARBALL="wget-${VERSION}.tar.gz"

SRC1=(
http://ftp.gnu.org/gnu/wget/${TARBALL}
)

MD5SUMS=(
2db6f03d655041f82eb64b8c8a1fa7da
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --sysconfdir=/etc --libdir=/usr/$LIBSDIR --with-ssl || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  mv $TMPROOT/etc/wgetrc $TMPROOT/etc/wgetrc.tmpnew || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://ftp.gnu.org/gnu/wget/'
  VERSION_STRING='wget-%version%.tar.gz'
  VERSION_FILTERS='latest'
}
