#!/bin/bash

DISABLE_MULTILIB=1

VERSION="2.21"

DIR="which-${VERSION}"
TARBALL="which-${VERSION}.tar.gz"

SRC1=(
http://ftp.gnu.org/gnu/which/${TARBALL}
)

MD5SUMS=(
097ff1a324ae02e0a3b0369f07a7544a
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --build=$BUILDHOST \
    --host=$BUILDTARGET --prefix=/usr || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://ftp.gnu.org/gnu/which/'
  VERSION_STRING='which-%version%.tar.gz'
}
