#!/bin/bash

DISABLE_MULTILIB=1

VERSION="3.11"

ONLY32=1

DIR="wine-$VERSION"
TARBALL="wine-${VERSION}.tar.xz"

SRC1=(
https://dl.winehq.org/wine/source/$(echo $VERSION | cut -f-2 -d'.')/$TARBALL
https://dl.winehq.org/wine/source/$(echo $VERSION | cut -f-1 -d'-')/$TARBALL
https://dl.winehq.org/wine/source/$(echo $VERSION | cut -f-1 -d'.').x/$TARBALL
)

MD5SUMS=(
34ffa2f1177207bdd92bafbc480db105
)

build(){
  unset CFLAGS CXXFLAGS
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --target=$BUILDTARGET \
    --prefix=/usr --libdir=/usr/$LIBSDIR || return 1
  make || return 1
  make install prefix=$TMPROOT/usr libdir=$TMPROOT/usr/$LIBSDIR || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='https://www.winehq.org/'
  VERSION_STRING='Wine %version% Released'
  VERSION_FILTERS="rc"
}
