#!/bin/bash

DISABLE_MULTILIB=1

VERSION="1.3.32"

ONLY32=1

DIR="wine-${VERSION}"
TARBALL="wine-${VERSION}.tar.bz2"

SRC1=(
http://ibiblio.org/pub/linux/system/emulators/wine/${TARBALL}
)

MD5SUMS=(
2f8655434711b0ef11247f1bf7c28d13
)

build(){
  unset CFLAGS CXXFLAGS
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR || return 1
  make || return 1
  make install prefix=$TMPROOT/usr libdir=$TMPROOT/usr/$LIBSDIR || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://ibiblio.org/pub/linux/system/emulators/wine/'
  VERSION_STRING='wine-%version%.tar.bz2'
  VERSION_FILTERS="docs rc"
}
