#!/bin/bash

DISABLE_MULTILIB=1

VERSION="2.0"

ONLY32=1

DIR="wine-$VERSION"
TARBALL="wine-${VERSION}.tar.bz2"

SRC1=(
http://prdownloads.sourceforge.net/wine/${TARBALL}
)

MD5SUMS=(
fde8a855080279f74fb2e9ccec926db7
)

build(){
  unset CFLAGS CXXFLAGS
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --target=$BUILDTARGET \
    --prefix=/usr --libdir=/usr/$LIBSDIR || return 1
  make || return 1
  make install prefix=$TMPROOT/usr libdir=$TMPROOT/usr/$LIBSDIR || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://sourceforge.net/projects/wine/files/Source/'
  VERSION_STRING='wine-%version%.tar.bz2'
  VERSION_FILTERS="docs rc"
}
