#!/bin/bash

DISABLE_MULTILIB=1

VERSION="0.4.0"

DIR="xcb-util-keysyms-${VERSION}"
TARBALL="xcb-util-keysyms-${VERSION}.tar.bz2"

SRC1=(
http://xcb.freedesktop.org/dist/${TARBALL}
)

MD5SUMS=(
1022293083eec9e62d5659261c29e367
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
    CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR --sysconfdir=/etc --localstatedir=/var || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://xcb.freedesktop.org/dist/'
  VERSION_STRING='xcb-util-keysyms-%version%.tar.bz2'
}
