#!/bin/bash

DISABLE_MULTILIB=1

VERSION="1.0.4"

DIR="xcursor-themes-${VERSION}"
TARBALL="xcursor-themes-${VERSION}.tar.bz2"

SRC1=(
http://xorg.freedesktop.org/releases/individual/data/${TARBALL}
)

MD5SUMS=(
fdfb0ad9cfceed60e3bfe9f18765aa0d
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR --sysconfdir=/etc --localstatedir=/var || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://xorg.freedesktop.org/releases/individual/data/'
  VERSION_STRING='xcursor-themes-%version%.tar.bz2'
  MIRRORS=(
    'http://xorg.freedesktop.org/releases/individual/data/xcursor-themes-%version%.tar.bz2'
  )
}
