#!/bin/bash

DISABLE_MULTILIB=1

#1.4.0 doesn't work on my laptop (emachines e525)

VERSION="1.3.0"

DIR="xf86-input-synaptics-${VERSION}"
TARBALL="xf86-input-synaptics-${VERSION}.tar.bz2"

SRC1=(
http://xorg.freedesktop.org/releases/individual/driver/${TARBALL}
)

MD5SUMS=(
b4e58eba1bdca13f0929a4b03b262135
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR --sysconfdir=/etc --localstatedir=/var \
    --with-xorg-module-dir=/usr/$LIBSDIR/X11/modules || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://xorg.freedesktop.org/releases/individual/driver/'
  VERSION_STRING='xf86-input-synaptics-%version%.tar.bz2'
  MINOR_VERSION=1.3
  VERSION_FILTERS=99
}
