#!/bin/bash

DISABLE_MULTILIB=1

VERSION="1.9.1"

DIR="xf86-input-synaptics-${VERSION}"
TARBALL="xf86-input-synaptics-${VERSION}.tar.bz2"

SRC1=(
http://xorg.freedesktop.org/releases/individual/driver/${TARBALL}
)

MD5SUMS=(
cfb79d3c975151f9bbf30b727c260cb9
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR --sysconfdir=/etc --localstatedir=/var \
    --with-xorg-module-dir=/usr/$LIBSDIR/X11/modules || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://xorg.freedesktop.org/releases/individual/driver/'
  VERSION_STRING='xf86-input-synaptics-%version%.tar.bz2'
  VERSION_FILTERS=99
}
