#!/bin/bash

DISABLE_MULTILIB=1

VERSION="1.0.11"

DIR="xf86-video-nouveau-${VERSION}"
TARBALL="xf86-video-nouveau-${VERSION}.tar.bz2"

SRC1=(
http://xorg.freedesktop.org/releases/individual/driver/${TARBALL}
)

MD5SUMS=(
a0d2932d84ba10c4933c8332c9a
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR --sysconfdir=/etc --localstatedir=/var \
    --with-xorg-module-dir=/usr/$LIBSDIR/X11/modules || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://xorg.freedesktop.org/releases/individual/driver/'
  #VERSION_FILTERS='.90 .99'
  VERSION_STRING='xf86-video-nouveau-%version%.tar.bz2'
}
