#!/bin/bash

DISABLE_MULTILIB=1

VERSION="1.20.0" ## 1.19.6 causes crashes on startup. 1.19.5 last good

DIR="xorg-server-${VERSION}"
TARBALL="xorg-server-${VERSION}.tar.bz2"

SRC1=(
http://xorg.freedesktop.org/releases/individual/xserver/${TARBALL}
)

MD5SUMS=(
c1ca1ea0a905ea788da03c77cc38b06e
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1

  CC="$CC $BUILD" CXX="$CXX $BUILD" CFLAGS="$CFLAGS -Wredundant-decls" \
    ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR --sysconfdir=/etc --localstatedir=/var \
    --with-module-dir=/usr/$LIBSDIR/X11/modules || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://xorg.freedesktop.org/releases/individual/xserver/'
  VERSION_STRING='xorg-server-%version%.tar.bz2'
  VERSION_FILTERS='\.99 \.90 1.1[6-7] 1.19.6'
}
