#!/bin/bash

DISABLE_MULTILIB=1

VERSION="333"

DIR="xterm-${VERSION}"
TARBALL="xterm-${VERSION}.tgz"

SRC1=(
https://invisible-mirror.net/archives/xterm/${TARBALL}
)

MD5SUMS=(
32a810c436db81775706f9cbe7efc290
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR --sysconfdir=/etc --localstatedir=/var || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='https://invisible-mirror.net/archives/xterm/'
  VERSION_STRING='xterm-%version%.tgz'
}
