#!/bin/bash

DISABLE_MULTILIB=1

VERSION="1.1.7"

DIR="xvidcap-${VERSION}"
TARBALL="xvidcap-${VERSION}.tar.gz"

SRC1=(
http://prdownloads.sourceforge.net/xvidcap/${TARBALL}
)

MD5SUMS=(
b39a682d3ef9fcbf424af771936780e2
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  
cat << "EOF" | patch -Np1 || return 1
diff -Naur xvidcap-1.1.7/src/capture.c xvidcap-1.1.7.patched/src/capture.c
--- xvidcap-1.1.7/src/capture.c	2008-05-25 18:01:53.000000000 -0400
+++ xvidcap-1.1.7.patched/src/capture.c	2009-10-03 16:49:10.000000000 -0400
@@ -65,7 +65,7 @@
 #include <sys/ipc.h>
 #include <sys/shm.h>
 #include <X11/extensions/XShm.h>
-#include <X11/extensions/shmstr.h>
+#include <X11/extensions/shmproto.h>
 #ifndef SOLARIS
 #include <X11/extensions/extutil.h>
 #endif     // SOLARIS
diff -Naur xvidcap-1.1.7/src/codecs.c xvidcap-1.1.7.patched/src/codecs.c
--- xvidcap-1.1.7/src/codecs.c	2008-05-25 18:01:53.000000000 -0400
+++ xvidcap-1.1.7.patched/src/codecs.c	2009-06-09 15:56:54.000000000 -0400
@@ -43,8 +43,8 @@
 #include <locale.h>
 
 #ifdef USE_FFMPEG
-#include <ffmpeg/avcodec.h>
-#include <ffmpeg/avformat.h>
+#include <libavcodec/avcodec.h>
+#include <libavformat/avformat.h>
 #endif     // USE_FFMPEG
 
 #include "app_data.h"
diff -Naur xvidcap-1.1.7/src/main.c xvidcap-1.1.7.patched/src/main.c
--- xvidcap-1.1.7/src/main.c	2008-05-25 18:01:54.000000000 -0400
+++ xvidcap-1.1.7.patched/src/main.c	2009-06-09 16:00:13.000000000 -0400
@@ -45,7 +45,7 @@
 #include <locale.h>
 
 #ifdef USE_FFMPEG
-#include <ffmpeg/avcodec.h>
+#include <libavcodec/avcodec.h>
 #endif     // USE_FFMPEG
 
 #include "control.h"
@@ -217,9 +217,6 @@
 
     if (app)
         xvc_appdata_free (app);
-#ifdef USE_FFMPEG
-    av_free_static ();
-#endif
 }
 
 /**
diff -Naur xvidcap-1.1.7/src/xtoffmpeg.c xvidcap-1.1.7.patched/src/xtoffmpeg.c
--- xvidcap-1.1.7/src/xtoffmpeg.c	2008-05-25 18:01:54.000000000 -0400
+++ xvidcap-1.1.7.patched/src/xtoffmpeg.c	2009-06-09 16:18:48.000000000 -0400
@@ -56,13 +56,13 @@
 #include "xvidcap-intl.h"
 
 // ffmpeg stuff
-#include <ffmpeg/avcodec.h>
-#include <ffmpeg/avformat.h>
-#include <ffmpeg/avdevice.h>
+#include <libavcodec/avcodec.h>
+#include <libavformat/avformat.h>
+#include <libavdevice/avdevice.h>
 //#include <ffmpeg/dsputil.h>
-#include <ffmpeg/swscale.h>
-#include <ffmpeg/rgb2rgb.h>
-#include <ffmpeg/fifo.h>
+#include <libswscale/swscale.h>
+//#include <ffmpeg/rgb2rgb.h>
+#include <libavutil/fifo.h>
 #define swscale_isRGB(x) ((x)==PIX_FMT_BGR32 || (x)==PIX_FMT_RGB24 \
                         || (x)==PIX_FMT_RGB565 || (x)==PIX_FMT_RGB555 \
                         || (x)==PIX_FMT_RGB8 || (x)==PIX_FMT_RGB4 \
@@ -96,8 +96,7 @@
                         || (x)==PIX_FMT_YUVJ420P || (x)==PIX_FMT_YUVJ422P \
                         || (x)==PIX_FMT_YUVJ444P)
 
-#define PIX_FMT_ARGB32 PIX_FMT_RGBA32  /* this is just my personal
-                                        * convenience */
+
 
 /*
  * file globals
@@ -1248,7 +1247,11 @@
     st->codec->flags |= CODEC_FLAG2_FAST;
     // there is no trellis quantiser in libav* for mjpeg
     if (st->codec->codec_id != CODEC_ID_MJPEG)
+  #if LIBAVCODEC_VERSION_INT < ((52<<16)+(0<<8)+0)
         st->codec->flags |= CODEC_FLAG_TRELLIS_QUANT;
+  #else
+	st->codec->trellis = 1;
+  #endif
     st->codec->flags &= ~CODEC_FLAG_OBMC;
     // some formats want stream headers to be seperate
     if (oc->oformat->flags & AVFMT_GLOBALHEADER)
@@ -1346,7 +1349,7 @@
             // Solaris/SPARC, but need to do the conversion
             // for every frame we do it outside of this loop, cf.
             // below this matches both ARGB32 and ABGR32
-            input_pixfmt = PIX_FMT_ARGB32;
+            input_pixfmt = PIX_FMT_RGB32;
         } else {
             fprintf (stderr,
                      _
@@ -1699,7 +1702,7 @@
      * convert input pic to pixel format the encoder expects
      */
 #ifdef DEBUG
-    if (input_pixfmt == PIX_FMT_ARGB32)
+    if (input_pixfmt == PIX_FMT_RGB32)
         dump32bit (image, job->c_info);
     if (input_pixfmt == PIX_FMT_PAL8)
         dump8bit (image, (u_int32_t *) job->color_table);
@@ -1707,7 +1710,7 @@
 
     /** \todo test if the special image conversion for Solaris is still
      *      necessary */
-    if (input_pixfmt == PIX_FMT_ARGB32 && job->c_info->alpha_mask == 0xFF000000
+    if (input_pixfmt == PIX_FMT_RGB32 && job->c_info->alpha_mask == 0xFF000000
         && image->red_mask == 0xFF && image->green_mask == 0xFF00
         && image->blue_mask == 0xFF0000) {
         myABGR32toARGB32 (image);
EOF

  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR --sysconfdir=/etc || return 1
  make || return 1
  for x in C de es it; do
    touch doc/xvidcap/$x/xvidcap-${x}.omf.out || return 1
  done
  make install DESTDIR=$TMPROOT || return 1
  sed -i -e 's%XVidCap Screen Capture%Video Screen Capture%' \
    -e 's%X11 Screencam%Video Screen Capture%' \
    $TMPROOT/usr/share/applications/xvidcap.desktop || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://sourceforge.net/project/showfiles.php?group_id=81535&package_id=83441'
  VERSION_STRING='xvidcap-%version%.tar.gz'
  VERSION_FILTERS=rc
}
