#!/bin/bash

VERSION="5.2.2"

DIR="xz-${VERSION}"
TARBALL="xz-${VERSION}.tar.xz"

SRC1=(
http://tukaani.org/xz/${TARBALL}
)

MD5SUMS=(
e26772b69940085c0632589ab1d52e64
)

Tools_Build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --build=$BUILDHOST \
    --host=$BUILDTARGET --prefix=$TCDIR \
    --libdir=$TCDIR/$LIBSDIR || return 1
  make || return 1
  make install || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --prefix=/usr \
    --libdir=/usr/$LIBSDIR || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  mkdir -p $TMPROOT/bin || return 1
  mv -v $TMPROOT/usr/bin/{xz,lzma,lzcat,unlzma,unxz,xzcat} $TMPROOT/bin/ || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://tukaani.org/xz/'
  VERSION_STRING='xz-%version%.tar.xz'
  VERSION_FILTERS='alpha beta'
}
