#!/bin/bash

DONT_REMOVE=1
DISABLE_MULTILIB=1

VERSION="1.1.0"

DIR="yasm-${VERSION}"
TARBALL="yasm-${VERSION}.tar.gz"

SRC1=(
http://www.tortall.net/projects/yasm/releases/${TARBALL}
)

MD5SUMS=(
8392e5f2235c2c2a981e1a633f2698cb
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" ./configure --build=$BUILDHOST \
    --host=$BUILDTARGET --prefix=/usr || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://www.tortall.net/projects/yasm/releases/'
  VERSION_STRING='yasm-%version%.tar.gz'
}
