#!/bin/bash

DISABLE_MULTILIB=1
VERSION="1.2.0"

DIR="yasm-${VERSION}"
TARBALL="yasm-${VERSION}.tar.gz"

SRC1=(
http://www.tortall.net/projects/yasm/releases/${TARBALL}
)

MD5SUMS=(
4cfc0686cf5350dd1305c4d905eb55a6
)

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" CFLAGS="$CFLAGS -fPIC" \
  CXXFLAGS="$CXXFLAGS -fPIC" ./configure --build=$BUILDHOST \
    --host=$BUILDTARGET --prefix=/usr --libdir=/usr/$LIBSDIR || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://www.tortall.net/projects/yasm/releases/'
  VERSION_STRING='yasm-%version%.tar.gz'
}
