#!/bin/bash

DONT_REMOVE=1
VERSION="1.2.11"

DIR="zlib-${VERSION}"
TARBALL="zlib-${VERSION}.tar.gz"

SRC1=(
http://www.zlib.net/${TARBALL}
http://prdownloads.sourceforge.net/libpng/$TARBALL
)

MD5SUMS=(
1c9f62f0778697a09d36121ead88e08e
)

Tools_Build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" CFLAGS="$CFLAGS -fPIC" \
    ./configure --prefix=$TCDIR \
    --libdir=$TCDIR/$LIBSDIR || return 1
  make || return 1
  make install || return 1
  cd $SRCDIR || return 1
  rm -rf $DIR || return 1
}

build(){
  unpack_tarball $TARBALL || return 1
  cd $SRCDIR/$DIR || return 1
  CC="$CC $BUILD" CXX="$CXX $BUILD" CFLAGS="$CFLAGS -fPIC" \
    ./configure --prefix=/usr --libdir=/$LIBSDIR || return 1
  make || return 1
  make install DESTDIR=$TMPROOT || return 1
  mkdir -vp $TMPROOT/usr/$LIBSDIR || return 1
  mv $TMPROOT/$LIBSDIR/{libz.a,pkgconfig} \
    $TMPROOT/usr/$LIBSDIR/ || return 1
  cd ../ || return 1
  rm -rf $DIR || return 1
}

version_check_info(){
  ADDRESS='http://www.zlib.net/'
  VERSION_STRING='zlib-%version%.tar.gz'
}
